### ISSUE TITLE
app interferes with the Bluetooth connection between car and mobile phone

### ISSUE THREAD

**Issue by baukran** [corona-warn-app/cwa-app-ios#975] opened 2020-07-29 15:31 UTC
the app disrupts the bluetooth connection of the mobile phone and the car, that established calls can no longer be ended  the problem is known to Seat, but cannot be fixed there.  you either have to delete the app or connect the cell phone via the usb cable and carplay.  bluetooth no longer works

## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Technical details

- iOS Version:
- Device:

**Comment by Ein-Tim** [comment] 2020-07-29 15:49
Duplicate of #932

**Comment by SebastianWolf-SAP** [comment] 2020-07-29 18:04
Thanks, @Ein-Tim for mentioning the earlier issue. Closing this one as duplicate.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Closed by SebastianWolf-SAP** 2020-07-29 18:04 UTC
Labels: bug
