### ISSUE TITLE
After factory reset / backup: infinite loop with the on boarding screens

### ISSUE THREAD

**Issue by rainervonuns** [corona-warn-app/cwa-app-ios#1233] opened 2020-09-24 17:07 UTC
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

After a change to a new iPhone and automated re-installation from the backup, I'm stuck in an infinite loop with the welcome / on boarding screens. 
I can click through the 5 screens but than I'm back on the first screen again.   

## Expected behaviour

After clicking through the five screens, I should jump to the home screen of CWA. 

## Steps to reproduce the issue

1. Use a new iPhone (factory reset should also work)
2. Login with your Apple ID
3. Select use backup to configure iPhone
4. Wait till CWA is installed and settings are restored from the backup 
5. Open CWA
6. And you are in an infinite loop with the on boarding screens. 

## Technical details

- iOS Version: 13.7
- Device: iPhone SE 2020

## Additional context
Uninstalling the app and re-installation via App Store helped to solve the issue, but my data is lost. 

On the old device (iPhone 7, iOS 13.7) there was:
* Risk Assessment active 
* Warnings / Notifications allowed

**Comment by Ein-Tim** [comment] 2020-09-24 17:10
Duplicate of: https://github.com/corona-warn-app/cwa-app-ios/issues/754

**Comment by Ein-Tim** [comment] 2020-09-24 17:12
Please also see the related FAQ entry:

https://www.coronawarn.app/en/faq/?search=Backup#migration_Apple

**Closed** 2020-09-24 17:12 UTC
Labels: bug

**Comment by heinezen** [comment] 2020-09-24 17:31
Duplicate of #754
