### ISSUE TITLE
Vaccination Certificate rules check fails for Netherlands

### ISSUE THREAD

**Issue by jwildeboer** [corona-warn-app/cwa-app-ios#3291] opened 2021-08-01 16:00 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11
- iOS version: 14.7.1
- App version: 2.6.2(0)

## Describe the bug

I have added both my vaccination certificates to the App. When I do a validity check for any country, it comes back as "valid" - except for the Netherlands, which returns "Certificate could not Be Validated completely"

## Steps to reproduce the issue

Scan certificates, make sure CWA marks them as valid.

Open certificates tab

Use "check validity"

Select Netherlands

![image](https://user-images.githubusercontent.com/873028/127777422-7b197ffc-124a-4ea6-b06d-9da328c450fa.png)

![image](https://user-images.githubusercontent.com/873028/127777436-931ee0d3-658c-4fa3-897c-611d1eea69d1.png)

## Expected behaviour

Certificate is valid and satisfies all rules. So should be shown as "valid"

**Comment by jucktnich** [comment] 2021-08-01 16:31
Probably a duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/671

**Comment by jwildeboer** [comment] 2021-08-01 16:39
> Probably a duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/671

Seems to be. But why is that one in documentation? Doesn't really make sense to me. It's an app issue, IMHO.

**Comment by jwildeboer** [comment] 2021-08-01 16:47
Ok. So after reading the other issue, I gather:

- my certificate uses schema V1.0, whereas the Dutch rules require V1.3

My question thus becomes: Why doesn't the CWA give that information as a warning/error message but instead a long list of issues with my certificate that are unrelated to core problem - a schema version mismatch?

**Comment by jucktnich** [comment] 2021-08-01 19:01
The bug does affect both OSs so it's in the documentation repo.
I suggest to post your question in the other issue and close you're issue in favour of the other.

**Comment by jwildeboer** [comment] 2021-08-01 21:33
Reluctantly closing this but absolutely not happy with the current situation. Elevated by the fact that I actually am Dutch and was planning to visit family and am now confused about if my certificate will be accepted or not.

**Closed** 2021-08-01 21:34 UTC
Labels: bug

**Comment by dsarkar** [comment] 2021-08-02 10:17
Internal Tracking ID: [EXPOSUREAPP-8786](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8786)
