### ISSUE TITLE
Time of risk calculation

### ISSUE THREAD

**Issue by AnOtherMuenchner** [corona-warn-app/cwa-app-ios#1515] opened 2020-11-15 18:19 UTC
I am wondering why the app for iOS does the next risk calculation always at least 24 hours after the last. So the comparision shifts every day a little bit.

While the app for Android seems to do it once every day, but at the most early possible points of time, which means that it can be one day e.g. at 11:00 am and the next at 6:30 am.

**Comment by thomasaugsten** [comment] 2020-11-15 20:52
Both OS has a rate limit for the risk calculation. 
iOS will reset the limit after 24h and Android at 01:00 oClock. This leads to a different behavior.

**Comment by dsarkar** [comment] 2020-11-17 12:12
Dear @AnOtherMuenchner, 

Your question seems to be answered satisfactorily by @thomasaugsten, and if you have no futher questions, please consider closing this issue.

Best wishes, 
DS

---
Corona-Warn-App Open Source Team

**Comment by AnOtherMuenchner** [comment] 2020-11-18 08:37
Not really.

It seems possible that the app does a check on 1pm and the next day on 7am. Without problems.

Such a calculation protocol is done when the app is opened without internet connection. The next time when it has an connectin, the calculation can be manually triggered.

I am using iOS 14.2 and the lastest version of the app.

**Comment by ndegendogo** [comment] 2020-11-18 10:59
@AnOtherMuenchner the check will fail on iOS if you have no internet coverage (don't know if the same is true for Android).
iOS implementation of ENF needs internet.

**Comment by sin-azucar** [comment] 2020-11-18 11:09
@AnOtherMuenchner I think you have a valid point that the risk calculation interval is more restrictive than it has to be. The rate limit has been loosened on iOS side since ENF first came out.

But my understanding is that this will soon resolve itself because CWA will switch to doing multiple checks per day in the next version (based on the hourly published infection keys). ➡️ https://github.com/corona-warn-app/cwa-app-ios/pull/1492

**Comment by Ein-Tim** [comment] 2020-11-20 13:01
BTW this is a duplicate of: https://github.com/corona-warn-app/cwa-wishlist/issues/133

**Comment by dsarkar** [comment] 2020-11-27 10:19
Dear @AnOtherMuenchner, @ndegendogo, @Ein-Tim, @sin-azucar 

Thanks again for contributing and detailed feedback. Be aware of the following:

- Using WIFI: Updates will occur up to 6 times / 24 h
- Using mobile data network: Update about once / day

Please, continue reporting your observations regarding update time here https://github.com/corona-warn-app/cwa-app-ios/issues/916 

I think with these changes, this issue becomes obsolete. @AnOtherMuenchner I suggest closing this issue.

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-11-27 10:20
Duplicate of #916

**Comment by ndegendogo** [comment] 2020-11-27 19:28
@dsarkar I don't think this is a duplicate of #916 

#916 is actually a bug report about unreliable checking task, especially from background.
Whereas this issue started as a question, then the request for a more frequent checking schedule was made.
So, maybe it could be considered as duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/466
Or maybe even the request as fulfilled with 1.7

@AnOtherMuenchner what do you think?

**Comment by Ein-Tim** [comment] 2020-11-27 19:56
If we all search for duplicates, please see my comment [above](https://github.com/corona-warn-app/cwa-app-ios/issues/1515#issuecomment-731156853) 😀

**Comment by dsarkar** [comment] 2020-11-28 15:26
Dear @ndegendogo, @Ein-Tim, @AnOtherMuenchner,

Agreed, the original proposal is not a duplicate but related to various issues.


Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by AnOtherMuenchner** [comment] 2020-11-29 09:29
> #916 is actually a bug report about unreliable checking task, especially from background.
> Whereas this issue started as a question, then the request for a more frequent checking schedule was made.
> So, maybe it could be considered as duplicate of [corona-warn-app/cwa-documentation#466](https://github.com/corona-warn-app/cwa-documentation/issues/466)
> Or maybe even the request as fulfilled with 1.7
> 
> @AnOtherMuenchner what do you think?


Before the update to 1.7 I had the same issue. The risk calculcation only updated when I opened the app, no matter if connected to W-Lan or mobile internet. In this case, I could see the download of data and update of risk calculation.

Since the update to 1.7 this issue seems to be gone. The risk calculcation does not update anymore when I open the app. Instead the time stamp of risk calculation says that the update has been done at same time point in the past.

In the log I can see, there is an update in the morning, when the mobile connects to a W-Lan for the first time of the day. During the night, W-Lan and mobile internet is switched off.

Then there is an update after slightly more (?) than 4 hours, when the mobile stays connected to the W-Lan. I cannot say if this is related to usage of the phone. At least, there seems to be a re-check if more than 4 hours have been passed, the mobile has not been connected to W-Lan during the end of the 4-hour-interval and then the mobile is reconnected to W-Lan.

When I am on the mobile net, the app update once about 4 hours after the last update and not anymore, as long as I do not return to a W-Lan.

At the moment, I cannot say anything about the reliability of the update interval, since for interest about the functionality I opened the app at times since the last update. I will try to have my fingers off the next days. :-)

**Comment by dsarkar** [comment] 2020-11-30 08:53
Dear @AnOtherMuenchner,  Thanks for the feedback. We appreciate if you keep monitoring and give us a feedback.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-11-30 10:30
Hi @AnOtherMuenchner, thanks for the detailed feedback. Let's monitor it for a few days, and please report your observations. 

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by AnOtherMuenchner** [comment] 2020-12-02 18:56
Here are some more information about the updates of the risk status.

**Day 1:**

Network connection:

Network:  8:30 WLAN on, ~14:30 Wifi -> LTE, ~18:30 LTE -> WiFi.  Maybe that I ran through same Wifi-Hotspot to which I can connect during LTE-Time.

Updates: 8:32 (a), 12:36 (a), 16:50 (m), 20:;57 (m)

a -> automatic
m -> manually triggered by opening the app.

** Day 2 **

Network:  Wifi on: ~5:45, ~6:45 switch to LTE, ~16:00 switch to WiFi
Updates: 5:48 (a), 9:48(a), 16:39(a), 20:57 (a)

** Day 3 **

Network: Wifi on: ~6:33, Wifi connection lost: ~12:30, Wifi reconnection ~13:30, Wifi connection lost: ~17:00, Wifi reconnection ~18:00, Wifi off: ~22:00

Updates: 6:33(a), 10:36(a), 14:41(a), 18.43(a)

** Today **

Network: Wifi on: ~6:30, Wifi connection lost: ~12:45, Wifi reconnection: ~13:30, Wifi connection lost: ~15:20, Wifi reconnection ~16:30. 

Updates: 6:33 (a), 10:37(a), 14:37 (a): 18:40 (a)


It seems that the first update of the day is done immediately after the first connection to Wifi on the day.

**Comment by Ein-Tim** [comment] 2020-12-03 05:41
So I think we can close this, or @AnOtherMuenchner?

**Comment by dsarkar** [comment] 2020-12-07 11:40
Dear @AnOtherMuenchner, @Ein-Tim, and community, 

We understand that this issue is now fixed with CWA version 1.7.1. Thanks again for your contributions. However, should the problem re-occur, re-open this issue, please.

Best regards,
DS

---
Corona-Warn-App Open Source Team

**Closed by dsarkar** 2020-12-07 11:40 UTC
Labels: duplicate, question
