### ISSUE TITLE
Unexpected Message

### ISSUE THREAD

**Issue by iTommix** [corona-warn-app/cwa-app-ios#695] opened 2020-06-17 17:59 UTC
Yesterday and Today i'll get this Message from my iPhone. I didn't change/leave my preferred Region, so it must be a bug.

![IMG_6906](https://user-images.githubusercontent.com/22579516/84932599-d5846380-b0d4-11ea-89de-bd5bc0adba2e.jpeg)

**Comment by tens0rfl0w** [comment] 2020-06-17 18:08
Duplicate of #645

This issue is related to the framework behind the application, so it's not fixable by the dev team. Already reported to Apple.

**Closed** 2020-06-17 18:10 UTC
Labels: bug
