### ISSUE TITLE
Lost encounters after the latest update

### ISSUE THREAD

**Issue by healther** [corona-warn-app/cwa-app-ios#1713] opened 2020-12-17 18:51 UTC
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone SE (2020)
- iOS Version: 14.3
- App Version: 1.9.1(0) <note: this is annoyingly hard to find>

## Describe the bug

Before getting the latest update from the AppStore today my CWA showed 4 encounters with low risk. After updating it shows no encounters. I'm unsure whether this fixes itself again but as of now it looks like the update ate my low risk encounters. 

## Steps to reproduce the issue

Unknown

## Expected behaviour

Seeing the same amount of encounters pre and post update (at least within 5 mins)

**Comment by RalphRichter** [comment] 2020-12-17 19:20
Same here on iOS 14.3 iPhoneMax 12 Pro and latest app update

EXposure Framework in iOS Settings App is showing machen keys, but App shows nothing

**Comment by Ein-Tim** [comment] 2020-12-17 19:47
Duplicate of #1703

**Comment by Ein-Tim** [comment] 2020-12-17 19:47
See my comment here for more information: https://github.com/corona-warn-app/cwa-app-ios/issues/1703#issuecomment-747494860

**Comment by dsarkar** [comment] 2020-12-18 08:05
Dear @RalphRichter, @healther,

Thanks for posting here. Indeed, this seems not a bug. See the links provided by @Ein-Tim and then close this issue, please.

Best wishes, 
DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment] 2020-12-20 18:29
@healther 
Could you close this please?

**Closed** 2020-12-20 20:25 UTC
Labels: duplicate
