### ISSUE TITLE
[iOS14 Public Beta 2] App crashing without opening

### ISSUE THREAD

**Issue by cwFry** [corona-warn-app/cwa-app-ios#892] opened 2020-07-11 13:48 UTC
Hi, 

i installed the public beta of ios14 today. The app crashes directly after opening.
After re-installing the app, i can't get pass the "Receive Warnings and Identify Risks" screen. The os asked for permissions to display notifications, but after approvement nothing happens. After another re-installation and rejecting the request, no further progress. Can click on "Next" or "Do not Allow"but no response from the app.

Not sure, if its a problem of the app or iOS14. The setting for "COVID-19 Exposure Logging" states, that the logging and notifications are not available in my region. My region is Germany (residing in Mannheim).

Thanks a lot for your effort and keep up the spriti!

**Comment by n-thumann** [comment] 2020-07-11 13:58
Duplicate of #749. CWA is not working on iOS 14 Beta yet, see https://www.coronawarn.app/en/faq/#ios_14_beta ✌️

**Comment by cwFry** [comment] 2020-07-11 14:00
> Duplicate of #749. CWA is not working on iOS 14 Beta yet, see https://www.coronawarn.app/en/faq/#ios_14_beta ✌️

Sorry, my bad! Thanks for the fast reply.

**Closed** 2020-07-11 14:27 UTC
