### ISSUE TITLE
COVID-19 Exposure Notifications may not be supported by “Coronoa-Warn” in this region.

### ISSUE THREAD

**Issue by kkaefer** [corona-warn-app/cwa-app-ios#731] opened 2020-06-19 18:05 UTC
I got this system notification about CWA. It is the second time I've received it since Tuesday.

![IMG_D57504EE6869-1](https://user-images.githubusercontent.com/52399/85166245-4c516600-b267-11ea-8372-2a53b47b0e08.jpeg)

> COVID-19 Exposure Notifications may not be supported by “Corona-Warn“ in this region. You should confirm which app you are using in Settings.

https://github.com/corona-warn-app/cwa-app-ios/issues/638 mentions this notification as well, however, my issue seems different.

- My region is set to Germany. I haven't changed it recently; in fact, it has always been set to Germany. The iPhone's language is set to English though.
- When going into the COVID-19 Exposure logging screen in the Settings app, "Exposure Logging" is enabled, although it also shows "Your exposure log has not been checked in the past 14 days".
- CWA shows "Exposure logging active". 
- I've never installed any other apps that use the contact tracing API.

## Technical details

- iOS 13.5.1, iPhone 11

**Comment by itinance** [comment] 2020-06-19 18:48
Same here. Germany/Berlin. It appeared after I have left my district for the first time after installation, spend some hours in another district and came back at home. Then the message appeared. 

If important: I have asked friends an hour ago and got many people having the same issue as well. Nobody of them left the country or changed region-settings in this period from first launch until the message appeared.

**Comment by tens0rfl0w** [comment] 2020-06-19 23:04
Duplicate of #645 

This is a known bug from the EN framework itself, not the app. Exposure logging will just continue to work normal, so you can ignore this message (I know it gets annoying😅). Probably this will be fixed in a future iOS software update, but the app dev team can't do anything about, because as mentioned, the notification comes from OS directly.

**Comment by itinance** [comment] 2020-06-20 07:09
Thanks for clarifying, @tens0rfl0w. As long as this is not fixed from iOS, there should be an info displayed to the users describing that this could happen without any negative impacts.

**Comment by wjv** [comment] 2020-06-21 09:18
I'm also experiencing this issue. My phone is set to region *Germany*, but language *English (UK)*.

I may be mistaken (and please correct me if I am!), but this seems different from #645, which appears to cover not being able to switch on exposure notification at all.

In my case, exposure notification appears to be activated in the app: Corona-Warn reports "No exposure up to now" after 5 days of use. However, in *Settings → Privacy → Health → COVID-19 Exposure Logging*, the operating system reports that the exposure log has not been checked in the past 14 days, as reported by @kkaefer.

**Comment by tkowark** [comment] 2020-06-21 11:32
This really seems to be the very same issue as described in #645. Hopefully that will be resolved in iOS 13.6. Until then, we'll add it to our FAQ as noted in the other issue.

**Closed by tkowark** 2020-06-21 11:32 UTC
Labels: bug

**Comment by wjv** [comment] 2020-06-22 06:41
Thanks @tkowark. Since I'm not familiar with what's going on here, I'll take your word for it.

I would just like to document the troubling (?) fact that there's simply a discrepancy between the app (which seems to believe it's checking exposure) and iOS (which seems to say the app is not accessing the exposure log at all). See attached screenshots.

(Apologies for adding more discussion to a closed issue.)

![IMG_0914](https://user-images.githubusercontent.com/295282/85255716-1bd61b80-b463-11ea-8339-9eab3a1ad346.jpeg)

![IMG_0915](https://user-images.githubusercontent.com/295282/85255733-242e5680-b463-11ea-9f90-afac8e92120b.jpeg)

![IMG_0916](https://user-images.githubusercontent.com/295282/85255765-327c7280-b463-11ea-9c93-46dea29e5ebb.jpeg)

**Comment by tkowark** [comment] 2020-06-22 07:18
No worries, always feel free to ask follow up questions. Running logging actively and accessing the exposure log are indeed different things. The exposure log is only accessed if the cwa-server returned any keys to check against. Currently that is not yet the case: https://www.coronawarn.app/de/faq/#no_log_check

**Comment by wjv** [comment] 2020-06-22 07:25
Thank you @tkowark, that answers my question. I should've checked the FAQ first! 🙃

**Comment by Alexcirlan** [comment] 2020-07-04 06:35
Same problem here, i thought is iOS14 related because for me it stopped working after installing the beta. Hope they will solve it on Monday when they will supposedly launch beta2
