### ISSUE TITLE
Add app version to AppInformationViewController 

### ISSUE THREAD

**Issue by frnkschmtt** [corona-warn-app/cwa-app-ios#83] opened 2020-06-01 08:58 UTC
## Current Implementation

<img width="378" alt="Screenshot 2020-06-01 at 10 50 24" src="https://user-images.githubusercontent.com/3415019/83392680-ca071c00-a3f5-11ea-9edf-3f7290c09bcf.png">

## Suggested Enhancement

<img width="378" alt="Screenshot 2020-06-01 at 10 49 05" src="https://user-images.githubusercontent.com/3415019/83392687-cd020c80-a3f5-11ea-9ad9-91d60b5a496b.png">

## Expected Benefits

Before pushing a public release to app store a version label should be shown somewhere in the UI. This will be beneficial for issue reporting and QA in the future.

**Comment by haosap** [comment] 2020-06-01 20:21
Hi @EisvogelSAP ,
Does the version passed the Ux check?

**Comment by haosap** [comment] 2020-06-03 18:01
Hi @EisvogelSAP ,
Can we close this one?

**Comment by inf2381** [comment] 2020-06-05 07:05
Merged and approved by design

**Closed by inf2381** 2020-06-05 07:05 UTC
Labels: enhancement
