### ISSUE TITLE
Ios14

### ISSUE THREAD

**Issue by jbuerger-ios14** [corona-warn-app/cwa-app-ios#757] opened 2020-06-23 20:10 UTC
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Describe the bug
With ios14 app starts with empty screen; also in prefs it says no Corona app supported in your region.

## Technical details

- iOS Version: 14.0 (18A5301v)
- Device: iPhone 7

**Comment by ferdinand** [comment] 2020-06-23 20:36
> ## Avoid duplicates
> * [ ]  Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
> * [ ]  Bug is not already reported in another issue

Why did you ignore these points?

It's mentioned [here](https://www.coronawarn.app/en/faq/#ios_14_beta) in the FAQ and a duplicate of #749 and #756.

**Closed** 2020-06-23 21:23 UTC
Labels: bug

**Comment by jbuerger-ios14** [comment] 2020-06-23 21:42
So sorry for not respecting your guidelines. 
Main reason: Did it on the iPhone, and GitHub is not exactly mobile friendly - or even user friendly for people not in your developer community. A more user friendly feedback channel for all the other people out there might be not so bad an idea.  
Also, did a quick search, came up with nothing. So, my bad. Won’t do it again.
Nevertheless, thanks that you obviously have an eye on things.
Take care.
Best
Jürgen Bürger.


Am 23.06.2020 um 22:37 schrieb ferdinand <notifications@github.com>:
