### ISSUE TITLE
An error occurred during exposure logging. EN Code: 2

### ISSUE THREAD

**Issue by tom-georg** [corona-warn-app/cwa-app-ios#1369] opened 2020-10-20 09:13 UTC
## Describe the bug

Every time I start the app I get the Error:
An error occurred during exposure logging. EN Code: 

The following steps didn't help:
I reinstalled the app. 
I rebooted my phone.
I deactivated exposure logging on in the iOS settings.

## Steps to reproduce the issue

The error occurs every time I start the app.

## Technical details

- iOS Version: 14.02
- Device: iPhone 11

![IMG_AB148923B8E0-1](https://user-images.githubusercontent.com/4346391/96565869-34492c00-12c5-11eb-9f8e-61d0016d5996.jpeg)

**Comment by sin-azucar** [comment] 2020-10-20 09:29
Duplicate of #1339 .

**Comment by heinezen** [comment] 2020-10-20 10:38
Hey @tom-georg ,

Thanks for your feedback. As @sin-azucar already pointed out, your bug is already reported in https://github.com/corona-warn-app/cwa-app-ios/issues/1339. Please continue the discussion there if you have further input on the issue. I'll close this issue as a duplicate.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-10-20 10:38
Duplicate of #1339

**Closed by heinezen** 2020-10-20 10:38 UTC
Labels: bug, duplicate
