### ISSUE TITLE
Huge battery drain [iOS 14.4 iPhone SE1]

### ISSUE THREAD

**Issue by tzschies** [corona-warn-app/cwa-app-ios#2290] opened 2021-03-29 06:37 UTC
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone SE 1. Generation
- iOS Version: 14.4.2
- App Version: 1.15.1

## Describe the bug

There is a huge battery drain over night. The phone is charged to nearly 100%, but not connected to a charging cable over night. In the morning the battery is down to 0% and the phone switched off. 

## Steps to reproduce the issue

1. Install CWA
2. Charge to 100%
3. Wait 6 to 8 hours, while doing nothing with the phone
4. Look at the battery status: 
![IMG_11222060BFB2-1](https://user-images.githubusercontent.com/67805460/112795505-e81ac880-9068-11eb-9163-8733db125a2a.JPEG)
If I click on the details for each hour, there is only the "Begegnungsmitteilungen" mentioned. And as you can see on the screenshot, there is really a huge drain from 10pm to 6am without doing anything. 

## Expected behaviour

For a comparison, I've deleted the CWA and if you then look at the battery status: 
![IMG_9750](https://user-images.githubusercontent.com/67805460/112795757-434cbb00-9069-11eb-9383-94b20faf8f32.PNG)
It seems quite normal. The capacity went down from 50% to 40% or something similar over night. This should be the expected behavior, even with CWA installed. 

## Possible Fix

Can't tell 

## Additional context

Just to say, not sure if the problem was initiated from an iOS update (14.4) or a CWA update. Can't reproduce this, because I have no backups with older iOS versions (or CWA. versions). The only thing I can say, if I delete the app, the battery drain is gone. And it happens with two phones (both iPhone SE 1.Generation). One of those two phones has a new battery (5 months old), so the battery itself is ok. 

--- 

Related issues are:
#1823
#1664
#912
#937
#671

---
Internal Tracking ID: [EXPOSUREAPP-6013](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6013)

**Comment by thomasaugsten** [comment] 2021-03-29 06:41
Hi,

both images shows a diagramm for 29.03. can you explain the different of the two screenshots?

**Comment by tzschies** [comment] 2021-03-29 06:51
As I mentioned, there are two phones in our household. I deleted the app on the second phone (second screenshot). I've tried it on both phones, but I have no screenshots (just these two for this morning) 

Can try it again next night and delete the app again on the first phone, and charge it again to 100% for a better comparison, and make then an additional screenshot.

**Comment by dsarkar** [comment] 2021-03-29 07:04
Internal Tracking ID: [EXPOSUREAPP-6013](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6013)

**Comment by Ein-Tim** [comment] 2021-03-29 08:09
Hey @tzschies 

First of all, it is normal that during the night/if the phones not used "Begegnungsmitteilungen" show 100% used, since no other apps were running.

It would be perfect if you could do what you said in https://github.com/corona-warn-app/cwa-app-ios/issues/2290#issuecomment-809119192.
Please do it as follow:

1. Charge both phones to 100%
2. Activate flight mode
3. Switch WLAN and Bluetooth back on again
4. Wait for the said 6-8 hours
5. Report back here


Please also let us know:
iOS 14.4.2 on both phones? 
Original or replaced batteries? 
Battery health of the two phones (can be found in the settings)

Thank you very much! 

Related issues are: 
#1823
#1664
#912
#937
#671

**Comment by Ein-Tim** [comment] 2021-04-24 18:32
@tzschies 

Could you give us an update wether you still experience this?

**Comment by vasilevalex** [comment] 2021-05-08 19:48
I had the same issue. But after updating iOS to 14.5.1 it became significantly worse.
For 7 hours without activity my iPhone SE battery goes from 100% to 10% Before 14.5.1 it could at least survive a day, but now it's impossible. On screenshots you can see, that last 2 days (the moment, I upgraded to 14.5.1) battery usage highly increased (even thought phone usage was minimum).
![20210508_193743000_iOS](https://user-images.githubusercontent.com/29298979/117551512-bbce7080-b046-11eb-9a16-70742a7e8d97.png)
![20210508_193807000_iOS](https://user-images.githubusercontent.com/29298979/117551514-c25ce800-b046-11eb-917f-7bdaeb7538d1.png)

**Comment by jucktnich** [comment] 2021-05-08 19:52
That iOS 14.5.1 uses significant more battery is known by apple and not CWA related I think. iOS 14.6 Beta 2 solved the problem for me.

**Comment by Ein-Tim** [comment] 2021-05-08 20:06
@vasilevalex 

Did you try to verify that this problem is related to the Corona-Warn-App? 
I'd suggest that you do a test:
Don't use your phone for 7 hours (while you sleep) with active CWA. Put the phone into flight mode but keep Bluetooth & WLAN ok. 
Now do the same but with inactive CWA (deactivate via "Exposure Logging"). 

If the battery is significantly lower (I would expect a difference from max. 15 percent) with active CWA we can be sure that CWA/Exposure Notification is the problem.

Also note what @jucktnich said, I can confirm worse battery usage in 14.5.1.

**Comment by vasilevalex** [comment] 2021-05-08 20:10
@Ein-Tim 
I'll make these tests. Will report here.

**Comment by Ein-Tim** [comment] 2021-05-08 20:12
Thank you @vasilevalex!

What would be also nice to know is what I've written here: https://github.com/corona-warn-app/cwa-app-ios/issues/2290#issuecomment-809168927

**Comment by dsarkar** [comment] 2021-05-09 07:40
@vasilevalex Thanks for the report, we are standing by for your feedback.
@Ein-Tim Thanks.

**Comment by vasilevalex** [comment] 2021-05-10 07:27
So I had 2 nights with tests.
iPhone SE. Original battery. Battery health 82%.
Test 1:
iOS: 14.5.1
CWA fully disabled, local (Danish) app, using CWA is removed from device. Flight mode with WiFi and Bluetooth enabled.
For 8 hours battery goes from 100% to 29%.
![20210509_052654000_iOS](https://user-images.githubusercontent.com/29298979/117620850-31366000-b171-11eb-82c4-a16791e62749.png)

Then I could not wait and installed 14.6 beta2.
Test 2:
iOS: 14.6 beta 2
CWA fully enabled, local app is installed and active. Flight mode with WiFi and Bluetooth enabled.
For 7 hours battery goes from 100% to 72%.
It still shows that CWA consumes 60% of the battery:
![20210510_033457000_iOS](https://user-images.githubusercontent.com/29298979/117620867-3693aa80-b171-11eb-9ff3-7b9e22a55d4d.png)

So I guess, this is not the app problem. At least the CWA is not the source of the problem. Thanks for help.

**Comment by Ein-Tim** [comment] 2021-05-10 09:04
@vasilevalex 

No problem and nice to hear that CWA isn't the problem. It's normal that "Exposure Notifications" is shown as high battery consumer if you don't use your phone, since nothing else is running then. 

Have a nice week!

**Comment by Ein-Tim** [comment] 2021-05-30 21:37
Hey @tzschies, are you still experiencing battery problems on iOS 14.6 which can be nailed down to CWA?

**Comment by Ein-Tim** [comment] 2021-06-09 05:39
I think this issue is obsolete and we should follow up in #2849.

**Comment by heinezen** [comment] 2021-06-10 15:37
@Ein-Tim True, I'm closing

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-06-10 15:37 UTC
Labels: bug, mirrored-to-jira
