### ISSUE TITLE
WiFi Error w/o reason

### ISSUE THREAD

**Issue by Hermann12** [corona-warn-app/cwa-app-ios#1007] opened 2020-08-04 17:00 UTC
iOS 13.6
## Bug see picture. The App told me could not connect to Internet, but the connection is still there. Browser works. Phone shows connected.

![Warn-app](https://user-images.githubusercontent.com/32801929/89325022-7ed4e800-d688-11ea-92c7-fbdba22fa941.PNG)

**Comment by Ein-Tim** [comment] 2020-08-04 17:02
Which picture?

**Comment by daimpi** [comment] 2020-08-04 17:05
Duplicate of #942

**Comment by Hermann12** [comment] 2020-08-04 17:35
Switch off,switch on Covid-19-Kontaktmitteilungen solve the issue. Don't know why, but error disappears and looks right now.

**Comment by Ein-Tim** [comment] 2020-08-04 19:44
@Hermann12, if the error is solved you could close the issue, please?

**Comment by GPclips** [comment] 2020-08-05 08:56
Hello @Hermann12,

thanks for reaching out. As @daimpi answered correctly, this indeed is a duplicate. 
Therefore I will go on and close this issue.

If you have additional comments you like to share with the community, please feel free to join the conversation here:  https://github.com/corona-warn-app/cwa-app-ios/issues/942.

Thank you,
LMM

Corona-Warn-App Open Source Team

**Closed by GPclips** 2020-08-05 08:56 UTC
Labels: bug, duplicate
