### ISSUE TITLE
Using different app for exposure notifications isn’t reflected in the UI

### ISSUE THREAD

**Issue by danielburkard** [corona-warn-app/cwa-app-ios#708] opened 2020-06-18 11:20 UTC
## Describe the bug

Since I’m in a different country (Italy) I installed the local app for covid-19 exposure logging. 
I was asked if I want to switch exposure logging to the new app, since only one app can have this permission simultaneously. 

![image](https://user-images.githubusercontent.com/1938136/85014066-e335f980-b165-11ea-88c9-8f1b5d6d6618.png)

## Expected behaviour

I expected that the corona-warn app would show me that exposure logging is disabled for the app. 

![image](https://user-images.githubusercontent.com/1938136/85014170-0f517a80-b166-11ea-93d7-46b3e38d431e.png)

After some time an technical error appeared, with no useful information for the user 

![image](https://user-images.githubusercontent.com/1938136/85014226-298b5880-b166-11ea-8f81-307b6cd04c43.png)

## Steps to reproduce the issue

- Install corona-warn
- Enable exposure logging
- Install immuni (Italian Covid exposure tracing app) 
- Switch exposure logging permission

## Technical details

iOS 13.5.1

---
Internal Tracking Id: EXPOSUREAPP-1878

**Comment by haosap** [comment] 2020-06-18 11:22
Hi @steins-code ,
We may need more state handling.

**Comment by dsarkar** [comment] 2020-12-09 12:11
Hi @danielburkard, 

Thanks again for your report. This issue should be fixed. Can you reproduce the error with CWA 1.7.1? If not, we would suggest closing this issue.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-12-26 10:12
Since we got no more reports about this issue, we consider it fixed.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2020-12-26 10:12 UTC
Labels: UX, further input needed, mirrored-to-jira
