### ISSUE TITLE
[Minor][UI] Contact Journal Headline overlapping

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-app-ios#3472] opened 2021-09-02 19:58 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [maybe that's related to the headline bugs] Bug is not already reported in another issue

## Technical details

- Device name: iPhone SE 1
- iOS version: iOS 14.7.1
- App version: 2.8.1 (0)

## Describe the bug

![image](https://user-images.githubusercontent.com/73582096/131907740-bb136f5f-290b-4e7f-be20-510b89f6f648.jpeg)

## Steps to reproduce the issue

Dunno, just randomly appeared.

## Expected behaviour

Let em not overlap.

## Possible Fix

Maybe this gets fixed with the headline bugs PR? (But I never read the code of the PR)

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-9482](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9482)

**Comment by ndegendogo** [comment] 2021-09-05 11:27
@jucktnich really iOS **17.7.1**? 🤪
*maybe some relativistic effect like a length contraction?*   

**SCNR**

**Comment by jucktnich** [comment] 2021-09-05 16:34
I've got the iOS 17 beta. I think i need to delete this all, to avoid the iPhone 4 debacle 😉😂

**Comment by ndegendogo** [comment] 2021-09-05 18:01
😅😅😅

**Comment by ndegendogo** [comment] 2021-09-06 16:44
@jucktnich is that reproducible / always, or was it a "one-time glitch"?

**Comment by jucktnich** [comment] 2021-09-06 17:01
It appeared to me twice

**Comment by ndegendogo** [comment] 2021-09-09 10:57
I can reproduce it on the simulator as of v2.8.1 as follows:

- start cwa
- select "contact diary" tab, see large title
- scroll down slowly. Watch the large title disappear.
- continue to scroll till the first line of text is hidden under the navigation bar.
- click on the "certificates" tab
- click on the "contact diary" tab and see the corrupted layout.

cwa 2.8.1(0) / iOS 14.4 (simulator) / iPhone SE 2nd gen (simulator)

**Comment by ndegendogo** [comment] 2021-09-09 16:33
I can reproduce it on my true device with the same sequence.
cwa 2.8.1(0) / iOS 14.4.1 / iPhone 8

**Comment by jucktnich** [comment] 2021-09-09 16:37
You can click on every tab not only the certificates tab

**Comment by ndegendogo** [comment] 2021-09-09 16:46
I can NOT reproduce with 
cwa 2.8.1(0) / iOS 12.5.3 / iPhone 6

**Comment by ndegendogo** [comment] 2021-09-10 20:52
Some intermediate results from my investigations so far:
1) [this line of code](https://github.com/corona-warn-app/cwa-app-ios/blob/0976c16c616b448e1123a9c3df4c0cf85143a705/src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Overview/DiaryOverviewTableViewController.swift#L59) triggers a recalculation of the layout for the navigation bar. If I just comment that line the issue is gone.

2) Unfortunately, the solution is not that easy. The line is actually needed to trigger a large title in the following scenario:
* Home tab / Settings / Reset App
* perform the onboarding sequence
* select the contact diary and see the contact diary info screen with large title
* scroll down till the large title shrinks, then press "continue".

Expectation: see the contact diary overview with large title
Observation: see the contact diary overview with normal title

*... investigations ongoing ...*

**Comment by ndegendogo** [comment] 2021-09-11 23:34
PR #3511 😎

@dsarkar @heinezen could you please apply labels? - Thanks!

**Comment by dsarkar** [comment] 2021-09-16 14:53
Internal Tracking ID: [EXPOSUREAPP-9482](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9482)

**Comment by Ein-Tim** [comment] 2021-10-06 09:22
@jucktnich Can you confirm that this has been fixed in version 2.11?

**Comment by jucktnich** [comment] 2021-10-06 11:55
With the way @ndegendogo described it's fixed, if it was the only way idk.
Closing as fixed.

**Closed** 2021-10-06 11:55 UTC
Labels: bug, mirrored-to-jira, Fix 2.11
