### ISSUE TITLE
Big iOS 14 issue

### ISSUE THREAD

**Issue by eikebartels** [corona-warn-app/cwa-app-ios#783] opened 2020-06-25 22:16 UTC
The app is not working at all on iOS 14. I only see a empty screen.

## Technical details

- iOS Version: 14
- Device: 11 pro

**Comment by n-thumann** [comment] 2020-06-25 22:31
Duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/749, see https://www.coronawarn.app/en/faq/#ios_14_beta ✌️

**Closed** 2020-06-26 06:09 UTC
