### ISSUE TITLE
iOS "Begegnungsüberprüfung" "Ausgetauschte Schlüssel" https://www.coronawarn.app/de/faq/#keys_matches

### ISSUE THREAD

**Issue by Bernhard387** [corona-warn-app/cwa-app-ios#1333] opened 2020-10-12 10:42 UTC
Hey,
I am not a developper but I was told at the hotline that this is an issue that might by of interest to you. It concerns the entry "Ausgetauschte Schlüssel" which in my case is "0" for all entries and the app reporting 2 "Risikobegegnungen" of high risk.
![20201011_173944000_iOS](https://user-images.githubusercontent.com/72725480/95737186-94b5e900-0c87-11eb-9742-78fe74a03d91.png)
![20201012_100243000_iOS](https://user-images.githubusercontent.com/72725480/95737193-967fac80-0c87-11eb-851c-96e26e8219ee.png)
![20201012_100257000_iOS](https://user-images.githubusercontent.com/72725480/95737198-98e20680-0c87-11eb-97fa-d7c49a543632.png)

It is an iphone SE 1st generation and iOS 14.0.1. I checked all entries and it says "0" for all entries. To my understanding the app would have no reason to report positive contacts as this is not what is found in "Begegnungsüberprüfungen".
If there is an interest I can provide the respective "ExposureChecks-2020-10-11.json" file, which I have exported from the "app".
Regards
Bernhard

**Comment by Bernhard387** [comment] 2020-10-12 10:45
Sorry, ich meine natürlich "Abgeglichene Schlüssel"

**Comment by Ein-Tim** [comment] 2020-10-12 11:53
I think @diampis comment [here](https://github.com/corona-warn-app/cwa-app-ios/issues/921#issuecomment-707070861) answered your question, or? @Bernhard387

**Comment by daimpi** [comment] 2020-10-12 12:01
Thanks @Ein-Tim 🙂 

I think this issue can be closed as a duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/1106 and the discussion can be continued over there 🙂.

**Comment by Bernhard387** [comment] 2020-10-12 14:09
Thank you all
sorry for the double post.
Regards
Bernhard

**Closed** 2020-10-12 14:09 UTC
Labels: question
