### ISSUE TITLE
Error 13 reappears >24hrs

### ISSUE THREAD

**Issue by Nutzerin** [corona-warn-app/cwa-app-ios#4163] opened 2022-02-02 10:06 UTC
![180C9179-3EFC-4DC6-88F6-74FA97E1F738](https://user-images.githubusercontent.com/98880332/152133345-e2541bc1-b13b-4079-aeaf-0ad194f8e47a.png)

## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name:
- iOS version:
- App version:

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-5836](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5836)
Internal Tracking ID: [EXPOSUREAPP-11706](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11706)

**Comment by Nutzerin** [comment] 2022-02-02 10:09
Error 13 states I had Refreshed Risikoermittlung More than 6 times that day, which is not true

**Comment by Ein-Tim** [comment] 2022-02-02 10:18
Hey @Nutzerin 👋

Could you please send us a screenshot of the following screen? 

`iOS-Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen`

This would help us to investigate the issue. Thanks.

**Comment by Nutzerin** [comment] 2022-02-02 10:54
Hi Tim

Please See attached. 

The Screen has always been green with Message ‚keine Risikobegegnungen‘ since November 2021. 

I See now that there have been 2 records of Begegnungsmitteilungen in the last days at least. However, they were Not indicated in the WarnApp Screen. 

Kind regards
Claudia 



Von meinem iPhone gesendet

**Comment by Ein-Tim** [comment] 2022-02-02 11:01
@Nutzerin 

You have to go to GitHub.com or use the GitHub mobile application to upload pictures. Attachments are not shown here.

**Comment by Nutzerin** [comment] 2022-02-02 11:11
Dome

**Comment by Ein-Tim** [comment] 2022-02-02 16:44
The check at 08:52 seems to have failed. This is most likely the reason why the error pop up appears. Is this the first time you see this pop up?

> I See now that there have been 2 records of Begegnungsmitteilungen in the last days at least. However, they were Not indicated in the WarnApp Screen.

This only means that there were some encounters which were filtered out by the CWA because they were too short/too far away.

**Comment by Nutzerin** [comment] 2022-02-02 17:00
Yes. I had encountered this yesterday or the day before (Not sure), too. 
Sure is that the error Message in the - then white instead of green- tile indicated exactly the Same time: aktualisiert heute 02:02.

![image](https://user-images.githubusercontent.com/98880332/152200988-ef0fdba8-4bdb-4157-9665-250495da45dc.png)

**Comment by dsarkar** [comment] 2022-02-02 17:14
Internal Tracking ID: [EXPOSUREAPP-5836](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5836)

**Comment by Ein-Tim** [comment] 2022-02-03 05:44
I'm also encountering error 13 now, due to a failed check yesterday:

<img src="https://user-images.githubusercontent.com/67682506/152287946-441d3bcb-a3bb-42ca-8af6-d86a16dfd59b.png" width="300">

<img src="https://user-images.githubusercontent.com/67682506/152287956-3c24a517-50f9-4686-9641-52501dce6dbf.png" width="300">

**Comment by ThatIsEpic** [comment] 2022-02-05 11:05
Still facing this bug.
![F0B85089-16F7-4E29-925B-D497D22D3D3A](https://user-images.githubusercontent.com/99075626/152639472-cb8ad9c6-5644-461b-9827-b6e565a5dc29.png)

**Comment by Ein-Tim** [comment] 2022-02-05 11:44
@ThatIsEpic 

Could you please send us a screenshot of the following screen?

iOS-Einstellungen ➡️ Begegnungsmitteilungen ➡️ Status von Begegnungsaufzeichnungen ➡️ Begegnungsüberprüfungen

**Comment by ThatIsEpic** [comment] 2022-02-05 12:03
Since I deleted the exposure checks as a first attempt to fix this issue there’s nothing to show right know, sorry.
![43928FF6-A81A-4A78-9669-6466865A2B69](https://user-images.githubusercontent.com/99075626/152641287-7ba9493c-125e-411f-a5fc-5dfc02d76e0d.png)
![B7FC3D39-5568-486B-B175-56AC1DA2F0AF](https://user-images.githubusercontent.com/99075626/152641289-f47170d1-ea0b-43b4-9366-cf92b3551e7b.png)

**Comment by Ein-Tim** [comment] 2022-02-05 12:14
@ThatIsEpic 

You pressed on "Begegnungsaufzeichnungen löschen"?

**Comment by ThatIsEpic** [comment] 2022-02-05 12:25
I did. The bug appeared beforehand and couldn’t be fixed by removing the data.
Perhaps it is a coincidence but this bug occurred after adding the PCR test?!

**Comment by Ein-Tim** [comment] 2022-02-05 13:12
@ThatIsEpic 

By pressing the button you have deleted all contacts which were recorded in the last 14 days.

The error will be gone in at max. 24h.

**Comment by ThatIsEpic** [comment] 2022-02-05 13:41
Maybe this error message should be shown instead of „please try again in 24h“. :)

let’s just hope for a bug fix :)

**Comment by Nutzerin** [comment] 2022-02-06 09:53
Again a failed Risikoermittlung. This time another Message: s Screenshot. 
3 Hours before the tile was green, time 7:3x it said. 
Now white tile with a time of check 6:06. what is this???

I also add a Screen of Begegnungsüberprüfungen. 

![image](https://user-images.githubusercontent.com/98880332/152675550-fdf18f2e-7bca-48f6-aee8-d52304f05f4b.png)

![image](https://user-images.githubusercontent.com/98880332/152675608-9cd9c669-b13e-4fd0-bafb-7231a394aae6.png)

**Comment by Ein-Tim** [comment] 2022-02-06 09:55
@Nutzerin What happens when you click on "Erneut starten"?

**Comment by Nutzerin** [comment] 2022-02-06 09:56
But: After manual reStart of Risikoermittlung it is green again 

![image](https://user-images.githubusercontent.com/98880332/152675708-f6f52677-3067-4ffa-a995-6ddf493ff38a.png)

**Comment by Ein-Tim** [comment] 2022-02-06 09:58
@Nutzerin 

Interesting.

Could you please let us know:
- Which iOS Version you are using?
- Which iPhone you are using?
- Which version of the CWA you are using?

**Comment by Nutzerin** [comment] 2022-02-06 10:02
iOS 15.1
iPhone 8
CWA 2.17.1

**Comment by Ein-Tim** [comment] 2022-02-06 10:03
Ok thanks, please let us know when this happens again!

**Comment by ErinBeyer** [comment] 2022-02-06 14:27
![D2F27EBD-2C8D-401F-BFD2-DCEBA6826A64](https://user-images.githubusercontent.com/67906294/152685517-1953367b-3e4a-48d5-af30-76b2e9deb61a.png)
![0E47016B-697E-449D-AC94-B56D1018EC83](https://user-images.githubusercontent.com/67906294/152685522-e859267a-96cd-4a28-93ef-80e704e95b1d.png)

i‘ve also been getting this message unexpectedly. You can see it last updated around 1am. I also got no warning at all when my husband had covid and uploaded to the app and he often gets warnings when we have been out together and I get nothing.

**Comment by Ein-Tim** [comment] 2022-02-06 14:32
Hi @ErinBeyer 

Could you please send us a screenshot of the following screen?

iOS-Einstellungen ➡️ Begegnungsmitteilungen ➡️ Status von Begegnungsaufzeichnungen ➡️ Begegnungsüberprüfungen

**Comment by ErinBeyer** [comment] 2022-02-06 14:39
![Uploading A48C7CF0-228E-46F4-879A-7FDBCA422859.png…]()

**Comment by ErinBeyer** [comment] 2022-02-06 14:40
![E7121DEA-AD9D-493B-A155-70293B02D04E](https://user-images.githubusercontent.com/67906294/152686050-dd2b4c45-78d9-4aff-bb7a-71f5f27e6b69.png)

**Comment by Ein-Tim** [comment] 2022-02-06 14:52
@ErinBeyer 

Okay also for you, the error should disappear in 24h.

**Comment by Mattin59379** [comment] 2022-02-07 07:44
Hello, I‘ve got the same problem using my iPhone 8, iOS 15.3, CWA 2.16.2 (0)
Screenshots attached.
It seems, that the last error-free check was proceeded on January 31.

![57FFAB0F-7E7E-4F39-BBF6-E15FC31ED068](https://user-images.githubusercontent.com/99168258/152745509-9a76a8c9-b6f6-45f6-bd23-6aa253ceeb30.png)
![C85C5794-DA0F-4528-A5DE-7F17777FDDA1](https://user-images.githubusercontent.com/99168258/152745517-262b5c9a-2bc6-493c-a82a-69d81c4be90e.png)
![D1608AE1-DD58-43AB-AA78-DEFC3A01453C](https://user-images.githubusercontent.com/99168258/152745518-f64b106c-9c83-47c0-8771-f771f61c8573.png)

**Comment by Ein-Tim** [comment] 2022-02-07 07:59
@Mattin59379 

Can you deactivate exposure logging for 24h and then try again.

@thomasaugsten Is the team investigating these issues?

**Comment by dsarkar** [comment] 2022-02-07 09:56
@Mattin59379  Thanks for the report. Forwarded to internal ticket.

**Comment by Mattin59379** [comment] 2022-02-07 13:10
Ok, I‘ll try that. But while opening the CWA another error message is displayed now:
![2CB28CDF-A413-44F0-BD62-BB472FBADEAF](https://user-images.githubusercontent.com/99168258/152794236-2827c55a-1457-4bf9-8de6-6f907f460634.png)

**Comment by Ein-Tim** [comment] 2022-02-07 13:11
@thomasaugsten Please take a look.

**Comment by Ein-Tim** [comment] 2022-02-07 18:13
@dsarkar 

The problem is that the app retries when an exposure check fails and these retries count into the rate limit. I'm also seeing error 13 at the moment:

Yesterday: 10:16h - successful check
Yesterday: 15:43h - successful check
Yesterday: 19:56h - check failed
Yesterday: 20:09h - check failed
Yesterday 21:25h - check failed
Yesterday 22:49h - successful check
Today 06:34h - successful check
Today 13:44h - successful check

Now: 19:11h - no more checks due to error 13.

@thomasaugsten You said Apple is not counting failed checks but obviously they are. Maybe you could ask Apple to change this?

Exposure log:
[ExposureChecks-2022-02-07.txt](https://github.com/corona-warn-app/cwa-app-ios/files/8017691/ExposureChecks-2022-02-07.txt)


cc @ndegendogo

**Comment by thomasaugsten** [comment] 2022-02-07 19:09
I don't think we can expect a change from Apple side. But with the next release we will hide the error 13 and show only a white card after 48h no successful check

**Comment by Ein-Tim** [comment] 2022-02-07 19:11
@thomasaugsten Ok so you are implementing https://github.com/corona-warn-app/cwa-wishlist/issues/388.

I guess Error 13 will still be logged, right?

**Comment by Ein-Tim** [comment] 2022-02-07 19:13
> I don't think we can expect a change from Apple side. But with the next release we will hide the error 13 and show only a white card after 48h no successful check

If the user clicks on the "Erneut versuchen" button and the app can't carry out a risk check because of error 13, what will happen? Will you show the error then? Or will nothing happen?

**Comment by thomasaugsten** [comment] 2022-02-07 19:18
Stilled logged but not shown to the user if this occurring  after 48h without successful check the issue is not error 13 it is a different problem

**Comment by Ein-Tim** [comment] 2022-02-07 19:20
@thomasaugsten Yeah, right.

**Comment by Nutzerin** [comment] 2022-02-10 06:21
Again ...🙄
Whole App is frozen!!
No kpi's, no diary - unaccessable. 

iPhone 8
iOS 15.3


![image](https://user-images.githubusercontent.com/98880332/153349079-684ef4dc-5f80-42cf-8f7c-2fdd59836f25.png)

![image](https://user-images.githubusercontent.com/98880332/153349257-cd40fa0c-ff9e-48c0-982d-ae55eb1ff9ab.png)

**Comment by Ein-Tim** [comment] 2022-02-10 06:25
@Nutzerin 

I wonder what actually causes the error. 

@thomasaugsten Would you take a look at an error log?

**Comment by sapjolkin** [comment] 2022-02-10 07:39
Same issue here. Only 2 Begegnungsüberprüfungen today (which I think is less than 6 🙄).

![image](https://user-images.githubusercontent.com/99389101/153359778-554bdf0c-c5f0-48bb-b9eb-ae166b83fdd6.png)

**Comment by Ein-Tim** [comment] 2022-02-10 07:48
@sapjolkin 

There were more than 6 checks in the last 24h. The last 24h are relevant, not only today.

**Comment by ndegendogo** [comment] 2022-02-10 07:59
@Nutzerin actually, your screenshots are quite interesting.

1) cwa shows a timestamp of 22:19 for the **last successfully finished** risk check; whereas the ENF log shows 21:30 as the **starting time** of the last check.
It looks as if the whole procedure lasted 49 minutes!?

*It would be very interesting to see the detailed timestamps for all the files. Would you mind to export your ENF log? It contains no private data, only the timestamps of the checks.* 
@Ein-Tim can give more instructions on this export if needed.

**Comment by Nutzerin** [comment] 2022-02-10 08:04
@Ein-Tim How would i Upload the Jason file here?

**Comment by ndegendogo** [comment] 2022-02-10 08:04
@Nutzerin do you remember any details on your usage of cwa yesterday at 21:30 when this successfull check started? Was the device powered? Did you have WLAN or only mobile data? Was any power-saving mode active? Did you open cwa actively, or was this check started from background?

**Comment by ndegendogo** [comment] 2022-02-10 08:06
@Nutzerin do you remember any details on your usage of cwa yesterday at 21:30 when this successfull check started? Was the device powered? Did you have WLAN or only mobile data? Was any power-saving mode active? Did you open cwa actively, or was this check started from background?

**Comment by ndegendogo** [comment] 2022-02-10 08:09
> How would i Upload the Jason file here?

@Nutzerin

github doesn't like json file extension for upload.
Just rename the file to *.txt then it should work

**Comment by Ein-Tim** [comment] 2022-02-10 08:09
@Nutzerin 
<details>
<summary>How to export Exposure Notificaiton Logs under iOS 13.7 or newer</summary>


**German:**

`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ `Überprüfungen exportieren`

**English:**

`Settings` ➡️ `Exposure Notifications` ➡️ `Exosure Logging Status` ➡️ `Exposure Checks` ➡️ `Export Exposure Checks`

**To upload the file here, rename it from .json to .txt**
</details>

**Comment by ndegendogo** [comment] 2022-02-10 08:20
@Nutzerin 

2) your ENF log shows that there were indeed many checks started yesterday (even more than 6 which is the limit). So, technically, the error 13 is expected behaviour (rate limit exceeded). However, we need to understand the root cause.
The short sequence in which new checks were started suggests that the previous check was not finished successfull. **Error or timeout?**

Are you aware of any special condition yesterday that could have caused an error? Did you have stable internet all the day? How was battery? How is the memory condition of your device - is it very full? Again: do you remember if you opened cwa often or if these checks wee from background?
Did you register for test results, certificates, events?

**Comment by Nutzerin** [comment] 2022-02-10 08:41
> @Nutzerin 
> 
> 
> 
> 2) your ENF log shows that there were indeed many checks started yesterday (even more than 6 which is the limit). So, technically, the error 13 is expected behaviour (rate limit exceeded). However, we need to understand the root cause.
> 
> The short sequence in which new checks were started suggests that the previous check was not finished successfull. **Error or timeout?**
> 
> 
> 
> Are you aware of any special condition yesterday that could have caused an error? Did you have stable internet all the day? How was battery? How is the memory condition of your device - is it very full? Again: do you remember if you opened cwa often or if these checks were from background?
> 
> Did you register for test results, certificates, events?
> 
> 

@ndegendogo 
No issues of those mentioned. 
And I Really Start worrying about the CWA Software quality, if any of the conditions you mentioned Could really have an impact on the reliability of the App.

**Comment by Ein-Tim** [comment] 2022-02-10 08:41
> > @Nutzerin 
> > <details>
> > 
> > <summary>How to export Exposure Notificaiton Logs under iOS 13.7 or newer</summary>
> > 
> > 
> > 
> > 
> > 
> > **German:**
> > 
> > 
> > 
> > `Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ `Überprüfungen exportieren`
> > 
> > 
> > 
> > **English:**
> > 
> > 
> > 
> > `Settings` ➡️ `Exposure Notifications` ➡️ `Exosure Logging Status` ➡️ `Exposure Checks` ➡️ `Export Exposure Checks`
> > 
> > 
> > 
> > **To upload the file here, rename it from .json to .txt**
> > 
> > </details>
> 
> @Ein-Tim No, i can't Change the Extension to .txt. Then the filename is xxx.txt.json 
> 
> And: i Can only upload photos here. 
> 

You should be able to delete the .json extension and add the .txt instead. Uploading other files is possible via the GitHub website.

**Comment by Nutzerin** [comment] 2022-02-10 08:45
@tim 

No, I can’t change the extension on the iPhone!!

If you want me to transfer it to the website, then please provide a description of how to do it!

**Comment by ndegendogo** [comment] 2022-02-10 08:48
> And I Really Start worrying about the CWA Software quality, if any of the conditions you mentioned Could really have an impact on the reliability of the App.

@Nutzerin please don't misunderstand my statements. I am not a developer here (although I have provided them with a few minor bugfixes). I am only a long-term user. **I have seen quality and reliability of cwa improving a lot over the time since I am using it.**
And my questions are only "the usual suspects" that can cause unstable behaviour on software (and, yes, I have seen several of these in the early days of cwa).

**Comment by ndegendogo** [comment] 2022-02-10 08:50
@thomasaugsten I have seen a few times the following pattern on my iPhone 6 / iOS 12.5.
I open cwa, and the download starts, then the check starts. But the check takes a long time these days with the high numbers, and it is an old and slow model, and it has a very short timeout for the screensaver.
So often the screensaver timeout interrupts it before the check is finished.
When I notice that, I open it again, and the check continues.
Later in the ENF I can see this interruption as a gap in the timestamp.

Is this an issue? Would it continue the check if I had not unlocked the screen?

**Comment by ndegendogo** [comment] 2022-02-10 09:02
I just checked my ENF logs, and I see a similar pattern with a large gap in time on 29 Jan at 23:22. At this time we have the full load (22 hourly files plus 14 daily).
Not sure if this check was from background or from foreground.

My timestamps start at 23:22, then continue 23:23 / 23:24 / 23:25 / 23:26. And then there is a large gap... the very last file follows at 00:09.

**Comment by thomasaugsten** [comment] 2022-02-10 09:04
iOS normally doesn't kill the app when you put in background or lock your screen. You receive between 3-10min before iOS will put the app in standby.

**Comment by ndegendogo** [comment] 2022-02-10 09:06
@thomasaugsten also I have sometimes seen the following pattern in the ENF log: a single entry with a starting timestamp but no files in the list.

I think this happened when I opened cwa shortly but immediately closed it while the check was still ongoing.

@thomasaugsten do you know if such interrupted checks count against the rate limit?

**Comment by ndegendogo** [comment] 2022-02-10 09:11
> No, I can’t change the extension on the iPhone

@Nutzerin do you have a computer? I am not sure if it is possible to change the file extension on the phone

**Comment by Nutzerin** [comment] 2022-02-10 09:30
> > And I Really Start worrying about the CWA Software quality, if any of the conditions you mentioned Could really have an impact on the reliability of the App.
> 
> 
> 
> @Nutzerin please don't misunderstand my statements. I am not a developer here (although I have provided them with a few minor bugfixes). I am only a long-term user. **I have seen quality and reliability of cwa improving a lot over the time since I am using it.**
> 
> And my questions are only "the usual suspects" that can cause unstable behaviour on software (and, yes, I have seen several of these in the early days of cwa).

@ndegendogo 
Then we have Long-Term using in common, and the Willingness to help improve the CWA quality. 
But, at the end of the day I am a user, Working Full-time, and Spending hours here to provide developers with Information to fix bugs of Software already deployed.

**Comment by Nutzerin** [comment] 2022-02-10 09:57
> @Nutzerin 
> 
> > No, I can’t change the extension on the iPhone!! If you want me to transfer it to the website, then please provide a description of how to do it!
> 
> Sorry for not being helpful. You should be able to go to GitHub.com, log into your account, click on "Notifications", select this thread, click into the comment field and then select to upload files. Your iPhone will offer you to choose between your "Dateien" and "Fotos" app, please select "Dateien" and then choose the file.
> 
> However, you are right, changing the extension is not possible on the iPhone, sorry for not understanding your problem.
> 
> Let's see whether the file is still needed. 

- @Ein-Tim 
S. Screenshot
These are the icons i see on the iPhone GitHub App. Which is the icon of Dateien-App?

![image](https://user-images.githubusercontent.com/98880332/153383070-f6a0bf7c-23cb-4077-a3b0-325a241f0c8f.png)

**Comment by thomasaugsten** [comment] 2022-02-10 10:00
@Nutzerin the reason for your error 13 is that iOS will kill the background check because of high load and/or low battery of your device. Unfortunately Apple is counting this interrupted risk check in the daily quota. We will fix this issue in 2.18 by hiding the error 13 and showing the last successful risk check
It is up to you to provide more information to the community but from developer side this is at the moment not necessary.

**Comment by Ein-Tim** [comment] 2022-02-10 17:17
Fix for this: https://github.com/corona-warn-app/cwa-app-ios/pull/4203

**Comment by Nutzerin** [comment] 2022-02-10 17:22
> @Nutzerin the reason for your error 13 is that iOS will kill the background check because of high load and/or low battery of your device. Unfortunately Apple is counting this interrupted risk check in the daily quota. We will fix this issue in 2.18 by hiding the error 13 and showing the last successful risk check
> 
> It is up to you to provide more information to the community but from developer side this is at the moment not requested and necessary.
> 
> 

@thomasaugsten Thanks, but, please, you can Rest assured that none of the causes mentioned apply in this case.

**Comment by Nutzerin** [comment] 2022-02-10 17:26
> > @Nutzerin the reason for your error 13 is that iOS will kill the background check because of high load and/or low battery of your device. Unfortunately Apple is counting this interrupted risk check in the daily quota. We will fix this issue in 2.18 by hiding the error 13 and showing the last successful risk check
> > 
> > It is up to you to provide more information to the community but from developer side this is at the moment not requested and necessary.
> > 
> > 
> 
> @thomasaugsten Thanks, but, please, you can Rest assured that none of the causes mentioned apply in this case. 

In the meantime i can use the App again. However, 2.18 hasn't been released yet ....

**Comment by ndegendogo** [comment] 2022-02-10 20:09
@thomasaugsten the PR#4203 mentions error 16 besides error 13.

Do you have any insights (or even suspicions) what can cause error 16 to happen?

**Comment by thomasaugsten** [comment] 2022-02-10 20:37
The official documentation states the device is not unlocked.
https://developer.apple.com/documentation/exposurenotification/enerror/code/datainaccessible
The recommendation is to ignore the error because it is not clear what causes the error on an unlocked device

**Comment by thomasaugsten** [comment] 2022-02-11 08:43
Error 13 doesn't count in the rate limit it is only the rate limit warning.
There is no retry strategy planned because we have no reliable feedback when a risk check failed.

**Comment by Nutzerin** [comment] 2022-02-16 18:23
Again ...![image](https://user-images.githubusercontent.com/98880332/154330972-1f348601-ba55-4760-8d5f-119246f910a0.png)

**Comment by dsarkar** [comment] 2022-02-17 10:40
@Nutzerin Thanks for reporting. We will forward this.

**Comment by dsarkar** [comment] 2022-02-17 10:42
@Nutzerin There is a fix planned for release 2.18

**Comment by depechka** [comment] 2022-02-17 15:15
I’m also facing this error 13 for the second day in a row now. Nevertheless my phone last night warned me about a risky contact last week. I’m using a vintage iPhone 7.

**Comment by xenia71120** [comment] 2022-02-19 08:21
![D5A0810E-C365-4645-9F25-3AA89CD10769](https://user-images.githubusercontent.com/100017749/154793030-13b761e3-c599-43f0-95f1-154e82b0124c.png)

**Comment by Ein-Tim** [comment] 2022-02-19 09:38
@xenia71120 

24 Stunden warten, so wie es im Pop-Up steht. Oder hilft das nichts?

**Comment by xenia71120** [comment] 2022-02-19 09:39
Naja ist jetzt noch nicht ganz 24h aber nervt auch weil ich auf ein PCR
Test Ergebnis warte hoffe das es dadurch nicht gestört wird

Tim ***@***.***> schrieb am Sa. 19. Feb. 2022 um 10:38:

**Comment by Ein-Tim** [comment] 2022-02-19 09:45
@xenia71120 

Etwas anderes kannst du nicht tun, außer die Risiko-Ermittlung für die nächsten Stunden auszuschalten, dann werden aber natürlich auch keine Kontakte mehr aufgezeichnet.

Der Test kommt trotzdem in der App an.

**Comment by Nutzerin** [comment] 2022-02-19 09:45
@Ein-Tim 
Ich nochmal...
Das Problem besteht seit Wochen!
Hier nochmal: DIE APP IST DANN EINGEFROREN. Man kann nichts machen: kein Zertifikat vorzeigen, sich einchecken, die eigene Risikoermittlung überprüfen, das Tagebuch führen usw. 
Ist das tatsächlich Euer ernst, die Kunden jedesmal 24 std warten zu lassen? Und auf irgendein Release in ferner Zukunft zu verweisen?
Ich hoffe nicht und Ihr erarbeitet jetzt endlich mal eine Lösung.

**Comment by Ein-Tim** [comment] 2022-02-19 10:04
@Nutzerin 

Ich verstehe deine Frustration gut, aber auch das Entwicklungs-Team kann nicht zaubern. Version 2.18 ist die nächste Version, ich vermute, sie wird nächste Woche veröffentlicht. 

Was mir gerade als Workaround einfällt: Schalte die Hintergrundaktualisierung der CWA aus (Systemeinstellungen -> Corona-Warn -> Hintergrundaktualisierung-> AUS). Dann musst du zwar deinen Risiko-Status manuell in der App aktualisieren, dafür versucht die App aber auch im Hintergrund nicht immer und immer wieder Überprüfungen durchzuführen, wenn die fehlschlagen.

Wäre das ein Workaround für jetzt?

**Comment by Nutzerin** [comment] 2022-02-19 10:15
@Ein-Tim 
Meine Frustration?
Nicht zaubern?
Wie wäre es mal mit Testing VORAB? Oder einer durchdachten Release Strategie? Bevor Ihr die Änderungen produktiv schaltet. Anstatt die zahlenden Anwender die Tests machen zu lassen. 

Ich experimentiere jetzt nicht herum mit workarounds, die Ihr wahrscheinlich genauso wenig durchdacht und getestet habt. Tut mir leid, keinerlei Vertrauen mehr in Eure Truppe.

**Comment by Ein-Tim** [comment] 2022-02-19 10:38
@Nutzerin

> Wie wäre es mal mit Testing VORAB? Oder einer durchdachten Release Strategie? Bevor Ihr die Änderungen produktiv schaltet. Anstatt die zahlenden Anwender die Tests machen zu lassen.

Das einzige was sich geändert hat, ist das mehr Nutzer:innen ihre Infektionen über die App melden und deshalb auch mehr Daten verarbeitet werden. Dadurch kann es auf einigen Geräten zu Abstürzen bei der Risiko-Überprüfung im Hintergrund kommen.
Das Entwicklungs-Team hat darauf reagiert und veröffentlicht eine Version, die das Problem für den Normalen-Anwender so gering wie möglich macht, in Kürze.

**Comment by Nutzerin** [comment] 2022-02-19 12:15
Eben: re-agiert.

**Comment by Ein-Tim** [comment] 2022-02-24 21:20
@Nutzerin 

Und, wie sieht es mit Version 2.18 bis jetzt aus?

**Comment by ndegendogo** [comment] 2022-02-27 08:22
I can confirm that the suppression of error 13 works in cwa version 2.18. 
I got no new risk check this morning. The last successful check was yesterday at 22:56.
I had a look at my error log and saw indeed error 13.
Now the interesting part will be to see if it indeed recovers while I continue to use cwa.

I will continue to watch it.

cwa 2.18.1 (0) / iOS 15.1 / iPhone 13 pro

**Comment by ndegendogo** [comment] 2022-02-27 09:07
More details from my error log (all times as UTC):
- Feb 26 21:56: my last successful risk check
- Feb 26 23:47: I opened cwa, but no risk check, because the last is still fresh (younger than 4 hours, not enough time has passed)
- Feb 27 01:56: risk check from background downloads new key packages but then fails immediately (same timestamp) with error 16
- Feb 27 05:43 next attempt from background, download successful, check fails again with error 16
- Feb 27 07:13 I open cwa, it downloads new key files, but check fails - this time with error 13 (suppressed)
- again failing checks at 07:14:11 / 07:14:42 / 07:14:44 / 07:16:06 / 07:16:42 / 07:16:43 / 07:17:10 / all with error 13 (suppressed). We see here very nicely the pattern that it stalls after the first error 13. However, with the new behaviour and the suppressed error message, I can use it without problems.

**Comment by ndegendogo** [comment] 2022-02-27 09:22
And: YES, it has recovered, and I got my risk check successful now.

Thanks a lot to the devs for this fix! 
🎉🎉🎉🎉🎉

![31583170-2929-4759-8172-715D2B4D40B4](https://user-images.githubusercontent.com/6118267/155876484-86aaf13f-9a1f-407a-a29e-9ddcbd72e2b2.png)

**Comment by dsarkar** [comment] 2022-02-28 12:37
@ndegendogo Thanks for the feedback. Forwarded to internal ticket/dev team.

**Comment by Ein-Tim** [comment] 2022-02-28 13:03
@Nutzerin Any feedback you could give us?

**Comment by Ein-Tim** [comment] 2022-03-18 09:21
@dsarkar I suggest to close this issue as this should be fixed in 2.18 but there was no feedback from the author of this issue.

**Closed** 2022-03-18 09:38 UTC
Labels: bug, ready to close, mirrored-to-jira, Fix 2.18
