### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tank6b** [corona-warn-app/cwa-app-ios#792] opened 2020-06-27 01:51 UTC
![image](https://user-images.githubusercontent.com/794409/85912011-67087980-b829-11ea-98ae-1c7429e9d699.jpeg)

**Comment by christianbrb** [comment] 2020-06-27 05:12
@tank6b There is already an issue for this error (see -> #759)

**Comment by tank6b** [comment] 2020-06-27 07:51
Not the same behavior and also not one of the solutions mentioned in #759 works.

Now the state of the app is totally messed up.

![image](https://user-images.githubusercontent.com/794409/85917579-8e783a00-b85b-11ea-85f4-d0d7f14dca4c.png)

But the logging is active

![image](https://user-images.githubusercontent.com/794409/85917582-9c2dbf80-b85b-11ea-8d48-ae62b7bf62cd.png)

Instead of giving a security feeling is doing the contrary. The app itself doesn’t know the status.

**Comment by haosap** [comment] 2020-06-29 06:58
Hi @tank6b ,
Thanks for the bug report. 
The 1st one is a known issue and have been working on it. It is likely a bug from OS level.
The 2nd one we'll fix it in the next release.

**Comment by tkowark** [comment] 2020-06-29 14:53
Duplicate of #759

**Closed by tkowark** 2020-06-29 14:53 UTC
