### ISSUE TITLE
ENDomain Error 3 iOS 14 Developer Beta

### ISSUE THREAD

**Issue by RomanSch** [corona-warn-app/cwa-app-ios#852] opened 2020-07-05 09:21 UTC
## Describe the Bug
ENDomainError 3 when first starting the App on iOS14 Dev Beta. The first config can not be finished. 

- Installing the App fresh from the App Store 
- Opening the App 
- Starting the Config
- When enabling the Risk checking the error is thrown
- continuing the config to notifications
- after allowing the notifications the app does not continue to normal behaviour

## Expected behaviour

No error thrown and normal behaviour to view the app in a normal way

## Steps to reproduce the issue

- Installing the App fresh from the App Store 
- Opening the App 
- Starting the Config
- When enabling the Risk checking the error is thrown
- continuing the config to notifications
- after allowing the notifications the app does not continue to normal behaviour

![CA667BE9-DC68-41B8-B71D-D5E09567AC9F](https://user-images.githubusercontent.com/26023737/86529516-7cc51100-beb1-11ea-8cc8-3f472b644533.png)

Screen Recording here:
https://share.icloud.com/photos/0ShDYMqQQ0HIJ2ctVtuTSABWw

## Technical details

- iOS Version: 14.0 Dev Beta
- Device: 11 Pro Max

**Comment by n-thumann** [comment] 2020-07-05 11:12
Duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/749. CWA is not working on iOS 14 Beta yet, see https://www.coronawarn.app/en/faq/#ios_14_beta ✌️

**Closed** 2020-07-05 11:34 UTC
Labels: bug, duplicate
