### ISSUE TITLE
App isn't working with iOS 14 Preview

### ISSUE THREAD

**Issue by heinemannmarkus** [corona-warn-app/cwa-app-ios#764] opened 2020-06-24 10:11 UTC
## Avoid duplicates

* [ x ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ x ] Bug is not already reported in another issue

## Describe the bug
The App isn't working with the beta release of iOS 14. When the App is opened there will be only a white blank screen without any information. 

![Screenshot 2020-06-24 at 12 06 44](https://user-images.githubusercontent.com/21105441/85537594-65199d00-b614-11ea-8afa-48aa19c9843b.png)

## Expected behavior

The app should open and show the usual dashboard.

## Steps to reproduce the issue

1. Install the iOS 14 Developer Preview 
2. Open the App

## Technical details

- iOS Version:  14.0 (18A5301v)
- Device: iPhone XR

## Additional context

I know that iOS 14 is still a developer preview and not released now but maybe it's useful to take a look at this bug to avoid issues when iOS 14 will be officially released.

**Comment by n-thumann** [comment] 2020-06-24 10:36
Duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/749 ✌️ 
ExposureNotification Framework isn´t available yet in iOS 14 Beta 😊

**Comment by inf2381** [comment] 2020-06-24 10:36
https://www.coronawarn.app/en/faq/#ios_14_beta. The checkbox in the issue template is there for a reason

**Closed by inf2381** 2020-06-24 10:36 UTC
Labels: bug
