### ISSUE TITLE
High battery draining even in flight mode (iOS 13.6)

### ISSUE THREAD

**Issue by Simpelton** [corona-warn-app/cwa-app-ios#937] opened 2020-07-23 06:28 UTC
Power consumption of CoronaWarnApp has drastically increased - I guess with install of iOS 13.6. Main topic has been that even in flight mode, my battery got drained from 50% down to 0% - phone shut down completely. I always have my phone in flight mode over night, that usually takes almost no battery.

Battery consumption:
- Health Exposure Logging 37% (has been around 15-20% in the past I believe)
- Mail (next in statistic) 16%

I did review #671 - my issue surfaced with iOS13.6 - #671 is about general consumption with iOS13.5.1
https://github.com/corona-warn-app/cwa-app-ios/issues/671

## Steps to reproduce the issue

Turn on flight mode and watch some thing suck your battery dry - but also happens during normal operation.

## Technical details

- iOS Version: 13.6
- Device: iPhone 7
- Managed corporate device 
- C Warn app 1.1.1 (3)

**Comment by Ein-Tim** [comment] 2020-07-23 06:48
Duplicate of #671

**Comment by Simpelton** [comment] 2020-07-23 06:52
I did review #671 - my issue surfaced with iOS13.6 - #671 is about general consumption with iOS13.5.1
So I expect this  is a different / new issue - thus opened this ticket.

**Comment by Ein-Tim** [comment] 2020-07-23 06:58
> I did review #671 - my issue surfaced with iOS13.6 - #671 is about general consumption with iOS13.5.1
> 
> So I expect this  is a different / new issue - thus opened this ticket.

Okay, good point, my fault.
We will see how the Admins handle this.

**Comment by Ein-Tim** [comment] 2020-07-23 07:02
> Battery consumption:
> 
> - Health Exposure Logging 37% (has been around 15-20% in the past I believe)


One more question:
How are you able to see the battery consumption for the Health Exposure Logging in iOS 13.6?

**Comment by Simpelton** [comment] 2020-07-23 07:15
I only got indicators 

- I did watch the battery consumption statistics right  after I installed the warn app. I do recall that it was acceptable.
- Recently (I guess with iOS 13.6) I observed that I need to charge my device a lot more - even being in home office
- Battery statistic showed an increase of consumption for the warn app / apple health so I started to observe more closely
- I also noticed that my battery was heavily drained over night - that was very unusual
-  Last night, I did check my battery - was at 50%. Turned on flight mode. Phone was dead in the morning - 7h time window in flight mode. 
- Corona / Apple Health shows 37% of battery consumption this morning => Settings => Battery => Battery usage per app

I did not install any other software nor did I change my device setup (knowingly). Not sure if any silent update to any other app have been rolled out. Let me know if a screen shot helps.

**Comment by Ein-Tim** [comment] 2020-07-23 07:22
Okay thank you. 
We will wait for the admins and see. 

> - Recently (I guess with iOS 13.6) I observed that I need to charge my device a lot more - even being in home office

This I also noticed with iOS 13.6, the other points I can't confirm.

**Comment by SebastianWolf-SAP** [comment] 2020-07-23 07:55
Thanks for reporting this issue. This is really unusual as we've received some reports that it got better with 13.6. However, we'd anyway ask you follow-up in #671. Only the last comment references a difference between 13.5 and 13.6 - the rest was more or less generic (as only 13.5 existed when they were written). Let's collect all reports concerning battery consumption there. 

One remark though before we close this one: We've also received reports that a restart of the device has mitigated battery consumption. Sounds a little strange to write it here, but have you tried turning it off and on again? ;)

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Closed by SebastianWolf-SAP** 2020-07-23 07:55 UTC
Labels: bug

**Comment by Simpelton** [comment] 2020-07-23 07:59
I will keep watching and then report into #671  As the device turned off this morning "automatically" I will know soon enough. Sad to see that this "reboot tut gut" thing keeps chasing us - lol
