### ISSUE TITLE
CWA performing checks (nearly) every time I open the app

### ISSUE THREAD

**Issue by Mihahn** [corona-warn-app/cwa-app-ios#1544] opened 2020-11-19 09:24 UTC
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

When I open cwa it downloads the new files and checks them. But: often this happens twice! When I leave the app then and reopen it after 10 minutes it's downloading the files again – you may see it in the log. This issue could be related to #916 or #1542 but in #1542 one of the files is empty; my logs always do contain "new" files (which are the same as ten minutes before obviously).

It's happening randomly. This morning I can't get cwa to update (intended behaviour as the last check was last night at 01:28 when I opened the app), yesterday it updated every time I opened it – only 01:28 contained the new DC6C131E[...] file.

![1](https://user-images.githubusercontent.com/3447340/99645483-92e20100-2a4f-11eb-93c9-d5c6d7b65510.PNG)
![2](https://user-images.githubusercontent.com/3447340/99645490-94abc480-2a4f-11eb-9bd4-23afb63ecc57.PNG)

## Technical details

- iOS Version: iOS 14.2
- Device: iPhone 7

**Comment by dsarkar** [comment] 2020-11-19 10:16
Dear @Mihahn,

Thank you for your contribution. Your post seems a duplicate of actually two issues.

Please, continue any further contribution regarding duplicate checks here #1505.
Also, have alook here https://github.com/corona-warn-app/cwa-app-ios/issues/1514#issuecomment-727602796, please.

Can you confirm you are using CWA version 1.6.1 ?

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by Mihahn** [comment] 2020-11-19 10:22
Thank you for your reply and I'm sorry I missed those issues.

I didn't know I had connection issues (which might be the root of the problem) – but this seems to be the cause. And yes, I am on 1.6.1. Thanks again!

**Comment by dsarkar** [comment] 2020-11-19 10:29
Thanks again for reporting. I will close this issue now, you will find further updates regarding these issues in the aforementioned issues. 

Best regards,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-11-19 10:29
Duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/1505

**Closed by dsarkar** 2020-11-19 10:29 UTC
Labels: bug, duplicate, further input needed
