### ISSUE TITLE
Error: ExposureDetwctionIsAlreadyRunning

### ISSUE THREAD

**Issue by greedystack** [corona-warn-app/cwa-app-ios#1512] opened 2020-11-14 12:57 UTC
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug
![image](https://user-images.githubusercontent.com/25386620/99147447-44b0b480-2681-11eb-8c8a-ee8093a8ba88.png)

## Expected behaviour
Not getting a bug message when starting the app.

## Steps to reproduce the issue
Start app to manually load positive beacons from server. (Automatic loading isn't working since a few weeks. Thanks Telekom & SAP for this crappy app!)

## Technical details

- iOS Version: 14.2
- Device: iPhone X

**Comment by Ein-Tim** [comment] 2020-11-14 13:13
This is a duplicate of #1497 (exactly from [this comment](https://github.com/corona-warn-app/cwa-app-ios/issues/1497#issuecomment-725960568))
The Issue will be solved with the 1.7.0 release (PR: #1510)
Please concider closing this Issue, thanks!

But I have another question: 
What do you mean with:
>Automatic loading isn't working since a few weeks

**Comment by thomasaugsten** [comment] 2020-11-14 13:22
You can ignore this information that an exposure check is already running
EXPOSUREAPP-3769

**Closed by thomasaugsten** 2020-11-14 13:22 UTC
Labels: mirrored-to-jira
