### ISSUE TITLE
Consider completely disregarding irrelevant encounters

### ISSUE THREAD

**Issue by danielvonmitschke** [corona-warn-app/cwa-app-ios#1380] opened 2020-10-21 11:21 UTC
## Avoid duplicates

* [x] This issue has not already been raised before
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
Only low and high risk encounters are displayed. No additional information about the encounters is provided.
So a low risk encounter could either be a person quickly passing by in 20m distance or a person you are talking with in only 1m distance for quite some time but not matching the criteria to make this a high risk encounter.

## Suggested Enhancement
Display statistical information about recorded risk encounters.
Or eliminate most low risk encounters where only the signal was received for a second or from a very far (calculated) distance.

## Expected Benefits
Less confusion about low risk encounters.
Give users the possibility to evaluate low risk encounters themselves. 
e.g. (assuming that I need to be talking 15min to someone for an encounter to be considered high risk):
If I have 4 low risk encounters where I talked 14min to someone is very different from having 4 low risk encounters where only a signal was received from another phone.

**Comment by Ein-Tim** [comment] 2020-10-21 11:36
Hey @danielvonmitschke 

Please see this Issue in the Wishlist Repo: 
https://github.com/corona-warn-app/cwa-wishlist/issues/100

Please note that the RKI already [denied](https://github.com/corona-warn-app/cwa-wishlist/issues/100#issuecomment-690279530) to show more Informations about Low Risk Encounters.

But there are some open Issues in the Wishlist Repo requesting to show more Information about (Low) Risk Encounters, e.g. https://github.com/corona-warn-app/cwa-wishlist/issues/178, https://github.com/corona-warn-app/cwa-wishlist/issues/205, etc. 

So I think it would be good if we would close this Issue here and continue the Discussion in the Wishlist Repo, what do you think?

**Comment by Ein-Tim** [comment] 2020-10-27 20:01
Since you now changed the title, but also for this Request we have an open Issue in the Wishlist: 🙂
https://github.com/corona-warn-app/cwa-wishlist/issues/181

**Comment by heinezen** [comment] 2020-10-29 16:16
Hello @danielvonmitschke 

As @Ein-Tim pointed out, we already have several wishlist entries dealing with your request:

* https://github.com/corona-warn-app/cwa-wishlist/issues/181 should cover your suggested enhancement regarding low ris encounter display.
* https://github.com/corona-warn-app/cwa-wishlist/issues/100 and the [published statement](https://github.com/corona-warn-app/cwa-wishlist/issues/100#issuecomment-690279530) outline the current position regarding more information inside the app.

I would like to ask you to continue the discussion in these threads, so that the discussion about these features is not spread out and thus easier to follow. I will close your issue here and link it to the other threads as a duplicate

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-10-29 16:16
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/181

**Closed by heinezen** 2020-10-29 16:16 UTC
Labels: enhancement

**Comment by danielvonmitschke** [comment] 2020-10-29 16:20
@Ein-Tim @heinezen 
Thank you
