### ISSUE TITLE
Test certificate for PCR test: "Error during certificate retrieval" (DCC_COMP_202)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3256] opened 2021-07-27 10:22 UTC
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS version: 14.7.1
- App version: 2.5.1

## Describe the bug

I registered a PCR test result in the app yesterday. Today, at 10:00h, my test result was available in the Corona-Warn-App. However, after switching to the certificates tab, I only get this error:

<img src="https://user-images.githubusercontent.com/67682506/127137857-1a478571-9a9b-4fca-806a-4b4e65f8411d.PNG" width="300">

After tapping on "Try Again", I get this error message:

<img src="https://user-images.githubusercontent.com/67682506/127137960-52d1d722-45a9-460c-b21f-05d042deb8a5.PNG" width="300">

This error message links to this FAQ entry: https://www.coronawarn.app/en/faq/#test_cert, which does not give an answer to why this problem happens and what a user should do next.

## Steps to reproduce the issue

1. Register a PCR-test in the app
2. Wait for your result
3. Switch to the certificates tab
4. See the error message shown above

## Expected behaviour

No error message, certificate should be available. If the testing site does not support EU DCC, another error message should be shown. 

## Additional information

Error report ID: 1DD4C0FC878720B0F6CD

<details>
<summary>For everyone interested, this is the important part of the log:</summary>

```
Info 2021-07-27T09:52:13Z
[ENA/HealthCertificateService.swift:230] [executeTestCertificateRequest(_:retryIfCertificateIsPending:completion:)]
[HealthCertificateService] Executing test certificate request: 🙈🙉🙊

Debug 2021-07-27T09:52:13Z
[ENA/CachedAppConfiguration.swift:223] [shouldFetch()]
timestamp >= 300s? 79.04366707801819 >= 300)

Debug 2021-07-27T09:52:13Z
[ENA/CachedAppConfiguration.swift:183] [appConfiguration(forceFetch:)]
fetching cached app configuration

Info 2021-07-27T09:52:13Z
[ENA/HealthCertificateService.swift:264] [executeTestCertificateRequest(_:retryIfCertificateIsPending:completion:)]
[HealthCertificateService] waitAfterPublicKeyRegistrationInSeconds: 10.0, waitForRetryInSeconds: 10.0

Info 2021-07-27T09:52:13Z
[ENA/HealthCertificateService.swift:321] [executeTestCertificateRequest(_:retryIfCertificateIsPending:completion:)]
[HealthCertificateService] Public key already registered, immediately requesting certificate.

Info 2021-07-27T09:52:13Z
[ENA/HealthCertificateService.swift:470] [requestDigitalCovidCertificate(for:rsaKeyPair:retryIfCertificateIsPending:waitForRetryInSeconds:completion:)]
[HealthCertificateService] Requesting certificate…

Error 2021-07-27T09:52:13Z
[ENA/HTTPClient.swift:571] [getDigitalCovid19Certificate(registrationToken:isFake:completion:)]
HTTP error code 202. DCC is pending.

Error 2021-07-27T09:52:13Z
[ENA/HealthCertificateService.swift:500] [requestDigitalCovidCertificate(for:rsaKeyPair:retryIfCertificateIsPending:waitForRetryInSeconds:completion:)]
[HealthCertificateService] Certificate request failed with error Der Vorgang konnte nicht abgeschlossen werden. (ENA.DCCErrors.DigitalCovid19CertificateError-Fehler 5.)

Info 2021-07-27T09:52:15Z
[ENA/HealthCertificateService.swift:230] [executeTestCertificateRequest(_:retryIfCertificateIsPending:completion:)]
[HealthCertificateService] Executing test certificate request: 🙈🙉🙊

Debug 2021-07-27T09:52:15Z
[ENA/CachedAppConfiguration.swift:223] [shouldFetch()]
timestamp >= 300s? 81.14154207706451 >= 300)

Debug 2021-07-27T09:52:15Z
[ENA/CachedAppConfiguration.swift:183] [appConfiguration(forceFetch:)]
fetching cached app configuration

Info 2021-07-27T09:52:15Z
[ENA/HealthCertificateService.swift:264] [executeTestCertificateRequest(_:retryIfCertificateIsPending:completion:)]
[HealthCertificateService] waitAfterPublicKeyRegistrationInSeconds: 10.0, waitForRetryInSeconds: 10.0

Info 2021-07-27T09:52:15Z
[ENA/HealthCertificateService.swift:321] [executeTestCertificateRequest(_:retryIfCertificateIsPending:completion:)]
[HealthCertificateService] Public key already registered, immediately requesting certificate.

Info 2021-07-27T09:52:15Z
[ENA/HealthCertificateService.swift:470] [requestDigitalCovidCertificate(for:rsaKeyPair:retryIfCertificateIsPending:waitForRetryInSeconds:completion:)]
[HealthCertificateService] Requesting certificate…

Error 2021-07-27T09:52:15Z
[ENA/HTTPClient.swift:571] [getDigitalCovid19Certificate(registrationToken:isFake:completion:)]
HTTP error code 202. DCC is pending.

Error 2021-07-27T09:52:15Z
[ENA/HealthCertificateService.swift:500] [requestDigitalCovidCertificate(for:rsaKeyPair:retryIfCertificateIsPending:waitForRetryInSeconds:completion:)]
[HealthCertificateService] Certificate request failed with error Der Vorgang konnte nicht abgeschlossen werden. (ENA.DCCErrors.DigitalCovid19CertificateError-Fehler 5.)
```

</details>

----
Internal Tracking-ID: [EXPOSUREBACK-1351](https://jira-ibs.wbs.net.sap/browse/EXPOSUREBACK-1351)

**Comment by heinezen** [comment] 2021-07-27 16:04
@Ein-Tim 

Thanks for reporting. This is a backend issue that was assumed to be fixed in June. We will investigate why it reappeared.

----
Corona-Warn-App Open Source Team

**Comment by serpensalbus** [comment] 2021-09-21 12:52
Is there still no solution yet? We need the certificate...

**Comment by Ein-Tim** [comment] 2021-09-21 14:19
@serpensalbus 

Try to put the app in background for some minutes (with active internet connection) and open it again, this helped the last time when I got this error.

**Comment by serpensalbus** [comment] 2021-09-21 14:46
Thanks for the idea, but no luck.

**Comment by serpensalbus** [comment] 2021-09-21 14:53
Meanwhile, I tried several times, but always the same error code. Seems to give an IOS app to SAP produces the expected result.

**Comment by luzuku** [comment] 2021-12-04 08:48
I am currently having the exact same issue with a normal test (non-PCR).
The test is shown as negative under the Status tab but on the certificate tab I get the above mentioned error message.
How can this be?

**Comment by Ein-Tim** [comment] 2021-12-04 08:51
@luzuku 

Is the testing station which did the test able to issue EU DCCs? 

I suggest you try what I've suggested in https://github.com/corona-warn-app/cwa-app-ios/issues/3256#issuecomment-924035965. Maybe this helps?

**Comment by luzuku** [comment] 2021-12-04 08:52
My normal intuition would be to delete the certificate and request it again. But the app scares me with the message: "If you remove the certificate, you cannot request it again." So tnow I am stuck with doing nothing and finding no answers in your FAQ...

**Comment by luzuku** [comment] 2021-12-04 08:53
> 



> @luzuku
> 
> Is the testing station which did the test able to issue EU DCCs?
> 
> I suggest you try what I've suggested in [#3256 (comment)](https://github.com/corona-warn-app/cwa-app-ios/issues/3256#issuecomment-924035965). Maybe this helps?

Until now it didn't help.

**Comment by luzuku** [comment] 2021-12-04 09:02
Nobody picks up at the official number from the test station. I will just delete it in the app and show the pdf then (which has QR codes for CWA and luca) and hope this works. But how can it be that CWA accepts this certificate and knows it's results but cannot fetch the certificate. To me this sounds like an issue on your side 🤷‍♂️

**Comment by luzuku** [comment] 2021-12-04 09:07
FYI: After deleting the certificate, the test is still showing in the status tab. This behaviour feels weird. Maybe I just don't know what the difference is. Anyways, I hope my feedback helps somewhow. Thanks for the quick reply.

**Comment by Ein-Tim** [comment] 2021-12-04 09:10
@luzuku 

Yes the test result (shown on the "Status" tab) is separate from the test certificate (shown on the "Certificates" tab).

**Comment by thomasaugsten** [comment] 2021-12-04 09:23
Please provide the test lab we can inform them about the issue.

**Comment by luzuku** [comment] 2021-12-04 13:46
Testzentrum Q Bergheim
Bergheimer Straße 74
69115 Heidelberg
+49 (0) 6221 6390041
kontakt@testzentren-q-heidelberg.de

**Comment by Magoli1** [comment] 2021-12-07 16:29
Same Problem, for the same provider of the tests 🙃

**Comment by Ein-Tim** [comment] 2021-12-07 16:33
@Magoli1 When did you register your test in the app?

@thomasaugsten Is an investigation of this issue going on?

**Comment by thomasaugsten** [comment] 2021-12-07 16:36
@Magoli1 can you please write the provider again?

we are working on this and informing the providers

**Comment by Magoli1** [comment] 2021-12-07 16:42
I just registered it, around 20 minutes ago.

Testzentrum Q Qube Hotel Bahnstadt
Grüne Meile 21
69115 Heidelberg
+49062216390041
kontakt@testzentrum-q-heidelberg.de

Let me know if I can do something from my side.

Cheers

**Comment by tleonard06** [comment] 2021-12-17 19:25
Hello,

I also have the issue with the same provider for a non-PCR test, today around 2 hours ago.

Testzentrum Q Qube Hotel Bahnstadt
Grüne Meile 21
69115 Heidelberg
+49062216390041
kontakt@testzentrum-q-heidelberg.de

Thanks,

Thomas

**Comment by dsarkar** [comment] 2021-12-17 20:23
Good evening @tleonard06 @Magoli1,
Thanks for reporting, we forwarded your issues.
Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by Taeufer** [comment] 2021-12-21 13:18
noticed the issue with test the first time on the 5th of December, called the Hotline on the 6th of December, but they said, that there where issues. in these Days, so I give them time, but is is still a Issue there, first of all i thought maybe a Interface Problem

Testcenter ist the Muhelenkreiskliniken AoeR - POC is no Issue, just PCR

I use the IOS App, CWA Version 2.15.1 (2)
![cw2](https://user-images.githubusercontent.com/96479489/146936105-794b95bf-2a9a-4d77-b3c2-ec818f9a6025.png)
![cw1](https://user-images.githubusercontent.com/96479489/146936281-361d6bc3-abfd-454d-8bcc-67c7fa8e1d75.png)

Same issue with Androis, mention  [https://github.com/corona-warn-app/cwa-app-android/issues/4596](url)
with the same Testcenter.
[cwa-log.zip](https://github.com/corona-warn-app/cwa-app-ios/files/7755574/cwa-log.zip)

**Comment by dsarkar** [comment] 2021-12-21 15:28
@Taeufer Thanks for the report. Internal Tracking-ID: [EXPOSUREBACK-1351](https://jira-ibs.wbs.net.sap/browse/EXPOSUREBACK-1351)

**Comment by Taeufer** [comment] 2021-12-22 15:12
@dsarkar seems top ne fixed- Worked today for the first time since 6th

**Comment by dsarkar** [comment] 2021-12-22 15:46
@Taeufer Thanks for the feedback.

**Comment by thomasaugsten** [comment] 2021-12-22 22:02
We also received the feedback from one provider that they fix an issue on their side

**Comment by Taeufer** [comment] 2021-12-26 10:37
Merry Christmas, and here is the Problem again, may there is a Profilbuild in the Clients( on richclient may get wrong profiles etc, or the Interface again that we could not Match) that is the issue, I guess. Softwarepatner on our Side is ixmid. Will get more informations tomorrow when i am at work. LogID: 138AA6C74ADEF1737E3C or 46F273800B3A72C0060A

**Comment by dsarkar** [comment] 2021-12-27 11:18
Merry Christmas to you as well @Taeufer. Thanks for your report, forwarded to internal ticket.

**Comment by Taeufer** [comment] 2021-12-29 07:39
I can´t get any new Informationen at this time, POC still work. (my coworkers in the lab-IT are on vacation)
I metion to our labratory-IT, that the QR-Codes are noticeably different, they may will get this Information to our Softwarepatner. I will also add the example here (bad quality, but you could get a idea), but my guess is, that there is a Problem which can´t fixed here, and the QR-Code hat nothing to do with it. The Problem @thomasaugsten metion earlier is may the key here - but I will hold you updated
![2021-12-27_09-34-48](https://user-images.githubusercontent.com/96479489/147638085-cda1bcf8-e842-48df-8b32-631b57404b80.png)
.

**Comment by OOME4096** [comment] 2021-12-29 10:07
@Taeufer: you seem quite informed about the technical workflow regarding PCR tests. Maybe you could help us: We did yesterday PCR tests at the mentioned test centre (Johannes Wessling Klinikum), but can’t download the EU COVID-Certificate resulting in before mentioned error DCC_COMP_202. Is there any known workaround to get the certificate until the issue is resolved?

**Comment by dsarkar** [comment] 2021-12-29 13:19
Hi @OOME4096, thanks for reporting. We will forward this issue.

---
Corona-Warn-App Open Source Team

**Comment by Taeufer** [comment] 2021-12-29 14:34
@OOME4096 

I´m sorry,  the same Problem, no solution so far.

POC will work, PCR not, but at the first QR, to get you result, you could download the medical result (Befund), this is the only chance, on the other side there is no scanning possible, but the medical result is all u need, in my opinion. I forwarded the Issue to the Labratory-IT, they will get it to there Provider. I think there is a Issue on the Providerside. Should be fixable in a couple of days, after somone read this.

**Comment by Taeufer** [comment] 2021-12-29 15:21
Log-ID: 7BCFF60A598853CCC5C3

**Comment by dsarkar** [comment] 2021-12-29 15:35
@Taeufer Thanks, forwarded to internal ticket,

**Comment by Taeufer** [comment] 2021-12-30 12:54
Provider has restarted a Service, should be fixed now.
@OOME4096 could you may confirm this ?

**Comment by dsarkar** [comment] 2021-12-30 13:33
@Taeufer Thanks for letting us now.

**Comment by Taeufer** [comment] 2021-12-30 13:45
@dsarkar so there is no bug, but i think the delivery-Service to the CWA. It may could proofed better by something like a uptimecounter for the interface, if possible maybe. Thank you for your support here. bye

**Comment by Ein-Tim** [comment] 2021-12-30 13:50
I'm not able to get a PCR test atm, so I need someone other to confirm this issue is fixed here.

**Comment by Taeufer** [comment] 2021-12-30 13:55
@Ein-Tim I get a PCR worked from the Testcenter (johannes wesling klinikum), that don´t work yesterday. 2 of my coworkers confirmed it on the Androidside alswell, there is no Issue with the CWA, just a Service of the delivering provider has generated the issue, so I am happy, but i can´t speak for @tleonard06

**Comment by OOME4096** [comment] 2021-12-30 14:02
Issue is resolved for me. I can access the covid certificate now.

**Comment by thomasaugsten** [comment] 2022-01-03 08:20
The problems with Q Testzentrum should be also resolved now.

**Comment by Taeufer** [comment] 2022-01-03 17:36
Just a Service restart at the Provider IF?

**Comment by Shaakhal** [comment] 2022-01-29 17:33
I have the same issue with a Rapid-Test today. I use the Corona Warn App on IOS and tried it with my own test result and that of my wife. 

Test Center is : 
Teststelle Schönaich-easy sports
Bahnhofstraße 6
71101 Schönaich
Email: schoenaich@corona-schnelltest-schoenbuch.de
Website: http://www.corona-schnelltest-schoenbuch.de/

**Comment by Taeufer** [comment] 2022-05-05 08:42
and here it is again, called the provider and will report if they´ve done something. 

Error-Logs in CWA, were transmitted: 

ID 464EF74A99D7D9575304
ID 97ADA05B8C2F83ECDA5C
ID DD982B3109D21E4B23B5

**Comment by Taeufer** [comment] 2022-05-05 09:25
at the side of our Softwarepriovder they say, "all is working fine."

 They checked the IF an it works. They will **not** restart it, couse there are no issues on there side. The Data will be gereated.

@dsarkar

**Comment by thomasaugsten** [comment] 2022-05-05 10:46
Error 202 is only forwarded by the CWA. 
In this state all keys are provided by the CWA. 
The DCC Server is now waiting that the test provider is fetching the public keys for his labId and then providing an encrypted payload to the DCC Server.

**Comment by Taeufer** [comment] 2022-05-05 11:38
i will commit this to the testprovider softwarepartner

**Comment by Taeufer** [comment] 2022-05-06 06:18
Provioder changed a Cert, yesterday, but I have still the issue, and some 
colleagues, too - not all colleagues have the Problem, so it is wierd. Provder closed the Ticket so far, and I don´t know what to do next. One Cert have a PRK_403 but this if from last week.

**Comment by Taeufer** [comment] 2022-05-23 06:14
Error is still there, the first Certificate that has a Error, has a PKR_404, all others the DDC_COMP_202.

Could you start the IF on your side? I´ll make a new call at the Provider, but i guess ixmid will not be a great help in this case.

POC and PCR both are broken.

**Comment by thomasaugsten** [comment] 2022-05-23 06:22
Please provide us the provider name, contacts and teststelle we will contact the provider

**Comment by dsarkar** [comment] 2022-05-23 08:12
@Taeufer please see comment https://github.com/corona-warn-app/cwa-app-ios/issues/3256#issuecomment-1134231345

**Comment by thomasaugsten** [comment] 2022-05-23 08:52
Wir haben ix.mid schon am 03.05 wegen anderen Reports kontaktiert.
Es wurden Zertifikate getauscht die zu dem Fehler geführt haben.

Besteht das Problem aktuell weiterhin?

**Comment by Taeufer** [comment] 2022-05-23 09:46
Yes, they told me, that they changed Certificates, at the 05.05., but the Error is still there, was my answer one day ago.

 They closed the Call after that, waiting at a Answer on this thread, I opend a in Comment  [https://github.com/corona-warn-app/cwa-app-ios/issues/3256#issuecomment-1119293517](Comment_3246)

I mailed the Support today, that they had to open the Call again. I went on Vaccation meanwhile, sorry.

Latest Test I Registertd was POC, from today, and i have still the Issue.

**Comment by Taeufer** [comment] 2022-05-24 07:31
Problem Solved, there war at least a Problem on the User-Side.

All "broken Certificates", where old, and displayed above the Blue-Quare, with a error. 

The "new Certificates", get a quick loading Sign, and disapear. (the disapearing wa the "new feature", an the reason for the 
confusion)

All Certificates are available in the "Slide"-Switch or by klicking at the Blue Quare.

Mea Culpa - and thank you ! @thomasaugsten

**Comment by dsarkar** [comment] 2022-05-24 11:47
@Taeufer Thanks for your feedback.

**Comment by svengabr** [comment] 2022-06-13 07:48
Jira ticket is closed.
According to other feedback on this issue, the issue seems resolved.

> Tested on WRU. Bug is not occuring on WRU environment.
>
> When it's only occuring on PROD for a special test center, it should be tracked by a PROD incident.
> 
> Bug can be closed.

**Closed by svengabr** 2022-06-13 07:48 UTC
Labels: bug, mirrored-to-jira

**Comment by Ein-Tim** [comment] 2022-06-13 09:14
@svengabr 

I just experienced this issue yesterday, but I think it is a problem with the specific test center, or?

**Comment by svengabr** [comment] 2022-06-13 09:39
@Ein-Tim Yes that seems to be the case, its an issue with the specific test center
