### ISSUE TITLE
Error 13 / Fehler 13 occurs repeatedly - case 2

### ISSUE THREAD

**Issue by jpm4771** [corona-warn-app/cwa-app-ios#2316] opened 2021-03-30 17:57 UTC
A week ago I was tested positive. After getting the result on my app it stopped working properly. I always get error message 13.

IOS 14.5 beta 5

---

IOS 14.5 beta 5
App Version: 1.15.2 (2)
iPhone Model: ?
Related: https://github.com/corona-warn-app/cwa-app-ios/issues/2220
Internal Tracking ID: [EXPOSUREAPP-5836](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5836)

**Comment by Ein-Tim** [comment] 2021-03-30 18:02
Hey @jpm4771 

Could you please share a screenshot of your app, the version of CWA and the EN-Log.

<details>
<summary>How to export Exposure Notificaiton Logs under iOS 13.7 or newer</summary>


**German:**

`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ `Überprüfungen exportieren`

**English:**

`Settings` ➡️ `Exposure Notifications` ➡️ `Exosure Logging Status` ➡️ `Exposure Checks` ➡️ `Export Exposure Checks`

**To upload the file here, rename it from .json to .txt**
</details>

Thank you!

**Comment by jpm4771** [comment] 2021-03-30 18:43
![7AF9EBD5-74BB-4386-99B0-99953987EE7D](https://user-images.githubusercontent.com/81644841/113039954-88233f80-9198-11eb-8fc0-5773f08bf7f6.png)

**Comment by Ein-Tim** [comment] 2021-03-30 18:48
Thank you. So you already removed the test result again, right?

What "Aktualisiert" time is the app showing (click "OK" on the error message and read what's above the button "Erneut starten".

**Comment by jpm4771** [comment] 2021-03-30 18:58
You‘re welcome.

No, at least I didn't intentionally delete the result.

Aktualisiert time: 25.03.21, 20:05




Tim ***@***.***> schrieb am Di. 30. März 2021 um 20:48:

**Comment by Ein-Tim** [comment] 2021-03-30 19:57
@jpm4771 

Thanks, I think the test result isn't relevant here. If you want to upload a picture, please use the GitHub app or website, you can't attach it to a mail, sorry. 
So please try it again, thank you!

**Comment by jpm4771** [comment] 2021-03-30 20:02
![F65EB308-1C4C-4F7E-BCAA-0F38052736C4](https://user-images.githubusercontent.com/81644841/113049118-8e6ae900-91a3-11eb-9e0b-329e1cc79dbe.png)

**Comment by jpm4771** [comment] 2021-03-30 20:06
One more comment. Yes, the app suggests to wait 24 hours but its saying the same now for 4 or 5 days.

**Comment by Ein-Tim** [comment] 2021-03-30 20:32
@jpm4771 

Yes, this is also not the intended from the unintended behavior 😉

So please do as follow:

Open the iOS Settings -> search for "Corona-Warn" -> "Hintergrundaktualisierung" and turn it off.
Now wait and don't open the app until tomorrow at ca. 15:00h.
Then report back here please.

**Comment by dsarkar** [comment] 2021-03-31 08:03
@jpm4771 Thank you for reporting here. 

We have a couple of questions:
- As @Ein-Tim already suggested wait and do not open the app for 24 h and then give us some feedback, please.
- After that, as @Ein-Tim already suggested, could you please provide the EN-Log:
  - How to export Exposure Notificaiton Logs under iOS 13.7 or newer:
    - German: Einstellungen ➡️ Begegnungsmitteilungen ➡️ Status von Begegnungsaufzeichnungen ➡️ Begegnungsüberprüfungen ➡️ Überprüfungen exportieren
    - English: Settings ➡️ Exposure Notifications ➡️ Exosure Logging Status ➡️ Exposure Checks ➡️ Export Exposure Checks
  - **To upload the file here, rename it from .json to .txt!**
  - It would be ver helpful to have this file, in order to analyse this issue. Thanks.
- iPhone model?
-  Could you correct, comment, confirm or add on the exact course of events:
  - If you saw a red card it means the app gave you a high risk encounter. Is that correct and if so do you remember the date?
  - You scanned a QR code. Date ?
  - You received a positive test result via the app. Date ?
  - Then the app should stop "Risiko-Überprüfung", because the app assumes that you are in quarantine.
  - From the above comments we assume that you (unintentionally) activated "Risiko-Überprüfung" before the 14 days of quarantine ended.  Activating "Risiko-Überprüfung" in this situation will delete the positive test result. 
  - Since then you received Error 13 notifications. Date ?

Many thanks, your feedback is appreciated very much.

---
Internal Tracking ID: [EXPOSUREAPP-5836](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5836)
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2021-04-02 10:12
Dear @jpm4771,

 Thanks again for reporting here. Any updates? See also https://github.com/corona-warn-app/cwa-app-ios/issues/2316#issuecomment-810864571. Feedback is appreciated very much. We have developers looking into this issue. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2021-04-05 07:12
Good morning @jpm4771, 

Is the error 13 notification gone or do you still get the notification every day?
If that is the case, did you try this: #2316 (comment)?

Thanks for the feedback, best wishes, DS

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment] 2021-04-18 12:24
@jpm4771 Could you please give us an update wether you are still seeing the issue? Thank you!

**Comment by Ein-Tim** [comment] 2021-05-02 08:31
Version 2.1 which fixed the unintended occurrence of Error 13 has been released!

It will reach all users in the next 48 hours.

See GitHub Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.1.1 

The PR that fixed this was #2492.

Please update your App, confirm the fix and then close this issue.

Thank you!

**Comment by dsarkar** [comment] 2021-05-03 13:09
Hi @jpm4771,

Siehe den Kommentar oben von @Ein-Tim. Wir würden uns über Feedback von Dir freuen: Kannst Du bestätigen, dass der Fehler bei Dir nicht mehr auftaucht? Vielen Dank, Beste Gruesse, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2021-05-11 09:30
Hi @jpm4771,

See above comment from @Ein-Tim. Could you give us some feedback? Is this issue fixed for you or do you still get Error 13 notifications? Thanks.

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment] 2021-07-13 07:45
@dsarkar I assume we can close this issue.

**Comment by heinezen** [comment] 2021-07-13 11:30
Hello everyone,

Occurences of Error 13/Fehler 13 should be fixed with the recent CWA release 2.5. Please update your app and report back if the error still persists for you when using the newest version. We will close the issue for now.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-07-13 11:30 UTC
Labels: Fix 2.1, bug, mirrored-to-jira
