### ISSUE TITLE
CWA resets when no more memory is available 

### ISSUE THREAD

**Issue by Pelikan3857** [corona-warn-app/cwa-app-ios#1521] opened 2020-11-16 18:37 UTC
I have an iPhone 8 64Gb. Recently I had used up almost all of the available memory.  Something like 10-20 Mbyte where left. 
I then successfully deleted some objects to regain enough memory. 

When I called the cwa-app after that, it had lost all of its history-data and I had to restart the app.  

----

* iOS Version: 13.6
* CWA Version: 1.5.3

![grafik](https://user-images.githubusercontent.com/6852422/99694456-c000d480-2a8c-11eb-9b93-677554064f1d.png)

---
Internal Tracking ID: [EXPOSUREAPP-3886](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3886)

**Comment by Ein-Tim** [comment] 2020-11-16 18:43
Okay that's not good... Could you share a screenshot of the Menu "Begegnungsmitteilungen"/"Exposure Notifications" in the Settings of your iPhone and also a Screenshot of the App's main Screen? 
In the Settings you also find the EN-Log. It would be great if you could share this here too, so we can see if there were any checks done in the background and the App just tells the wrong thing, or if the App is correct and all data is lost.

Thanks! 

<details>
<summary>How to export Exposure Notificaiton Logs</summary>

**German:**

`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ `Überprüfungen exportieren`

**English:**

`Settings` ➡️ `Exposure Notifications` ➡️ `Exosure Logging Status` ➡️ `Exposure Checks` ➡️ `Export Exposure Checks`
</details>

**Comment by Pelikan3857** [comment] 2020-11-16 19:43
Ok...
1. due to the lack of memory I still have iOS 3.6, so things are bit different to what you described. I am not sure where to find
 "Begegnungsmitteilungen"/"Exposure Notifications", but I have uploaded the main-screen and the logs. 
 
Indeed, the exposer-check goes back to the 3. of Nov. while the main-screen says: "...war für 1der letzten14 Tage aktiv"

Main-Screen:
![Cwa-Main-16 11 20](https://user-images.githubusercontent.com/74562561/99298751-79239c80-284a-11eb-976a-05e22282db7c.PNG)

Log:
[ExposureChecks-2020-11-16.json.txt](https://github.com/corona-warn-app/cwa-app-ios/files/5549221/ExposureChecks-2020-11-16.json.txt)

**Comment by Ein-Tim** [comment] 2020-11-16 21:14
> due to the lack of memory I still have iOS 3.6, so things are bit different to what you described. I am not sure where to find
"Begegnungsmitteilungen"/"Exposure Notifications", but I have uploaded the main-screen and the logs.

Okay, under iOS 13.6 this menu is not here yet, but it's not that important.

So or so, form your log I can tell the App reliable downloaded new data until 07.11.. 
On the 08.11. there was no check performed, but then again on the 09.11..
Now the mess really starts, no more checks were prformed since the 09.11. until today (16.11.)

Question: I think you opened the App today for the first time again (after the 09.11.), did the App took longer to launch? (You stayed on the homescreen and it was "downloaded")?

**Comment by Pelikan3857** [comment] 2020-11-17 10:14
Hi Tim, 
thank you for looking into this so rapidly!
The cwa-app version on my phone is 1.5.3 (1). I had thought updating would go automatically nowadays... anyhow, I'll do the update now by hand.

Concening the gap in downloads: The problem with "iPhone memory full" I have a few weeks already. When I can no longer make photos, or apps dont start anymore, I delete some photos / videos / apps a.s.o. until I have enogh space for some time. 
The available space is reduced surprisingly fast though. Then I delete some more items. 

I believe, all the time the available memory drops below a certain value the cwa-app turns off the "risk detection" ("Risiko-Ermittlung") or resets all together.  I think - but I'm not 100% sure to reember correctly - I had to reactivate "Risiko-Ermittlung" at least once, and definitely had to do the "onbording thing" twice (the initial onbording after download not counted).

The last time I did the onbording process was on the 15.11. (NOT on 16.11.) Sinced than the app seemd working. I freed some memory in the morning of 16.11. though. I then called the app while writing the bug-report. It seems, that instance (16.11. 20:19) was the first time, new data was downloaded.

**Comment by Ein-Tim** [comment] 2020-11-17 13:50
>I believe, all the time the available memory drops below a certain value the cwa-app turns off the "risk detection" ("Risiko-Ermittlung") or resets all together.

Mhh, could be possible. I remember an Issue which was opened some time ago where a user also complained about something similar. Unfortunatelly I can't find this anymore ):...

So or so, this is all what I can do for you as a user, I don't know if this is expected behavior or not, maybe @thomasaugsten could jump in here and take a deeper look at this. 

Stay safe and healthy!

**Comment by dsarkar** [comment] 2020-11-19 09:07
Hi @Pelikan3857, 

Any chance you can update to the current CWA version and also the current iOS version? 

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Pelikan3857** [comment] 2020-11-19 09:49
Hi DS,
I already updated to cwa 1.6.1, but iOS 14 seems not possible, because one is expected to have at least 890 Mbyte additional free storage space before installing. If I had that, I wouldn't waste it for iOS14.

Regards, Peter

**Comment by heinezen** [comment] 2020-11-19 16:38
Hey @Pelikan3857 ,

I have created a ticket in our internal Jira for your report (EXPOSUREAPP-3886). The dev team will now investigate the issue. Thank you for supporting the development with your feedback.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by Pelikan3857** [comment] 2020-11-20 11:46
Hi there,
one more observation:
my phone ran out of memory again. Yesterday I had 26Mbyte left. I startet the CWA-App, but it didn't come up, only the display went black for one or two seconds, than the desktop was there again. 
Today I cleared some memory again, calld the app, and it had indeed reset once again. The Exposure-Check-Log this time was deleted as well. It only contained data from yesterday ranging from around 8:30 - 21:00.
Unfortunately I am not 100% sure when I started the app yesterday, but it may have been 8:30.
regards, Peter

**Comment by dsarkar** [comment] 2020-12-07 11:42
@Pelikan3857, can you update to CWA version 1.7.1? Thanks for feedback. Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Pelikan3857** [comment] 2020-12-07 15:59
...yes I already have.
Still, I rearanged my iPhone and have of lot of free memory now, and no strange things happened to the app since then.  So I'm afraid, I cant be of much help in that issue from now on. 
Best regards

**Comment by dsarkar** [comment] 2020-12-08 08:33
@Ein-Tim, we will raise this issue and see if we can get some feedback. 
Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2021-01-05 14:27
@Ein-Tim, from development side no news on this issue.
@Pelikan3857,

> When I called the cwa-app after that, it had lost all of its history-data and I had to restart the app.

What do you mean exactly? You reset the app (not deleted and re-installed) and then is said 1 of 14 days active instead of permanently active? If this is the case, my understanding is that the keys the phone collected are still present, but the CWA doest know that it was actually running since more than 14 days. This would not consist of a mayor problem, although message on screen a bit confusing.

 Can we close this issue if no further problem exists on your side ?

**Comment by dsarkar** [comment] 2021-01-05 21:09
@Pelikan3857, many thanks for your feedback, very much appreciated. I will forward all the information, and the developers will set priorities on on investigating and resolving the issues. Best wishes, DS

**Comment by heinezen** [comment] 2021-06-20 13:50
@Pelikan3857 

We cannot reproduce this issue anymoe and assume it is fixed. Can you chheck if it's still a problem for you?

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2021-07-06 12:21
I guess we'll close here since it is unlikely that the issue still exists if nobody else encounters it.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-07-06 12:21 UTC
Labels: bug, mirrored-to-jira
