### ISSUE TITLE
App not available in US app store

### ISSUE THREAD

**Issue by geapi** [corona-warn-app/cwa-app-ios#3394] opened 2021-08-21 22:41 UTC
This means as a traveler from the US with a primary US app store account you cannot install the app without creating an account in the German app store.

Not sure if that is intended, it increases the threshold for folks visiting to install the app.

**Comment by Ein-Tim** [comment] 2021-08-21 22:46
@geapi 

Yes this is intended, please take a look at our FAQ entry regarding this: https://www.coronawarn.app/en/faq/#international

Also, if you want to deep dive into this topic, I suggest to take a look at https://github.com/corona-warn-app/cwa-wishlist/issues/41.

If I've answered your question and you are satisfied with my answer, I suggest to close this issue.

Have a good night, a nice Sunday and stay safe!

**Comment by dsarkar** [comment] 2021-08-22 07:39
@geapi Thanks for contributing here. As @Ein-Tim suggests, have a look at corona-warn-app/cwa-wishlist#41. 


Best wishes, DS 

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2021-08-22 07:40
Duplicate of corona-warn-app/cwa-wishlist#41.

**Closed** 2021-08-23 23:05 UTC
Labels: duplicate, enhancement
