### ISSUE TITLE
50% of the user-keys have wrong Risk value

### ISSUE THREAD

**Issue by Tho-Mat** [corona-warn-app/cwa-app-ios#1297] opened 2020-10-06 09:42 UTC
## Describe the bug
ToDay keys are now uploaded for 50% of the users.
Most of the keys of this users have the wrong risk values.
6,8,8,8,5,3,1,...
It should be
5,6,8,8,8,5,3,1
For the 1. key the risk is too high,
For the 2., 5., 6., 7. the risk is too low.
I don't know if this affects only iOS or only Android devices or both, so i will publish this on both repositories.
https://github.com/corona-warn-app/cwa-app-android/issues/1325
#1297 
This issue is related to #1097.
@thomasaugsten tried to find out more in #1097 but with no results jet.

## Expected behaviour
Assign the right risk value to the keys.

## Steps to reproduce the issue
At the moment nearly 50% of the users upload a key for the day they upload their keys.
Take a look at 2020-10-05.zip and 2020-10-06-hour-03.zip
I first saw this on 2020-09-15, 2020-09-17, 2020-09-19, (but this lonely ones may be a result of a wrong device time). 
On 2020-09-21 the number starts to increase to nearly 50% now.

## Additional context
In the day file 2020-10-05.zip at least 103-117 users publish a same day key.
(it also contains same day key from 2020-20-04 uploads.)
All keys of this users have the wrong risk values.
6,8,8,8,5,3,1,...
It should be
5,6,8,8,8,5,3,1
For the 1. key the risk is too high,
For the 2., 5., 6., 7. the risk is too low.

## links
https://github.com/corona-warn-app/cwa-app-ios/issues/1097
https://github.com/corona-warn-app/cwa-server/issues/755
https://github.com/corona-warn-app/cwa-server/issues/723
https://github.com/corona-warn-app/cwa-server/issues/856

---
Internal tracking ID: EXPOSUREAPP-3095

**Comment by svengabr** [comment] 2020-10-06 10:08
Hello @Tho-Mat,

Your provided information looks very detailed, thank you very much for that. I am not sure how we will handle the duplication of the Tickets in iOS and Android, I will discuss this internally first.

I have created a Jira ticket `EXPOSUREAPP-3095` for this issue so that the developers are notified.

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by Tho-Mat** [comment] 2020-10-07 11:53
Good new:
https://github.com/corona-warn-app/cwa-app-android/issues/1325#issuecomment-704883307

**Comment by svengabr** [comment] 2020-10-08 11:21
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/1325

**Closed by svengabr** 2020-10-08 11:21 UTC
Labels: bug, mirrored-to-jira
