### ISSUE TITLE
Rapid Test Profile: Date of birth off one day

### ISSUE THREAD

**Issue by abbe79** [corona-warn-app/cwa-app-ios#2695] opened 2021-05-12 22:52 UTC
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 12 Pro
- iOS version: 14.5.1
- App version: 2.2.1 (0)
- MESZ timezone
- German language and localization settings

## Describe the bug

After entering my data in the rapid test profile mask, the birthday included in the QR code (and below in the text summary) is one day before the entered day.

## Steps to reproduce the issue

See screenshots.
1.  Enter a new rapid test profile, choose a date. 
2. Click next. 
3. Compare the date.

## Expected behaviour

The data entered in the mask should be the same as encoded in the qr code (and displayed below)

## Additional context

![IMG_1346](https://user-images.githubusercontent.com/20374998/118053662-3bc94300-b385-11eb-9c45-41036cdddb21.PNG)
![IMG_1347](https://user-images.githubusercontent.com/20374998/118053670-3e2b9d00-b385-11eb-9c4c-c013334357bf.PNG)

----
Internal Tracking ID: [EXPOSUREAPP-7263](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7263)

**Comment by abbe79** [comment] 2021-05-12 23:06
Also reported in #2696

**Comment by Ein-Tim** [comment] 2021-05-13 07:56
Hey @abbe79 same goes here, I am not able to reproduce this (see https://github.com/corona-warn-app/cwa-app-ios/issues/2696#issuecomment-840377994). I even entered the birthday shown on your screenshot and am not able to reproduce this.

Do you use a special keyboard app downloaded from the App Store?

I tried on a real iPhone 6s with iOS 14.5.1 and CWA 2.2.1 and on an Emulator (iPhone 12 Pro) running iOS 14.5 and CWA 2.2.1.

I used MESZ timezone & German language and localization settings, just like you.

**Comment by oleksiikutuzov** [comment] 2021-05-13 08:46
I can also confirm the issue. No special keyboard, MESZ timezone. I tried to create it about at the same time as @abbe79 did. 20 March 1998 worked fine, 30 March 1998 was always saving as 29 March 1998. Currently I can't reproduce it as well.

**Comment by Ein-Tim** [comment] 2021-05-13 08:54
Okay so seems like this is not always reproducible. 

Did this wrong behavior occur when you added a Rapid Test Profile for the first time @oleksiikutuzov @abbe79 @Jens07?

**Comment by dsarkar** [comment] 2021-05-13 08:58
@abbe79 @oleksiikutuzov Thanks for reporting: Internal Tracking ID: [EXPOSUREAPP-7263](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7263)


---
Corona-Warn-App Open Source Team

**Comment by Jens07** [comment] 2021-05-13 09:46
> Do you use a special keyboard app downloaded from the App Store?

No. I never installed a special keyboard. I always use the iOS standard keyboard.

> I used MESZ timezone & German language and localization settings, just like you.

Mee too.

If I tried it with the date of birth of @Ein-Tim here in #2696, I got a correct result.

> Did this wrong behavior occur when you added a Rapid Test Profile for the first time @oleksiikutuzov @abbe79 @Jens07?

At the first time I saved the dataset by mistake only with name, surname and my date of birth. Unfortunately I can't remember if the date of birth had been correct.

**Comment by abbe79** [comment] 2021-05-13 10:27
@Ein-Tim no special keyboard or other custom settings. 

Seems like to have something to do with the system time. Perhaps try it again between 00:00 and 01:00 o'clock when using MESZ. 

I guess the ISO8601DateFormatter uses GMT and I am in MESZ. But I am not very deep into Swift, so this is just an assumption.

**Comment by Jens07** [comment] 2021-05-13 15:19
Today I could save all dates of birth I wanted.

> Seems like to have something to do with the system time. Perhaps try it again between 00:00 and 01:00 o'clock when using MESZ. 

That's a good advice. I will try it again after midnight.

**Comment by Ein-Tim** [comment] 2021-05-13 18:30
@abbe79 

I was now able to verify that this is indeed a problem that only occurs if your time is between 00:00h and 02:00h MESZ. So yes, seems like that this is sealed to the Timezones. However, I wonder how this affects a date 🤔

**Comment by jucktnich** [comment] 2021-05-13 20:22
We're two hits of Greenwich , right?

**Comment by dsarkar** [comment] 2021-05-13 20:36
Thanks to all for analysing ! Will forward you findings to the internal ticket ! Good night!

**Comment by Jens07** [comment] 2021-05-13 21:19
> We're two hours off Greenwich, right?

You're right!

**Comment by heinezen** [comment] 2021-05-13 21:31
@Ein-Tim 

> I was now able to verify that this is indeed a problem that only occurs if your time is between 00:00h and 02:00h MESZ. So yes, seems like that this is sealed to the Timezones. However, I wonder how this affects a date thinking 🤔

I recommend watching the video [The Problem with Time & Timezones (10:12)](https://www.youtube.com/watch?v=-5wpm-gesOY) from Computerphile if you want to know how these problems might happen :smile: Note that the bug in this issue could very well be something completely different, but handling time is always a bit of an issue in programming.

**Comment by abbe79** [comment] 2021-05-13 23:21
@Ein-Tim thanks for confirming!
I guess one component is localized (UIDatePicker?) and the other one uses GMT. When the value gets transferred in between the components two hours are subtracted. This leads to falling back one day between 00:00 and 01:59.

But it has been years that I've programmed ObjC, so this is just an assumption.

**Comment by jucktnich** [comment] 2021-05-14 07:23
https://github.com/corona-warn-app/cwa-app-ios/blob/release/2.3.x/src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/AntigenTestProfileViewModel.swift on row 141 timezone has to be changed from none to cet

**Comment by Ein-Tim** [comment] 2021-05-14 07:26
@jucktnich I'll modify my environment with your suggested change and try if it works!

**Comment by jucktnich** [comment] 2021-05-14 07:40
Or on https://github.com/corona-warn-app/cwa-app-ios/blob/release/2.3.x/src/xcode/ENA/ENA/Source/Scenes/CreateAntigenTestProfile/CreateAntigenTestProfileViewController.swift row 191 set timezone to gmt, would be probably better for persons outside cet. (https://developer.apple.com/documentation/uikit/uidatepicker)

**Comment by jucktnich** [comment] 2021-05-14 07:45
Or on https://github.com/corona-warn-app/cwa-app-ios/blob/release/2.3.x/src/xcode/ENA/ENA/Source/Scenes/CreateAntigenTestProfile/CreateAntigenTestProfileViewController.swift row 191 set timezone to cet in combination to the proposal I made first, would be probably better for persons outside cet. (https://developer.apple.com/documentation/uikit/uidatepicker)

**Comment by dsarkar** [comment] 2021-05-17 09:37
FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/2707

**Comment by dsarkar** [comment] 2021-05-20 10:49
FYI new PR https://github.com/corona-warn-app/cwa-app-ios/pull/2741

**Comment by Ein-Tim** [comment] 2021-06-09 05:31
Version 2.3 has been released to the App Store yesterday, can you confirm the fix @abbe79?

**Comment by abbe79** [comment] 2021-06-09 22:13
@Ein-Tim What a great excuse to stay up late again! 😉

Just tested it, right after midnight. 
It's working, thank you all for improving the app!

**Comment by Ein-Tim** [comment] 2021-06-10 04:38
@abbe79 

Haha 😄

Thank you for confirming, as the author of this issue you can go ahead and close this issue. 

Thank you!

**Closed** 2021-06-10 04:46 UTC
Labels: Fix 2.3, bug, mirrored-to-jira

**Comment by dsarkar** [comment] 2021-06-10 07:30
Dear @abbe79 and community! Thanks for reporting and analysing this issue here! Best, DS

---
Corona-Warn-App Open Source Team
