### ISSUE TITLE
Contact-tracing-logs are not transmitted to new phone

### ISSUE THREAD

**Issue by daniela-waranie** [corona-warn-app/cwa-app-ios#1637] opened 2020-12-08 11:00 UTC
I got a new iphone and migrated all data/apps from previous iphone to new phone via IOS standard migration process ("personal wifi hotspot backup").

Tracing data was not transmitted to the new phone. If in the meantime new infected persons data are made public available, then, as i have no data about the past, i would not get a warning that i had a critical contact on my new iphone (even if the contact was recorded on my old phone and could have been warned by my old phone).

To carry 2 phones for 14 days is a workaround. But some people may not even aware that they have to carry 2 phones for 14 days to make a "perfect" transition to a new phone and to stay safe.

## Expected behaviour
tracing data should be copied to new iphones or there should be a big warning AND an alternative transfer-mechanism.

old iphone: 8 plus, IOS 14.0.1
new iphone: iPhone X, IOS: 14.2
context: new iphone was reset to factory defaults, standard restore from old iphone via WLAN

**Comment by heinezen** [comment] 2020-12-08 12:03
Hey @daniela-waranie ,

Thank you for the suggestion. We get this request a lot, but unfortunately we currently cannot do much about it, since the underlying Exposure Notification API by Apple does not allow exporting the tracing data to a new device (same for Google's Android implementation). Therefore, the feature you propose is not possible right now. However, we have forwarded the feedback to Apple and will re-evaluate a possible implementation if the situation changes.

Since we already have a similar issue to yours open (https://github.com/corona-warn-app/cwa-wishlist/issues/8), I will close your issue as a duplicate.

Best Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2020-12-08 12:04
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/8

**Closed by heinezen** 2020-12-08 12:04 UTC
Labels: bug

**Comment by daniela-waranie** [comment] 2020-12-08 12:41
What about a dialog to inform a user on a recently restored iPhone to carry new AND old phone as a workaround?

**Comment by Ein-Tim** [comment] 2020-12-08 12:51
@daniela-waranie I think this is not possible since CWA will not "note" that it was backuped from another phone.

**Comment by Ein-Tim** [comment] 2020-12-08 13:02
See also #1613

**Comment by daniela-waranie** [comment] 2020-12-08 14:26
When the app is started the very first time, the app is showing a sequence of dialogs informing the user about some stuff. Why not asking if this is "the very first time a user uses this app" or if "this app was reinstalled again" of if "user had switched to a new phone", and then show the relevant hints.

**Comment by Ein-Tim** [comment] 2020-12-08 14:31
@daniela-waranie 

This is a good idea I think, you could propose this [here in the CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist/issues/new?labels=enhancement&template=02_enhancement.md)
