### ISSUE TITLE
CWA does not stop camera session when leaving the Scan screen

### ISSUE THREAD

**Issue by trispo** [corona-warn-app/cwa-app-ios#1431] opened 2020-10-30 09:24 UTC
## Describe the bug

After scanning my QR code and leaving the scan screen, I noticed, that the camera indicator on iOS 14 is still green which means, the app does not stop the camera session correctly.

## Expected behaviour

The camera session should be stopped after leaving the scan screen and the green dot should disappear.

## Steps to reproduce the issue

1. Go to 'Informieren & helfen'
2. Tap on 'Weiter'
3. Tap on 'Dokument mit QR-Code'
4. Tap on 'Erlauben'
5. See green dot indicating that a camera session is started
6. Try to scan a QR code. (Mine says "Befund wurde nicht gefunden")
7. Leave the screen by tapping 'Abbrechen'
8. See the green dot is still present

## Technical details

- iOS Version: 14.2 beta 4
- Device: iPhone XS

## Possible Fix

Just stop the camera session.

---
Internal Tracking ID: EXPOSUREAPP-3572

**Comment by dsarkar** [comment] 2020-10-30 10:12
Deat @trispo,

Thanks for your contribution.
Can you confirm that you are using CWA version 1.5.3?
Actually, I can reproduce your issue in version 1.5.3, and it seems that only closing and re-opening the CWA closes the camera session. I add a screenshot for documentation purposes. We will let you know here when we have opened an internal tracking ticket for the developers.

Best wishes,
DS

Corona-Warn-App Open Source Team
![image](https://user-images.githubusercontent.com/1409741/97692585-3f0f7800-1aa0-11eb-9a50-43e9d4fbf23d.png)

**Comment by trispo** [comment] 2020-10-30 10:18
Yes, I confirm.

![image](https://user-images.githubusercontent.com/1045441/97693520-95c98180-1aa1-11eb-8fc9-71cf251845e1.png)

**Comment by Ein-Tim** [comment] 2020-10-30 13:32
Interesting, I can't reproduce on my iPhone XR with iOS 14.1 and newest CWA version and also can't reproduce on iPhone 6s with iOS 14.2 Public Beta 4

**Comment by trispo** [comment] 2020-10-30 21:25
Just updated to the iOS 14.2 GM. The issue still exists.

**Comment by thomasaugsten** [comment] 2020-10-31 11:27
Not reproducible from our side.

**Comment by Ein-Tim** [comment] 2020-10-31 11:36
@thomasaugsten But @dsarkar stated above that he could reproduce this...

**Comment by trispo** [comment] 2020-10-31 12:09
Would it help if I provide a video how to reproduce this?

**Comment by thomasaugsten** [comment] 2020-10-31 16:29
Hi this was a mistake by me I did a wrong path. Thanks for reporting this we will fix this soon.

**Comment by dsarkar** [comment] 2020-11-03 08:29
Dear @trispo, dear community, 

Thanks again for your contributions.

We have created a ticket for the bug (Internal Tracking ID: EXPOSUREAPP-3550) in the internal Jira system. The developers will look into this issue now. Any further developments will be communicated here in this Github issue.

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by KaiTeuber** [comment] 2020-11-26 10:21
This issue should be solved, just checked the latest version.

**Comment by dsarkar** [comment] 2020-11-26 13:45
Dear @trispo, @KaiTeuber, thanks for contributing. We will close this issue in that case. 

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Closed by dsarkar** 2020-11-26 13:45 UTC
Labels: bug, mirrored-to-jira
