### ISSUE TITLE
Allow to enter QR code manually if scanning fails

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#1413] opened 2020-10-27 08:30 UTC
## Avoid duplicates

* [ ] This issue has not already been raised before
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Suggested Enhancement

Sometimes (often?) the scanning of the QR code fails.
In this case an alternate input method for the code should be provided, e.g. manual input.
After all, the scanning gives no security by itself (or am I wrong here?), scanning is only convenience. The "encoded value" should be printed in human-readable format besides the QR code in any case.

## Expected Benefits

Better coverage of the lab use case in case of technical problems like: bad quality of QR code, or bad / broke camera

Note: This improvement idea might also apply to the Android version of the app?

**Comment by dsarkar** [comment] 2020-10-27 08:49
Dear @ndegendogo,

Thank you very much for your proposal. This proposal is actually a duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/227. I would like to ask you to continue there any further discussion, please. I will close hereby this issue.

Best regards,
DS

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-10-27 08:49
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/227

**Closed** 2020-10-27 08:49 UTC
Labels: duplicate, enhancement
