### ISSUE TITLE
[Localization] German text "Anzahl der bereitgestellten Schlüssel" too long

### ISSUE THREAD

**Issue by mw76** [corona-warn-app/cwa-app-ios#820] opened 2020-07-01 11:56 UTC
## Avoid duplicates

* [x] This issue has not already been raised before

## Current Implementation
Platform: iOS 13.5.1
Language: German

In the Setting app under Under "Datenschutz > Health > COVID-19-Kontaktprotokoll > Kontaktüberprüfungen > [DATE]" there is a string saying "Anzahl der bereitgestellten Schlüssel" followed by a number.
When increasing the text size in the Settings app, this string is leaving too little space to display the following number.

![image](https://user-images.githubusercontent.com/12535311/86240428-8133b600-bba1-11ea-890a-4586a9214707.png)

## Steps to reproduce

- In the iOS Settings app, increase font size under "Bedienungshilfen > Anzeige & Textgröße > Größerer Text"
- In the iOS Settings app, navigate to "Einstellungen > Datenschutz > Health > COVID-19-Kontaktprotokoll > Kontaktüberprüfungen > [DATE]""

## Suggested Enhancement

- Shorten "Anzahl der bereitgestellten Schlüssel" to "Bereitgestellte Schlüssel"
- Shorten "Anzahl der abgeglichenen Schlüssel" to "Abgeglichene Schlüssel"

## Expected Benefits

This should leave enough room for the following numbers to be displayed properly.

**Comment by ferdinand** [comment] 2020-07-01 12:10
Issues of the iOS Settings app can only be fixed by Apple.

**Comment by mw76** [comment] 2020-07-01 12:12
Ok. Chances were that those strings for app specific settings are provided by the app and could be changed by the developer.

**Comment by inf2381** [comment] 2020-07-01 12:26
Duplicate of #791

**Closed by inf2381** 2020-07-01 12:26 UTC
Labels: enhancement
