### ISSUE TITLE
Inconsistent behavior of the main screen widgets

### ISSUE THREAD

**Issue by odrotbohm** [corona-warn-app/cwa-app-ios#954] opened 2020-07-25 12:32 UTC
When you open the app, you immediately see three three different widgets. However, they behave inconsistently amongst themselves and also inconsistently to what they indicate they'd do.

![IMG_8777](https://user-images.githubusercontent.com/128577/88456958-df8f4400-ce82-11ea-9a3f-606537253492.PNG)

They all indicate they'd lead to the right due to the arrows in the upper right of the widget. Here's how they actually behave:

1. Navigates to the right, exposing the default iOS behavior. A swipe from the left navigates back from the details view. I think this is most correct.
2. Although the arrow points to the right it produces an overlay coming in from the bottom. That overlay be closed via either the close icon in the upper right or being swiped down. This is inconsistent both to 1 and to what's visually indicated would happen.
3. Looks like 1, but behaves like 2.

Is there a reason for this?

---
Internal Tracking ID: EXPOSUREAPP-1930

**Comment by fredrb** [comment] 2020-07-25 13:10
I think this is a fair point. I tested this on my own phone and indeed the first widget is the only that seems consistent to the arrow icon. I am not aware of any reason why this is like this. Maybe someone from the development team can clarify. 

@odrotbohm Do you have any suggestions on how this should be? I can see this going two ways:

1. Change the side arrows to some other icon (something like an up arrow since the widget opens up?)
2. Widget 2 and 3 should navigate to the side

**Comment by melloskitten** [comment] 2020-07-25 14:12
I believe this is an issue that is best addressed by our UX or UI designers, no? @tkowark is there a possibility to run this by the UI/UX teams as well?

**Comment by tkowark** [comment] 2020-07-25 14:13
Yes, we'll forward it to the UX team to get their feedback on that. Thanks for the report!

**Comment by odrotbohm** [comment] 2020-07-25 18:09
Thanks for getting back so quickly and taking action. Would't have expected that. 🙃🙏

**Comment by dsarkar** [comment] 2021-01-18 12:00
I can still reproduce this. Forwarded to devs.

**Comment by Ein-Tim** [comment] 2021-01-19 20:20
The contact journal box (which was added in version 1,10.1) behaves correct.

**Comment by Ein-Tim** [comment] 2021-02-10 06:17
@dsarkar 

This issue was reported 7 month ago. Is there any update about this?

**Comment by dsarkar** [comment] 2021-02-10 07:41
@Ein-Tim This ticket is classified as a story, i.e. wishlist item, not a bug, and has low priority at the moment, but yes, it is something they are looking into.

**Comment by Ein-Tim** [comment] 2021-02-10 07:45
Thanks for the clarification @dsarkar.
Maybe consider to remove the `bug` label and add the `enhancement` one.

**Comment by Ein-Tim** [comment] 2022-04-13 12:46
I meanwhile think this issue report is not valid, as the app follows OS standards here.

E.g. the Apple Weather app also has this "inconsistent" behavior:
![IMG_3868](https://user-images.githubusercontent.com/67682506/163182874-82837e51-64ff-42ca-9a1e-f0a899273d6b.PNG)

While the arrow points to the right side, when you click on it, a overlay coming from the button opens.

I therefore vote to label this issue as `wont fix` and close it.

**Comment by dsarkar** [comment] 2022-04-13 14:06
@Ein-Tim Thanks for your feedback; I forwarded your info to the UX team.

**Comment by svengabr** [comment] 2022-06-13 09:37
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Wont Fix`
Status: `Obsolete`

Developer comment:
> ...other apps have similar design, therefore on GH it was suggested by a community member to close this issue
> 
> ... we also took care of this as part of the redesign. But yes we can close this bug then.

**Closed by svengabr** 2022-06-13 09:37 UTC
Labels: enhancement, UX, mirrored-to-jira
