### ISSUE TITLE
App not checking the bluetooth contact protocol  

### ISSUE THREAD

**Issue by FSpitzer** [corona-warn-app/cwa-app-ios#702] opened 2020-06-18 08:13 UTC
## Describe the bug

According to the „COVID-19-Kontaktprotokoll“ in iOS settings section, the App did not check for contacts in the last 24h. I have the App installed already for 36h and the app states it already updated twice.

To me it looks like either app or iOS don‘t work as expected.
![63245ABF-5925-4C09-9498-09DBD9F74DBF](https://user-images.githubusercontent.com/35015/84994656-4b2b1680-b14b-11ea-9b0f-b2dc298bd605.jpeg)
![3730E590-D84E-4792-9001-DC500B2D6131](https://user-images.githubusercontent.com/35015/84994873-9d6c3780-b14b-11ea-99a4-42d5dc348622.jpeg)

## Expected behaviour

If app checks for my recent contacts that should be stated in iOS settings.

## Technical details

- Host Machine OS (Windows/Linux/Mac):
iOS 13.5.1 on iPhone SE (2020)
App Version 1.0.2 (2)

**Comment by inf2381** [comment] 2020-06-18 08:54
Duplicate of #675. Currently, there are no submitted keys on the server. Hence, the app can not check whether you have been exposed to a sick person.

**Closed by inf2381** 2020-06-18 08:54 UTC
Labels: bug
