### ISSUE TITLE
Using iOS 14.2 leads to the following issues wirh the app:

### ISSUE THREAD

**Issue by marsp61** [corona-warn-app/cwa-app-ios#1374] opened 2020-10-20 14:17 UTC
EN 2
EN 11
EN 13

It's not working since 16.10.2020 is there Beta of the which I could test? Or will be the upcoming update of the app solve the issue? Or can it be only solved on side of Apple?

## Your Question

* Website URL Path:
* Line / Paragraph:
* Question:

**Comment by heinezen** [comment] 2020-10-20 14:18
Duplicate of #1339

**Closed** 2020-10-20 14:17 UTC
