### ISSUE TITLE
App does not start under IOS 14

### ISSUE THREAD

**Issue by licht100** [corona-warn-app/cwa-app-ios#943] opened 2020-07-24 09:36 UTC
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

after opening the app under IOS 14, only a white screen appears.
even after reinstalling the app it does not work.  

## Steps to reproduce the issue

[IMG_9F44102C155A-1](https://user-images.githubusercontent.com/18720667/88378682-c498d300-cda1-11ea-80d1-fc4404e33e2c.jpeg)

## Technical details

- iOS Version: 14 DEV Beta 3 
- Device: Apple Iphone 10 (x)

## Possible Fix

can it be that the app is not activated for ios 14?

**Comment by Ein-Tim** [comment] 2020-07-24 09:38
Duplicate of #899 you could also take a look at the [FAQ](https://www.coronawarn.app/de/faq/#ios_14_beta)

**Closed** 2020-07-24 09:51 UTC
Labels: bug
