### ISSUE TITLE
Exposure logs duplicates 

### ISSUE THREAD

**Issue by Enib80** [corona-warn-app/cwa-app-ios#1475] opened 2020-11-08 17:10 UTC
Hallo, 
I have installed the latest version of the CWA app. However this does not help to manually activate the "Update" even when all parameters are set (-> hintergrundaktualisierung). 
My question: 

1) Does it mean that the app stops to register keys from the moment it would regularly be updated. And there is a gap until it is updated again?

2) on 7.11.2020 I received following updated (See attachment). What does that mean? It seems weird having to updates at the same time. Does this mean I had on Friday 7.11.2020 14 low risk contacts with 14 different people? Or can that be a duplicate? On that day  I did only passed by 5 people in a shop. Alltogether I was only 20 minutes in the shop. Thus I am wondering whether the contacts can also come from neighbours. And I wonder whether the same contact will be counted twice or more often. 

3) I backed up my iphone on icloud and migrated to a new iphone. I was wondering whether the history of the CWA app is migrated, too. But it isn't or wasn't. Is there an option to migrate the history manually? 

4) If I have several devices with the same Apple -ID. Or if I use one device with several Apple-IDs (from family). What impact does it have on the CWA exposure log?

Thank you very much for clarifying.

![Unbenannt](https://user-images.githubusercontent.com/74143261/98471402-3c252d80-21ec-11eb-8c71-f83ea11d8dcc.PNG)

~~Internal Tracking ID: EXPOSUREAPP-3682~~ Duplicate/Obsolete

---
Internal Tracking ID: EXPOSUREAPP-3664

**Comment by Ein-Tim** [comment] 2020-11-08 21:29
Just one question from me @Enib80 

What do you mean with: 
> I have installed the latest version of the CWA app. However this does not help to manually activate the "Update" even when all parameters are set (-> hintergrundaktualisierung).

Are Checks not done even if you have the App opened? Or are Background checks not running reliable?

**Comment by Enib80** [comment] 2020-11-09 08:09
Yes the checks are not done, even if I have the app opened and also
installed the latest version (as recommended in the forum). Background
checks are not running reliable. Just on 7.11 to checks with the same data
is done. Same number of key, same string.  Each of them report 7, which
makes 14. Thus did I have 7 or 14 contacts then....


Also with a number of 2500 of infection notified via the app on one day in
Germany. I wonder that I have been close to 7 (or 14) of them in the
limited time I have been out of the apartment. all of them have been
informed to me on the same day. However I have not knowingly been in
contact with someone I know being tested positive.

Thank you


Am So., 8. Nov. 2020 um 22:29 Uhr schrieb Ein_Tim <notifications@github.com

**Comment by Enib80** [comment] 2020-11-09 08:16
3:30 this morning. I woke up and updated. This is why it is this time...
There are two additional strings compared to the update on 7.11. at 23.
o'clock

Am Mo., 9. Nov. 2020 um 09:09 Uhr schrieb Sabine Mayerhofer <
sabine.mayerhofer@gmail.com>:

**Comment by Ein-Tim** [comment] 2020-11-09 14:22
@Enib80 
Okay thanks for the Information, could you please share your Exposure Logs & an Screenshot of the App here? 
Thanks!


<details>
<summary>How to export Exposure Notificaiton Logs (iOS)</summary>

**German:**

`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ `Überprüfungen exportieren`

**English:**

`Settings` ➡️ `Exposure Notifications` ➡️ `Exosure Logging Status` ➡️ `Exposure Checks` ➡️ `Export Exposure Checks`
</details>

**Comment by Enib80** [comment] 2020-11-09 14:35
[ExposureChecks-2020-11-09.txt](https://github.com/corona-warn-app/cwa-app-ios/files/5511160/ExposureChecks-2020-11-09.txt)

**Comment by Ein-Tim** [comment] 2020-11-09 14:48
Okay interesting, thanks.
Maybe @diampi could also take a look at this just too ensure that I don't get anything wrong here.

The Hash `DF09694A302A2C2EA8A7709C32AC7EC117B11A1092951124ED2DC287750FCCAD` was first downloaded at 07.11.20. There no matches were found. Then on 08.11.20 there was no check, but today (09.11.20) there was a check which downloaded the Hash **twice**. 
This is definitely not how it should be. I would trust the Number of Encounters in CWA, so you had 7 encounters. 

Two more questions:
1. When did you update to iOS 14.1? Before or after the 07.11.20? 
2. Could you please update to iOS 14.2 and do a check and share your log again? (The next Check will earliest ne possible tomorrow in the early morning)

**Comment by Enib80** [comment] 2020-11-09 15:03
I updated it I think at least two weeks ago. The check on 7.11 was at 23 o'clock. Already then the two same strings there reported. There is no check yesterday, because it did not do it automatically. .

Does it mean that the encounters have been at the same day? Or can it be, that the 7 encounters can be anytime in the past and this is due to the fact that the testing facilities do a mass upload of their test result?

**Comment by Ein-Tim** [comment] 2020-11-09 16:19
> Does it mean that the encounters have been at the same day?

Could be, but also could not be. You can only definitely tell if the Encounters start to disappear, then they are older than 14 days.

**Comment by Ein-Tim** [comment] 2020-11-09 18:01
@thomasaugsten Would you like to jump in here since the App is definetly not working correctly (downloaded the same Hash twice)? 
Thanks!

**Comment by daimpi** [comment] 2020-11-10 00:19
@Ein-Tim, @Enib80 

Looking at your EN log checks have been performed pretty consistently before the Nov 07.

Date | No. of checks performed
-- | --
26\. Okt | 14
27\. Okt | 14
28\. Okt | 14
29\. Okt | 14
30\. Okt | 14
31\. Okt | 14
02\. Nov | 14
03\. Nov | 14
04\. Nov | 14
05\. Nov | 14
06\. Nov | 14
07\. Nov | 16
09\. Nov | 15

14 checks per day as expected.

But then on the Nov. 07. There are two packages which are each checked twice:
```
{
          "Hash" : "DF09694A302A2C2EA8A7709C32AC7EC117B11A1092951124ED2DC287750FCCAD",
          "MatchCount" : 7,
          "KeyCount" : 29195,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-11-07 23:28:14 +0100"
        },
        {
          "Hash" : "DF09694A302A2C2EA8A7709C32AC7EC117B11A1092951124ED2DC287750FCCAD",
          "MatchCount" : 7,
          "KeyCount" : 29195,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-11-07 23:28:13 +0100"
        }
```
(This is the package which contains the diagnosis keys (DKs) which caused the 7 encounters)

And the other package:
```
{
          "Hash" : "1068092B709B3F06B1B2F6FB069158F4EFC6AEF43745EA950B727C7BCFBC3B53",
          "MatchCount" : 0,
          "KeyCount" : 14422,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-11-07 23:28:03 +0100"
        },
        {
          "Hash" : "1068092B709B3F06B1B2F6FB069158F4EFC6AEF43745EA950B727C7BCFBC3B53",
          "MatchCount" : 0,
          "KeyCount" : 14422,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-11-07 23:28:02 +0100"
        }
```
Which was also submitted twice to the Exposure Notification Framework (ENF) but doesn't contain any matches.

Then checks are missing on the 08th and on the 09th the package with the matches is again submitted twice to ENF (and the two submission are again separated by one second between them):
```
{
          "Hash" : "DF09694A302A2C2EA8A7709C32AC7EC117B11A1092951124ED2DC287750FCCAD",
          "MatchCount" : 7,
          "KeyCount" : 29195,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-11-09 03:30:05 +0100"
        },
        {
          "Hash" : "DF09694A302A2C2EA8A7709C32AC7EC117B11A1092951124ED2DC287750FCCAD",
          "MatchCount" : 7,
          "KeyCount" : 29195,
          "AppBundleIdentifier" : "de.rki.coronawarnapp",
          "Timestamp" : "2020-11-09 03:30:04 +0100"
        }
```
 
@Enib80 your CWA is showing 7 encounters, right? That should be correct, but why there are multiple submissions of the same package to ENF on the same day is beyond me and doesn't sound like it's working as intended tbh.

**Comment by thomasaugsten** [comment] 2020-11-10 08:36
We will check why the same key file is passed twice in the ENF

**Comment by ndegendogo** [comment] 2020-11-11 08:37
> if I use one device with several Apple-IDs (from family). What impact does it have on the CWA exposure log?
 
@Enib80 This question should also be answered by the dev team (or even by Apple?). 
To rephrase: is the ENF aware of this family usage? Does it collect separate databases of RPI (contacts) per user? Which does it use while no one is logged in?

@thomasaugsten

**Comment by ndegendogo** [comment] 2020-11-11 08:41
> If I have several devices with the same Apple -ID

@Enib80 if you don't carry both with you all the time, of course they will pick up different RPI / contacts. Both will perform checking, independently.

**Comment by dsarkar** [comment] 2020-11-11 10:18
Hi @Enib80, @thomasaugsten, and community,

This issue is internally tracked: Internal Tracking ID: EXPOSUREAPP-3682.

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment] 2020-11-11 14:35
@ndegendogo

I know you want these questions to be answered by the Devs but just if you wanna have a quick answer I will share my personal opinion:

> To rephrase: is the ENF aware of this family usage? Does it collect separate databases of RPI (contacts) per user? Which does it use while no one is logged in?

I don't think that the ENF Is aware of any family usage. Even if it would be it is not important since the UX of CWA does not support something like this. All Encounters recorded by the ENF, no matter which (or if an) AppleID is signed in, will be shown in the App. 

And if you change the AppleID on your iPhone the Encounters in CWA will stay the Same.

Still I think this is a good question and important to be answered by someone official 🙂

**Comment by Ein-Tim** [comment] 2020-11-16 06:38
I also experience this Issue (thx @ndegendogo for the hint):
https://github.com/corona-warn-app/cwa-app-ios/files/5542648/ExposureChecks-2020-11-15.txt

On the 15.11. and also on the 14.11. the Hash `54EB693E49198CB491546099297CEAC3A12E32D0A6D78DB619B2CD86E84ACD66` is always downloaded 2 times.
(You can ignore that there are so many checks on the same day, I tested something (#1514))

@thomasaugsten Are you able to reproduce this?

**Comment by Enib80** [comment] 2020-11-16 09:01
Hallo,

Update:

the weird thing now is that on one of my iphones the CWA app is updating
and creating a log whenever I open the the app - although several times a
day. Every time the logs are duplicated.

Whereas on the other device, the CWA updates only once per day. On the
other device the App was installed ~one week ago. The devices are using the
same Apple ID. The strings in the "Begegnungsprüfung" are the same -
except in the other devices the strings are duplicated, and the "risk
encounters" are not reported. Except of apparently one which was when I had
both devices with me.

Thus somehow the history from my view must be linked to the Apple-ID,
although risk encounters are not reported - as basically the smartphones
"have not been nearby each other" although the user has....



Am Mo., 16. Nov. 2020 um 07:38 Uhr schrieb Ein_Tim <notifications@github.com

**Comment by ndegendogo** [comment] 2020-11-16 11:29
@Enib80 the strings that you see in your log files are the hash values of the DEK key files that you dowloaded. Everybody here gets the same files.

**Comment by Ein-Tim** [comment] 2020-11-16 14:26
@Enib80 
And about: 
> CWA app is updating and creating a log whenever I open the the app - although several times a day.

This is, at the moment with 1.6.1, intended, see: https://github.com/corona-warn-app/cwa-app-ios/issues/1514#issuecomment-727602796


> Whereas on the other device, the CWA updates only once per day.

Which version is this device running?

**Comment by dsarkar** [comment] 2020-12-07 11:51
HI @Enib80, @ndegendogo, @Ein-Tim, dear community,

This issue was fixed and should not occur again. For a couple of days we will keep this issue open for feedback before closing it.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-12-09 09:23
Dear @Ein-Tim, @ndegendogo, @Enib8, and community

Thank you for your contributions. This issue will be closed now. Re-open if necessary!  
Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Closed by dsarkar** 2020-12-09 09:23 UTC
Labels: bug, mirrored-to-jira, question
