### ISSUE TITLE
Vaccination status can be manipulated by changing the system time

### ISSUE THREAD

**Issue by pizuz** [corona-warn-app/cwa-app-ios#2935] opened 2021-06-15 11:14 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the documentation repository

Can‘t say

* [x] Bug is not already reported in another issue

## Technical details

- Device name: any
- iOS version: any
- App version: 2.3.3

## Describe the bug

As reported on Twitter, the displayed vaccination status can be changed to fully vaccinated by setting the system date two weeks ahead.

## Steps to reproduce the issue

See this thread:

https://twitter.com/mahrko/status/1404548472544575488

## Possible Fix

Adding a double check with an NTP server or the EN Framework itself would probably help.

---
Internal Tracking ID: [EXPOSUREAPP-7736](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7736)

**Comment by Ein-Tim** [comment] 2021-06-15 11:44
The vaccination certificate will still show invalid when it's scanned with CovPassCheck, won't it?

**Comment by thomasaugsten** [comment] 2021-06-15 11:49
This is correct. The App cannot prevent manipulation of the user like date change, patched app or a simple screenshot. It is mandatory to check the certificate with the covpass check app. You cannot check the validity of an certificate with a look on the app.

**Comment by Ein-Tim** [comment] 2021-06-15 15:22
@thomasaugsten CovPass can't be tricked by changing the system time, maybe an improvement for CWA should still be thought of.

**Comment by thomasaugsten** [comment] 2021-06-15 15:28
@thomasaugsten I cannot reproduce this. I can trick the CovPass the same way.

**Comment by Ein-Tim** [comment] 2021-06-19 10:31
@dsarkar 

Could we close this in favor of https://github.com/corona-warn-app/cwa-app-android/issues/3461 and move https://github.com/corona-warn-app/cwa-app-android/issues/3461 to the documentation repository?

**Comment by dsarkar** [comment] 2021-06-19 10:39
@pizuz Thanks for contributing here. We will close this issue as a duplicate. Please, continue any further discussion on the thread https://github.com/corona-warn-app/cwa-documentation/issues/642.

Best regards, DS 


---
Corona-Warn-App Open Source Team

**Closed** 2021-06-19 10:39 UTC
Labels: bug, duplicate, mirrored-to-jira
