### ISSUE TITLE
Scanning the vaccination QR code: import from the photo library

### ISSUE THREAD

**Issue by ouboub** [corona-warn-app/cwa-app-ios#2942] opened 2021-06-15 15:03 UTC
Hi
I have successfully imported the QR code provided by the Spanish government. However the QR code was sent as a pdf file, which I had to print and then to scan. It would be more convenient, to make a screenshot of the QR code, which is saved in the photo library and then import that QR. Could that be implemented please?

Uwe Brauer

**Comment by Ein-Tim** [comment] 2021-06-15 15:04
Related to: https://github.com/corona-warn-app/cwa-wishlist/issues/389.

**Comment by heinezen** [comment] 2021-06-17 11:05
@ouboub 

Thanks for the proposal. As @Ein-Tim said, we have already received the same feature request in https://github.com/corona-warn-app/cwa-wishlist/issues/389 on the general wishlist. You can find the current status and a workaround in the thread. For the sake of keeping the discussion in one place, I would suggest we continue any further discussion there.

I will therefore close your issue as a duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/389

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2021-06-17 11:05
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/389

**Closed by heinezen** 2021-06-17 11:05 UTC
Labels: enhancement
