### ISSUE TITLE
Showing changed region warning

### ISSUE THREAD

**Issue by oezguercelebi** [corona-warn-app/cwa-app-ios#698] opened 2020-06-17 21:14 UTC
My fiancé told me that she gets some warning she doesn’t understand it. Later I got the same warnings couple of times during the day. We get a warning that we changed our region and it might not be supported in this region. Which doesn’t make sense, because we live in Berlin/Charlottenburg and haven’t traveled for months. I use iPhone 11 Pro with the iOS version 13.5.1.

![image](https://user-images.githubusercontent.com/4594429/84950582-6b2cec80-b0ef-11ea-953b-6067068993aa.png)

**Comment by inf2381** [comment] 2020-06-17 21:35
Closing this as a duplicate of #645

**Closed by inf2381** 2020-06-17 21:35 UTC
