### ISSUE TITLE
App shows date in the future

### ISSUE THREAD

**Issue by pgtaboada** [corona-warn-app/cwa-app-ios#4040] opened 2022-01-05 10:54 UTC
- IPhone Pro 13
- iOS 15.2
- CWA 2.15.1(2)

## Describe the bug

Aktualisierungsdatum Risiko-Ermittlung: 3.7.22

## Steps to reproduce the issue

Cannot reproduce on other devices. 

![0475190B-32E5-4B07-AFB0-1240AFDD1D9F](https://user-images.githubusercontent.com/1474196/148206321-136aa6e5-4980-47e3-aaad-38bbdb02fd1b.png)

---
Internal Tracking ID: [EXPOSUREAPP-10253](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10253)

**Comment by Ein-Tim** [comment] 2022-01-05 11:05
Hi, did you change your system time to this date and then changed it back?

**Comment by pgtaboada** [comment] 2022-01-05 11:07
Nope - I did not touch my date settings. ;)

**Comment by Ein-Tim** [comment] 2022-01-05 11:08
Okay (-:
Restart of the device and the app was not successful to fix this, or?

**Comment by pgtaboada** [comment] 2022-01-05 11:13
Thats right. I did not uninstall as I do not want to loose my data. 

Daily checks are made. ;)

**Comment by Ein-Tim** [comment] 2022-01-05 11:18
Okay could you please post a screenshot of your iOS settings?

`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen`

Since when does the app show this?

**Comment by pgtaboada** [comment] 2022-01-05 16:48
Not sure since when, I first noticed it on the 14th december....

Should I attach ExposureChecks-2022-01-05.json as well?

![IMG_1198](https://user-images.githubusercontent.com/1474196/148255967-b0abae6b-1b89-4e7c-8c58-03dbff3d6dd4.PNG)

![IMG_1197](https://user-images.githubusercontent.com/1474196/148255978-92e15322-8b0b-491b-b09a-07a904b176cf.PNG)

**Comment by pgtaboada** [comment] 2022-01-05 17:15
Only this exposure check.
Every morning the app says it will perform check, never get error. 

[ExposureChecks-2022-01-05.json.txt](https://github.com/corona-warn-app/cwa-app-ios/files/7816574/ExposureChecks-2022-01-05.json.txt)

**Comment by pgtaboada** [comment] 2022-01-05 17:16
New device, migration ios2ios early in december.
Date alwas correct.

**Comment by pgtaboada** [comment] 2022-01-05 17:19
pretty sure it was migrated

**Comment by pgtaboada** [comment] 2022-01-05 17:19
delete exposure check?

**Comment by dsarkar** [comment] 2022-01-05 17:24
@pgtaboada ok, as a first guess I would point to the migration process ...

- delete exposure check -> please not yet.
- Do you have certificates imported and are you using your contact journal.
-  I'd suggest to make sure that you have all your certificates as printed document, or export them as pdf 
- The reason being, is that the app might not recover from this wrong date until it was reset.
- However, before reset or deleting exposer checks, we will get feedback from the dev team.

**Comment by Ein-Tim** [comment] 2022-01-05 17:26
@dsarkar 

I guess an error log would be helpful here, or?

**Comment by dsarkar** [comment] 2022-01-05 17:27
@pgtaboada @Ein-Tim Not sure if an error log will help much, however, @pgtaboada yes, start the logging until tomorrow past the moment when the risk check was performed.

**Comment by dsarkar** [comment] 2022-01-05 17:28
From past experience the app does not recover from such "time travel" ...

**Comment by pgtaboada** [comment] 2022-01-05 17:29
started error log recording...

**Comment by pgtaboada** [comment] 2022-01-05 17:31
why export as pdf - screenshot from QR codes should do the trick, don't?

**Comment by Ein-Tim** [comment] 2022-01-05 17:33
@pgtaboada 

Yes screenshot work too.

**Comment by dsarkar** [comment] 2022-01-05 17:33
Sure, but there is a nice PDF export function, you could than save the file nicely with other docs on ... PC, laptop, just in case. But indeed, screenshot should work.

**Comment by dsarkar** [comment] 2022-01-05 17:35
@pgtaboada Dev team is informed, we will discuss this further tomorrow!

**Comment by dsarkar** [comment] 2022-01-05 18:37
Internal Tracking ID: [EXPOSUREAPP-10253](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10253)

**Comment by dsarkar** [comment] 2022-01-05 18:38
Related or same:
https://github.com/corona-warn-app/cwa-app-android/issues/4303
https://github.com/corona-warn-app/cwa-app-android/issues/3629

**Comment by Ein-Tim** [comment] 2022-01-05 19:15
@dsarkar Should I try to reproduce this by setting my secondary device to a date in the future?

**Comment by pgtaboada** [comment] 2022-01-05 22:40
I am absolutely sure I never manually changed the date or how the date is setup on my phone. 
While the end result might be the same - how it happened will remain unknown. 
;)

**Comment by pgtaboada** [comment] 2022-01-06 15:33
[cwa-log.zip](https://github.com/corona-warn-app/cwa-app-ios/files/7822864/cwa-log.zip)

**Comment by dsarkar** [comment] 2022-01-06 16:02
Hi @pgtaboada I talked to a dev: I am afraid your app will not recover and resume normal operation until the date shown. This could be acceptable if it was one day or so, but in this case it is far from ideal. Most probably, either resetting the app or re-installing it will help in this case. If you do so, make sure that you have a backup of your certificates (paper, pdf, screenshot), and if applicable of your CWA contact journal. Also note, if you have registered a PCR or RAT test, it cannot be scanned again!

We have created a bug ticket, Internal Tracking ID: EXPOSUREAPP-10253, in order to change the behaviour of the app for such cases.

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment] 2022-02-11 15:39
@dsarkar I will make a test: Change the time of my phone to 2 days in the future, wait if/until a risk check was carried out and then switch the time back to the correct one. 

No worries, I won't do this on my productive device.

**Comment by Ein-Tim** [comment] 2022-02-11 15:47
As intended, the app does not carry out risk checks in the future but shows the following error pop up:
<img src="https://user-images.githubusercontent.com/67682506/153622816-250e9f1e-47b5-4623-91dd-5b4cbe644beb.jpeg" width="300">

**Comment by dsarkar** [comment] 2022-04-13 15:35
Not as far as I know. The pop-up should prevent such issues in general.

**Comment by Ein-Tim** [comment] 2022-04-13 15:44
@dsarkar Okay, thanks for the feedback! In this case, I suggest to close this issue.

**Comment by dsarkar** [comment] 2022-04-14 06:59
Good morning @pgtaboada, thanks again for reporting. This case seem to be an edge case, and we'd suggest to close this issue now. Should you experience this issue again, or any other issue, please reopen or open a new issue. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Closed by dsarkar** 2022-04-14 06:59 UTC
Labels: bug, mirrored-to-jira
