### ISSUE TITLE
Wiederkehrender Fehler 13 - case 5

### ISSUE THREAD

**Issue by christiane3012** [corona-warn-app/cwa-app-ios#2389] opened 2021-04-08 05:27 UTC
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11 Pro
- iOS version: 14.4
- App version: 1.15.2 (2)

## Describe the bug

Risikoermittlung nicht möglich. Wiederkehrender Fehler 13. 

## Additional context

Internal Tracking ID: [EXPOSUREAPP-5836](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5836)

**Comment by dsarkar** [comment] 2021-04-08 06:08
Hi @christiane3012,

Thank you for your report. We had a few similar reports already. 

Did  you recently scan a QR code. Other users reported the probem started shortly after having received a positive test result. Did something similar happen on the phone you are reporting the problem?

Thank you for your feedback, very much appreciated. Best wishes, DS 

---

**Comment by dsarkar** [comment] 2021-04-08 06:32
@christiane3012 See auch folgenden Kommentar: https://github.com/corona-warn-app/cwa-app-ios/issues/2387#issuecomment-815173737


> Danke das du diesen Bug gemeldet hast! Wir haben schon ähnliche Berichte in #2327, #2220 und #2316.
> 
> Um dieses Problem zu beheben, gehe bitte wie folgt vor:
> 
> Öffne die iOS Einstellungen
> Scrolle hinunter bis zu "Begegnungsmitteilungen"
> Klicke auf "Corona-Warn-App"
> Klicke nochmal auf "Corona-Warn-App"
> Scrolle runter und deaktiviere "Begegnungsinformationen teilen"
> Nach 24 Stunden kannst du die Option wieder aktivieren, danach sollte die App wieder funktionieren.
> 
> In der Zeit in der du "Begegnungsinformationen teilen" ausgeschaltet hast werden deine Kontakte nicht aufgezeichnet und dein Risiko wird nicht berechnet.
> Wenn du das nicht willst gib bescheid, es gibt noch andere Optionen, die aber manchmal nicht funktionieren.
> 
> Damit wir den Fehler analysieren können, wäre es perfekt wenn du den sog. EN-Log hier auf GitHub hochladen könntest (Anleitung siehe unten).
> 
> Teile uns bitte außerdem mit
> 
> deine iOS Version
> deine App Version
> ob du einen Test registriert hast
> ob dir irgendwelche anderen Fehler aufgefallen sind bevor der Fehler auftrat
> Anleitung zum exportieren von EN-Logs unter iOS 13.7 oder neuer

**Comment by dsarkar** [comment] 2021-04-08 06:57
Internal Tracking ID: [EXPOSUREAPP-5836](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5836)

**Comment by christiane3012** [comment] 2021-04-08 06:59
Hi dsarkar,

no, I didn‘t scan  a qr-code. If you Need any additional Information or logs just contact me.

Thanks !

:-)
Christiane

**Comment by dsarkar** [comment] 2021-04-08 07:01
@christiane3012 Thanks for the feedback! Yes, logs would be very much appreciated. If you could follow these steps  https://github.com/corona-warn-app/cwa-app-ios/issues/2389#issuecomment-815489008 and report back, that would be fantastic. Best wishes, DS

**Comment by christiane3012** [comment] 2021-04-08 07:09
Hope it helps !

Regards,

Christiane

**Comment by Ein-Tim** [comment] 2021-04-08 09:09
@dsarkar 

Should I open a new issue where we can communicate the findings from the devs and I (and other community members) can share their findings? I'm trying to reproduce this, test result added, etc. Didn't yet was able to. 

Also, we should think about centralizing this issue into one issue, we now have 5 open issues reg the same.

**Comment by dsarkar** [comment] 2021-04-08 09:22
@Ein-Tim OK, lets make a new issue with a summary/table, a good idea. Something like that: 
Case # / CWA v / iPhone / iOS / pos test result seemed to trigger issue (y/n) / ENF log provided / Workaround fixed issue?

**Comment by Ein-Tim** [comment] 2021-04-08 09:23
@dsarkar 

Will create ASAP.

**Comment by christiane3012** [comment] 2021-04-09 06:59
Workaround worked...

Thank you  !
🙂
Christiane

**Comment by christiane3012** [comment] 2021-04-09 07:05
App working After applying workaround.

**Comment by Ein-Tim** [comment] 2021-04-09 08:43
Nice to hear, thank you for your help @christiane3012!

Stay safe! 

@dsarkar 
I suggest to close this issue to focus on the unsolved cases, I'm quite sure they all have the same root cause.

**Comment by dsarkar** [comment] 2021-04-10 11:49
@Ein-Tim @christiane3012 OK, thanks for the feedback!. We are closing this issue now. Should you have more trouble regarding Error 13 please re-open this issue. Best wishes, DS

**Comment by dsarkar** [comment] 2021-05-03 13:32
Hi @christiane3012 Can you confirm that also with release 2.1 you have not experiences ndy issue with 'Fehler 13'. Feedback is very much appreciated. Thank you, DS

---
Corona-Warn-App Open Source Team

**Comment by christiane3012** [comment] 2021-05-03 14:50
Hallo @dsarkar, no, 'Fehler 13' did not show up until now, but I updated only one hour ago to release 2.1.
I'll let you know, if the problem reoccurs. 
Kind regards,
Christiane

**Comment by dsarkar** [comment] 2021-05-04 07:02
@jane1973 Vielen Dank für das Feedback. Viele Grüsse, DS 


---
Corona-Warn-App Open Source Team

**Closed** 2021-05-04 07:03 UTC
Labels: Fix 2.1, bug, mirrored-to-jira
