### ISSUE TITLE
Risk detection shows wrong number of active days

### ISSUE THREAD

**Issue by songbird82** [corona-warn-app/cwa-app-ios#1696] opened 2020-12-16 11:23 UTC
## Technical details

- Device name: iPhone 12
- iOS Version: 14.3
- App Version:1.7.1

## Describe the bug

I switched to a new phone 16 days ago. Since then the risk detection was active for every single day (since November 30th). But the app says "Risiko-Ermittlung war für 11 der letzten 14 Tage aktiv". It switched to "Risiko-Ermittlung war für 12 der letzten 14 Tage aktiv" some days ago, but since then it shows "Risiko-Ermittlung war für 11 der letzten 14 Tage aktiv" every day.

## Steps to reproduce the issue

1. Open the app

## Expected behaviour

After opening the app it should show "Risiko-Ermittlung dauerhaft aktiv"

---

## Related Issues
- https://github.com/corona-warn-app/cwa-app-ios/issues/1127.
- https://github.com/corona-warn-app/cwa-documentation/issues/412
- https://github.com/corona-warn-app/cwa-wishlist/issues/102
---
Internal Tracking ID: [EXPOSUREAPP-2556](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2556)

**Comment by Ein-Tim** [comment] 2020-12-16 11:44
Please also see #1127

**Comment by dsarkar** [comment] 2020-12-16 13:10
Dear @songbird82,

Thank you for your contribution. As @Ein-Tim points out we have created a ticket for the bug in the internal Jira system and any further developments will be notified in this Github issue: https://github.com/corona-warn-app/cwa-app-ios/issues/1127. Please monitor that issue and contribute there. Many thanks.
  
Best wishes,
DS

---

## Related Issues
- https://github.com/corona-warn-app/cwa-app-ios/issues/1127
- https://github.com/corona-warn-app/cwa-documentation/issues/412
- https://github.com/corona-warn-app/cwa-wishlist/issues/102
---
Internal Tracking ID: [EXPOSUREAPP-2556](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2556)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-12-16 13:10
Duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/1127

**Comment by songbird82** [comment] 2020-12-16 13:11
Thanks for the feedback, I will check the mentioned issue

**Closed** 2020-12-16 13:17 UTC
Labels: bug, duplicate
