### ISSUE TITLE
iOS 14.2 Public Beta 2: error EN-Code 2

### ISSUE THREAD

**Issue by MichaelScherf** [corona-warn-app/cwa-app-ios#1392] opened 2020-10-22 12:44 UTC
Since days I got error message EN-Code 2, even after 3 app updates from the apple App Store.

I’m using iOS 14.2 Public beta 2, iPhone 11

![F262B19C-0B62-48CF-9926-0B44A2AE9A61](https://user-images.githubusercontent.com/36472858/96873264-04408b00-1475-11eb-900d-5fb3b06e5f5c.png)

**Comment by dsarkar** [comment] 2020-10-22 13:23
Dear @MichaelScherf 


Thank you for your contribution. This issue has been raised previously and has been fixed in iOS 14.2 Beta 4, see here: https://github.com/corona-warn-app/cwa-app-ios/issues/1339#issuecomment-713407878 . Please update to the latest iOS release.

I will close this issue as a duplicate and I would like to ask you to continue any further discussion in the main issue thread https://github.com/corona-warn-app/cwa-app-ios/issues/1339 .

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-10-22 13:23
Duplicate of  https://github.com/corona-warn-app/cwa-app-ios/issues/1339

**Closed by dsarkar** 2020-10-22 13:23 UTC
Labels: bug
