### ISSUE TITLE
Corona Warn App doesn’t work after iOS is restored from Backup

### ISSUE THREAD

**Issue by tibor** [corona-warn-app/cwa-app-ios#1014] opened 2020-08-06 11:15 UTC
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

When switching your iPhone and installing the Corona Warn App from an iOS backup, the App is stuck in an endless loop at the onboarding stage, probably because the permissions like notifications and so on are already activated via the backup.

## Expected behaviour

The app should work as on the old iPhone.

## Steps to reproduce the issue

1. Install Corona Warn App
2. Make an iOS Backup
3. Restore iPhone from iOS Backup
4. Open Corona Warn App

## Technical details

- iOS Version: 13.6
- Device: iPhone 11 Pro

**Comment by tibor** [comment] 2020-08-06 11:17
![ezgif-2-fb0a06085fdf](https://user-images.githubusercontent.com/3136416/89525850-1e0ff180-d7e7-11ea-9d26-de9822cd0879.gif)

**Comment by Ein-Tim** [comment] 2020-08-06 11:19
Duplicate of closed issue #896. 
Please follow up in #754.

**Comment by SonaliDK** [comment] 2020-08-06 11:46
@tibor Thanks for your report. As @Ein-Tim mentioned this one is a duplicate. Please also refer to the FAQ : https://www.coronawarn.app/en/faq/#migration_Apple.

Best regards,
SD
Your Corona Warn-App Open Source Team

**Closed** 2020-08-06 11:46 UTC
Labels: bug, duplicate
