### ISSUE TITLE
App Version 1.9.1: App does not show any risk contacts, while the log on iOS shows 1.

### ISSUE THREAD

**Issue by AnOtherMuenchner** [corona-warn-app/cwa-app-ios#1705] opened 2020-12-16 19:13 UTC
Recently I update to version 1.9.1. of the app. Since the update, my "current" risk contact is gone. The app shows "no risk contacts", while in the log on iOS I can see still one contact.

Shorly before the update, the old version (1.7.1) of the app updated the risk contact. This version showed "one uncritical risk contact".

**Comment by Ein-Tim** [comment] 2020-12-16 19:16
Duplicate of #1703

**Closed** 2020-12-16 21:31 UTC
Labels: bug

**Comment by dsarkar** [comment] 2020-12-17 05:47
Dear @AnOtherMuenchner ,

Thank you for your report. This issue was close since it is a duplicate and is not a bug. Please monitor and if necessary contribute here: #1703.  

Best wishes, DS

---
Corona-Warn-App Open Source Team
