### ISSUE TITLE
Updates on past encounters after deactivating corona warn app due to travel to different country

### ISSUE THREAD

**Issue by seb-ast-ian** [corona-warn-app/cwa-app-ios#1430] opened 2020-10-29 20:55 UTC
I just traveled overseas and had to change from corona warn app to a local one. I understand that corona warn app can't register new encounters anymore.

However it should be possible to update me for the next two weeks if any of my past encounters in Germany turned out to have been infected. Can this be added?

---
Internal Tracking ID: EXPOSUREAPP-2888

**Comment by dsarkar** [comment] 2020-10-30 09:49
Dear @seb-ast-ian,

Thank you for your post.

I understand that you are now back in Germany now.
Did you re-select Corona-Warn-App?
Settings --> Exposure Notifications --> Active Region --> Corona-Warn-App
Since your operating system takes a rolling 14 days log of your encounters as long you use a corona application, I understand that the CWA still is able to match the risk encounters in retrospective. 
 
In general, if you travel within Europe, there is already an interoperrability partially implemented.
Here is a list of currently participating countries.
https://www.coronawarn.app/en/faq/#interoperability_countries

Best regards,
DS

Corona-Warn-App Open Source Team

**Comment by seb-ast-ian** [comment] 2020-10-31 21:33
Hi @dsarkar,

No, I am not back in Germany yet, I am in America right now. However I may potentially have encountered someone who was infected, who uses the Corona-Warn-App and who has just now received their positive test result. And I think, in this case I would not be notified about this encounter, as the corona-warn-app does not seem to update for past encounter.

I can't reselect Corona-Warn-App now, as I would have to disconnect from my current local American similar app.

I am not familiar with the encounter protocol and I read that these apps can't be active simultaneously. So there might be no solution to this.

Cheers,
seb-ast-ian

**Comment by dsarkar** [comment] 2020-11-05 10:54
Hi @seb-ast-ian,

Thanks again. There have been suggestions to switch forth and back between two different corona warn applications on the same day. However, we will raise this issue with the developers, in order to figure out how this will affect the functionality of the apps. We will come back with any new information on this issue. 

In the meantime, have a look also here:
https://github.com/corona-warn-app/cwa-wishlist/issues/62
https://github.com/corona-warn-app/cwa-app-ios/issues/708
https://github.com/corona-warn-app/cwa-backlog/issues/14

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-11-23 10:47
Dear @seb-ast-ian,

Regarding: Using two different Corona warn apps.

We have been raising this issue with the developers and can confirm the following expected behavior: 

Question: Can I switch between two active regions, i.e. two different CWAs, without missing risk encounters, assuming I switch once per day, or once every two days, e.g.? 
  
Facts: 
- It is possible to install two (or more) Corona warn apps from different countries on the same phone 
- Only one app at a time can access the iOS exposure logging. This is also shown in OS settings -> Exposure Notifications -> Active Region  (e.g. Corona-Warn-App / Deutschland) 
 
Example:  
- Assume e.g. a person p1 traveling overseas or to a European country not yet participating in transnational exposure logging, e.g. lives in Germany and uses German-CWA. 
- Then p1 spends a week in the USA, installs USA-CWA, and activates region 'USA'.
- Assume he uses day 1 the USA-CWA (and uses the active region 'USA'), then on day 2 he activates German-CWA and uses the active region 'Germany'.  
- In the meantime a positive test result QR code was registered in Germany by person p2, uploaded, and p2 had been in contact with person p1 a few days before traveling.  

Will this encounter be shown when he re-activates the German-CWA and German region? Yes, as long all happens within a 14-day time frame.


If this answers your question satisfactorily, please close this issue.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-11-25 11:00
Dear @seb-ast-ian, dear community,

Thanks again for contributing. I will close this issue now. Feel free to re-open, if more questions come up or furtur discussion on this topic is necessary.


Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Closed by dsarkar** 2020-11-25 11:00 UTC
Labels: enhancement, mirrored-to-jira
