### ISSUE TITLE
UI inaccuracy - exposure notification wording - possible improvement

### ISSUE THREAD

**Issue by Poeggi** [corona-warn-app/cwa-app-ios#1507] opened 2020-11-13 07:45 UTC
With no encounter/exposure in last few days, my exposure statement changed from "x exposure[s] with low risk" to "No exposures up to now".

I might be nit-picking here, but the "up to now" seems incorrect, given that I have been exposed earlier.

I would expect the app's UI to be more accurate, and state "No exposures for the last n days", where n is the number of days deemed siginificant for overall risk calculation, or maybe even the days since actual last exposure, which would be even more transparent.

Furthermore, it would be great that in case of exposure, the UI states how many days in the past the last exposure happened.
E.g. something like ".. x exposure[s] with low risk, last exposure m days ago." where m is the time since last exposure.

No specific steps arte needed to reproduce the issue.

A screenshot attached to show the current UI:

![exposure](https://user-images.githubusercontent.com/48416618/99041983-3339b080-258c-11eb-8985-16e735cce6cc.jpg)

**Comment by dsarkar** [comment] 2020-11-13 11:20
Dear @Poeggi,

Thank you for your post. The last time you have been the notification "x exposure[s] with low risk", was x = 14? A possible and simple explanation is that your encounters fall outside the 14-day window.

Also, please provide the following information:
- iPhone ... 
- iOS ...
- Corona-Warn-App Version ...
- Upload ENF file.

Thanks! Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment] 2020-11-13 12:49
This Issue is already tracked [here](https://github.com/corona-warn-app/cwa-documentation/issues/430) @Poeggi, so maybe close this Issue and follow up there with your suggestion. 
Thanks and have a nice weekend

**Comment by dsarkar** [comment] 2020-11-16 07:38
Dear @Poeggi,

As @Ein-Tim mentioned, this seems a duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/430, and as suggested, please post your issue there.

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment] 2020-11-20 05:58
@dsarkar 
I think we can close this 🤷🏻‍♂️

**Comment by dsarkar** [comment] 2020-11-20 08:55
Duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/430

**Closed by dsarkar** 2020-11-20 08:55 UTC
Labels: bug, duplicate, further input needed
