### ISSUE TITLE
Corona-Warn-App does not open the certificate if the notification "Überprüfen Sie die Gültigkeit Ihrer Zertifikate" is clicked while the app is in foreground

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-ios#3772] opened 2021-10-29 17:21 UTC
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s
- iOS version: 15.0.1
- App version: 2.12.1

## Describe the bug

If the app is in the foreground and the user clicks on the "Überprüfen Sie die Gültigkeit Ihrer Zertifikate." notification, nothing happens.

EDITED BY Corona-Warn-App Open Source Team

## Steps to reproduce the issue

1. Add a certificate which either will expire soon or which signature will soon get invalid
2. Get the "Überprüfen Sie die Gültigkeit Ihrer Zertifikate" notification from the CWA
3. Open the Corona-Warn-App and navigate to the "Zertifikate" tab
4. Click on the notification from the CWA
5. See that nothing happens

## Expected behaviour

Normally the certificate which the notification was send for is opened. 

## Additional context

EDITED BY Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2021-10-30 10:13
@Ein-Tim Please, use a different certificate with a different name. Thanks.

**Comment by Ein-Tim** [comment] 2021-10-30 10:23
@dsarkar 

Agreed, I'm sorry.

I cannot provide a new video as I did click on all notifications, so I will just leave the video out.

**Comment by dsarkar** [comment] 2021-10-30 10:31
@Ein-Tim I understand, no problem. I suggest closing this one and create a new "clean" issue. Thanks! Enjoy your weekend!

**Closed by dsarkar** 2021-10-30 10:31 UTC
Labels: bug

**Comment by jucktnich** [comment] 2021-10-30 12:11
@dsarkar what should you do in case you don't know if the content is appropriate like in this case?
Just creating the issue and waiting for corrections, write the content to an email address, ...?
Maybe you could append the Code of Conduct with the intended behaviour?

**Comment by Ein-Tim** [comment] 2022-07-31 11:02
Just to follow up: This bug was meanwhile fixed.
