### ISSUE TITLE
Critical Bug after device change on iOS

### ISSUE THREAD

**Issue by allagainstcorona** [corona-warn-app/cwa-app-ios#1240] opened 2020-09-25 10:26 UTC
Corona Warn App stop working after you change your iOS device.

I had changed from my iPhone 7 iOS 14.0 to an iPhone XR iOS 14.0 with the bluetooth functionality which is provided from apple.

When I run the C-W-A the app show the configuration again, but ends in an loop and i have to reintall the app again. 

Users, who are not looking daily in the app and know that they had to reinstall the app they will get no informations. Contacts from the last two weeks will be lost too.

## Technical details

- iOS Version: 14.0
- Device: iPhone 7 => iPhone XR

## Additional context

Aber die App stürzt ab, wenn man bei iOS das Endgerät wechselt und die dafür bereitgestellten Tools von Apple nutzt.

**Comment by Ein-Tim** [comment] 2020-09-25 10:32
Duplicate of: https://github.com/corona-warn-app/cwa-app-ios/issues/754
See also the FAQ: https://www.coronawarn.app/en/faq/?search=Backup#migration_Apple

**Closed** 2020-09-25 10:40 UTC
Labels: bug

**Comment by abro1i** [comment] 2020-09-25 12:04
Duplicate of #754
