### ISSUE TITLE
App does not start at all. Only a white/black screen. Incident since 19th February.

### ISSUE THREAD

**Issue by Jan-Walter** [corona-warn-app/cwa-app-ios#2046] opened 2021-02-20 11:21 UTC
Solve issue: 
---
**EN** https://www.coronawarn.app/en/faq/#ios_black_screen
**DE** https://www.coronawarn.app/de/faq/#ios_black_screen

Original post
---

## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11 ProMax
- iOS Version: 14.4
- App Version: 1.12.1

## Describe the bug

App does not start at all. Only a white screen. Incident since 19th February. 

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-5265](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5265)

**Comment by Ein-Tim** [comment] 2021-02-20 11:26
Hey @Jan-Walter 

Could you please provide


- iOS Version
- App Version
- Device Name

Thanks!

**Comment by Ein-Tim** [comment] 2021-02-20 12:44
Thanks for providing the information. 
What does the screen "Begegnungsmitteilungen" in the iOS Settings show? Could you maybe provide a screenshot? 

Did you already restart your device?

**Comment by dsarkar** [comment] 2021-02-20 17:21
@Ein-Tim 

Dear @Jan-Walter,
Thank you for reporting here. Please provide the information as requested by @Ein-Tim. Additionally:
- Are you aware of an update, e.g. did you do an update of the app on the same day?
- Did you update the iOS on the given day?

Many thanks, Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2021-02-20 17:24
Internal Tracking ID: [EXPOSUREAPP-5265](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5265)

**Comment by dsarkar** [comment] 2021-02-20 17:28
@Jan-Walter 
Could you try this, please:
https://www.coronawarn.app/en/faq/#ios_black_screen
https://www.coronawarn.app/de/faq/#ios_black_screen

**Comment by Ein-Tim** [comment] 2021-02-20 17:37
Is the white screen shown in the App or in the iOS settings? 
If it's shown in the settings, definitely do what @dsarkar said.

**Comment by Jan-Walter** [comment] 2021-02-20 18:23
![image](https://user-images.githubusercontent.com/75166489/108604881-d2065200-73b0-11eb-8edc-a564d7ade9f3.jpeg)
White Screen appears when opening the app and in settings.
Restart of device did not help. No update currently available in AppStore or iOS settings.

**Comment by Ein-Tim** [comment] 2021-02-20 18:24
Okay, thanks @Jan-Walter 

Please try what @dsarkar said:

> Could you try this, please:
https://www.coronawarn.app/en/faq/#ios_black_screen
https://www.coronawarn.app/de/faq/#ios_black_screen

**Comment by BerkeAras** [comment] 2021-02-22 08:34
At iOS 14.4 I cannot reproduce this issue. The App works perfect.

**Comment by dsarkar** [comment] 2021-02-22 09:32
@BerkeAras Thanks for your feedback.

**Comment by dsarkar** [comment] 2021-02-22 09:34
@Jan-Walter any news, did you try this: 

https://www.coronawarn.app/en/faq/#ios_black_screen
https://www.coronawarn.app/de/faq/#ios_black_screen

Feedback very much appreciated. Best, DS

---
Corona-Warn-App Open Source Team

**Comment by caludai** [comment] 2021-02-23 12:31
> @Jan-Walter any news, did you try this?
> 
> https://www.coronawarn.app/en/faq/#ios_black_screen
> https://www.coronawarn.app/de/faq/#ios_black_screen
> 
> Feedback very much appreciated. Best, DS
> 
> Corona-Warn-App Open Source Team

I've tried as I experience the same issue since some days. IOS 14.4, IPhone SE 2nd generation and latest Version of the App. I've performed the reset of Location and Privacy but still I just see a white screen if I open the App.

**Comment by dsarkar** [comment] 2021-02-23 12:43
@caludai Thank you very much for reporting. Your case will be forwarded to the developers. You use CWA 1.12 and can you also confirm that the issue started with the update or do you think it is not related to the update to version 1.12 ?

**Comment by thomasaugsten** [comment] 2021-02-23 13:11
@caludai  @Jan-Walter When do you update on iOS 14?
Deleting the App and reinstalling the app?
Install a different covid app like the SwissCovid?

**Comment by caludai** [comment] 2021-02-23 14:39
@dsarkar I think it did but I can't confirm 100%. I used the App a week ago an it worked. I've updated an opened it one or two days later, so I guess it is related.

**Comment by caludai** [comment] 2021-02-23 15:01
@dsarkar @thomasaugsten It's fixed. The problem was the "Exposure Notifications" was not available. Restarting the phone did the trick. The SwissCovid App showed me where to look. Sorry for the inconvenience but I hope it gives some insight that the "Exposure Notifications" can crash somehow.

**Comment by Ein-Tim** [comment] 2021-02-23 15:08
@caludai Did the app prompt you in-app to do so or is there a FAQ entry you could share with us? 😀

**Comment by dsarkar** [comment] 2021-02-24 08:30
@caludai Thanks for the feedback! Very much appreciated.

@Jan-Walter Please, see comments https://github.com/corona-warn-app/cwa-app-ios/issues/2046#issuecomment-784192593 and https://github.com/corona-warn-app/cwa-app-ios/issues/2046#issuecomment-784263849. Did you do an iOS update recently and/or CWA update? If so, try restarting the phone and if this doesn't solve it, try in combination with this https://www.coronawarn.app/de/faq/#ios_black_screen, please. We would appreciate your feedback here. Thanks.

**Comment by dsarkar** [comment] 2021-03-03 08:23
@Jan-Walter Any news, did the problem disappear, and if so, could you give us some feedback? Many thanks. DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment] 2021-03-09 06:40
Any updates here @Jan-Walter? 

Do you still have this issue? Or is it solved?

**Comment by Ein-Tim** [comment] 2021-03-28 10:26
If there's no further input here I suggest to close this issue.

**Comment by heinezen** [comment] 2021-03-28 11:43
@Ein-Tim We were still getting reports for this in the App Store and Play Store, so we will leave the issue open.

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment] 2021-06-20 13:58
Dear community,

we assume this bug was caused by a previous iOS update. Apple has fixed the beaviour by now. If you have previously encountered this error, please update iOS to the current version. If you still encounter the error then, please report back here on Github.

----
Corona-Warn-App Open Source Team

**Closed by heinezen** 2021-06-20 13:58 UTC
Labels: bug, mirrored-to-jira
