### ISSUE TITLE
App will not open when using iOS 14 

### ISSUE THREAD

**Issue by gitbodi** [corona-warn-app/cwa-app-ios#765] opened 2020-06-24 11:10 UTC
## Avoid duplicates

* [ x ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ x ] Bug is not already reported in another issue

## Describe the bug
When running iOS 14 on an  device the app will open with a black screen and remain that way. 

## Technical details

- iOS Version: 14 Developer Beta
- Device: iPhone 11 Pro

**Comment by F3000** [comment] 2020-06-24 11:24
Discussed in other tickets . The Apple API doesent work in Beta yet

**Comment by n-thumann** [comment] 2020-06-24 11:24
Duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/749 😊

**Comment by gitbodi** [comment] 2020-06-24 11:24
Sry for double opening

**Closed** 2020-06-24 11:24 UTC
Labels: bug
