### ISSUE TITLE
wrong URL shared?

### ISSUE THREAD

**Issue by Finkes** [corona-warn-app/cwa-app-ios#627] opened 2020-06-16 06:27 UTC
## Describe the bug

When I share the link to the app using the "share link" feature inside the iOS app, the URL seems to be wrong or not working: https://www.corona-warn-app.de/.

## Expected behaviour

I would expexct the following URL instead:
https://www.coronawarn.app/de/

## Steps to reproduce the issue

1. open ios app
2. click on "Corona-Warn-App" teilen
3. click omn "Download-Link versenden"
4. Share e.g. via whatsapp to a friend
5. the URL https://www.corona-warn-app.de/ will be used

![image](https://user-images.githubusercontent.com/6247179/84738722-b5588580-afaa-11ea-9f70-f1a70435a9a8.png)

![image](https://user-images.githubusercontent.com/6247179/84738826-dde07f80-afaa-11ea-874e-9a9c9907a8d5.png)

## Technical details

iOS

## Possible Fix

change the URL or make the website available again?

**Comment by tens0rfl0w** [comment] 2020-06-16 06:42
Duplicate of #625 

Seems like that this is an URL to be used to link to the app store sites.

**Closed** 2020-06-16 06:43 UTC
Labels: bug

**Comment by Shegox** [comment] 2020-06-16 06:47
FYI: 
For someone from SAP seeing that issue. Currently the url `corona-warn-app.de` is on a denylist on the corporate network and thus throwing the certificate mismatch error, due to DNS injection of an error page. I opened already a ticket internally to get that resolved.
