### ISSUE TITLE
Something went wrong... error when launching the app

### ISSUE THREAD

**Issue by TuTu800** [corona-warn-app/cwa-app-ios#787] opened 2020-06-26 09:42 UTC
Dear, 

When I launched the app, I got the following error: 
ENErrorDomain error 13.

The app last update is 24/06/2020. 

Any idea of what went wrong?

Thanks

**Comment by tkowark** [comment] 2020-06-26 10:47
Duplicate of #759 , please find more information about the issue there.

**Closed by tkowark** 2020-06-26 10:47 UTC
Labels: bug
