### ISSUE TITLE
Fehlerhafte Zählung der aktiven Tage

### ISSUE THREAD

**Issue by MichaelElbflorenz** [corona-warn-app/cwa-app-ios#804] opened 2020-06-30 08:32 UTC
Es erfolgte keine Neuinstallation oder Löschung der Daten. Trotzdem folgt auf Tag 13/14 der Tag 6/14.
![8063E828-067F-4806-823F-52BBA4754BA3](https://user-images.githubusercontent.com/67629866/86103398-ff6a5c80-babc-11ea-9bb4-5e0eec074e96.jpeg)

## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Technical details

- iOS Version:
- Device:

**Comment by haosap** [comment] 2020-06-30 09:47
Hi @MichaelElbflorenz ,
Thanks for reporting this bug. In order to find out the root cause reason, I would like to know more detail from you, for example, have you ever deactivate the "Risiko-Ermittlung"? Thanks.

**Comment by Skibbe69** [comment] 2020-06-30 10:23
Hi @MichaelElbflorenz, @haosap and @ChristianKienle, I have exactly the same behavoir.
- Installed on 16/06/2020
- 29/07/2020 App said „13 von 14 Tagen aktiv“
- 30/07/2020 App says „6 von 14 Tagen aktiv“ „Aktualisiert: Gestern, 21:00“
- no re-installation and never deactivated „Risiko-Ermittlung“
BR

**Comment by tillnagel** [comment] 2020-06-30 10:25
Similar here, my app showed "14 of 14 days saved", but now suddenly "2 of 14 days saved". It also showed an error message a couple of times (since today), stating "Something went wrong. The operation couldn't be completed. (ENErrorDomain error 11.)"

No deactivating in between.

![corona-app-error](https://user-images.githubusercontent.com/908847/86115831-c2a66180-bacc-11ea-9207-37c7dc2dd398.jpg)

**Comment by MichaelElbflorenz** [comment] 2020-06-30 10:37
@haosap it fully matches the description of @Skibbe69. No new installation, never disabled "risk detection", no error message or similar. So far the app has worked without problems.

**Comment by Skibbe69** [comment] 2020-06-30 10:42
Just checked the App again, now it says: „7 von 14 Tagen aktiv“

**Comment by solstice** [comment] 2020-06-30 11:14
I see the same bug. "X of 14 days saved" counted up until X=13, now it says "7 of 14 days saved.

I have not disabled the logging, my only interaction with the app was to open it about once a day to see whether it got updated.

iPhone 7
iOS 13.5.1

**Comment by tyrann0us** [comment] 2020-06-30 12:21
I can confirm this and made a short screencast to show how the counter jumps from "14" to a random (?) number after the app has been completely closed and reopened.


![804](https://user-images.githubusercontent.com/8144115/86125355-d0fc7980-badc-11ea-8803-d4b943892cea.gif)

**Comment by CJHarms** [comment] 2020-06-30 12:27
Same Issue for me. Never uninstalled/removed the App and never deactivated the Risk Detection Toggle. Went from 14 Days down to 7 Days now.

iPhone X / iOS 13.5.1

**Comment by ChristianKienle** [comment] 2020-06-30 12:46
Bug fixed - tests written - PR opened (#807 – still in draft to iron out the rough edges).

**Comment by bufemc** [comment] 2020-06-30 16:42
Same or similar bug happened here: first it showed 14 days.. after clicking the update button it was only 10..

![image](https://user-images.githubusercontent.com/18305092/86153037-5560f380-bb01-11ea-97b1-c47b739ecc18.png)

![image](https://user-images.githubusercontent.com/18305092/86153102-690c5a00-bb01-11ea-99fb-b2e39b3ac743.png)

**Comment by jatty** [comment] 2020-06-30 18:41
Same here. This morning i had 14/14, some hours later only 9/14.

**Comment by thrak23** [comment] 2020-06-30 19:44
![3110E38C-3454-4DB2-AE8B-16BAF62B78BC](https://user-images.githubusercontent.com/67418052/86170028-d2e52d80-bb1a-11ea-9a90-482276dd2d8d.jpeg)
Same here. 14/14 to 0/14

**Comment by cfritzsche** [comment] 2020-07-01 05:50
![8F8A803A-FD51-4B8E-A17F-D13DBD5EDD79](https://user-images.githubusercontent.com/1367701/86207631-3ef18100-bb6f-11ea-957c-daee8685d8db.jpeg)

I have not seen this example reported anywhere yet. Since this morning it consistently shows 15/14 days so not sure if it’s deleting the 15th day (the Launch Tuesday) correctly or it’s just a display issue. Should I create a new issue?

**Comment by haosap** [comment] 2020-07-01 06:57
Dear app users,
The hot fix is available at App Store now. Please update your app.
Thank you very much for your support.

**Comment by cfritzsche** [comment] 2020-07-01 06:59
Thanks that fixed it. 14/14 now.

**Comment by tyrann0us** [comment] 2020-07-01 07:06
For me, it says 12/14. I'm not sure what the expected behavior is: Jump to the number before the bug occurred (that seems the case for @cfritzsche) or stay with the "reduced" number and count it up (happens for me).

**Comment by jwildeboer** [comment] 2020-07-01 07:11
In my case it still says 0/14 days, Risk unknown. I’ve restarted the app after update. ![image](https://user-images.githubusercontent.com/873028/86213937-c2fd3600-bb7a-11ea-8e1a-55efa66f910b.jpeg) ![image](https://user-images.githubusercontent.com/873028/86213957-ca244400-bb7a-11ea-9ccf-52dfe15f81aa.jpeg)

**Comment by tillnagel** [comment] 2020-07-01 07:33
> The hot fix is available at App Store now. Please update your app.

Side note: For me, the update is not shown in the "Available Updates" list but only via the detail page of the app.

**Comment by tillnagel** [comment] 2020-07-01 07:35
After updating, same behavior as @tyrann0us reports: Still showing "3 of 14 days".

**Comment by haosap** [comment] 2020-07-01 07:53
Hi @tillnagel ,
the update is not able to fix counters that jumped back to 7 days (or any other values), but will only prevent that from happening in the future. Your contact events are, however, **NOT** affected by that, since they are not stored by the app but the exposure notification framework. cc @tkowark

**Comment by tillnagel** [comment] 2020-07-01 08:02
Thanks @haosap for the clarification. Is it the same for people not updating the app, i.e. it only ever was a display bug and never affected the contact event behavior?

**Comment by haosap** [comment] 2020-07-01 08:29
> Thanks @haosap for the clarification. Is it the same for people not updating the app, i.e. it only ever was a display bug and never affected the contact event behavior?

Hi @tillnagel ,
I think, if the user doesn't update the app. The side effect is, the trancing days (only number) will be pruned. Therefore, some strange number was shown instead of the correct one. It does NOT affect the risk level calculation, but it really confuses users. So we highly recommend users to update their apps. Thanks.

**Comment by Ein-Tim** [comment] 2020-07-01 08:35
Same issue for me.
After I updated to the new version the Number of Active Days went down from 13 to 11. (I don’t even know why I didn’t reached the 14 days, I installed the App on the launch day and never deactivated “Risiko-Ermittlung”)
So, for me, the new update didn’t fixed the error. 


iPhone XR/iOS 13.6 Public Beta 2

**Comment by jwildeboer** [comment] 2020-07-01 10:02
Ok. Seems I was just not patient enough. Though I “lost” the 14 days, everything is back to normal now and risk calculation is working again after updating to 1.0.3. 

Thank you, team, for identifying the bug, fixing it and distributing the updated app in less than 24 hours! This is truly inspiring!

![image](https://user-images.githubusercontent.com/873028/86231324-ac62d900-bb92-11ea-8f86-f59891ecdfce.jpeg)

**Comment by ferdinand** [comment] 2020-07-01 11:04
Indeed great work!

One little remark: I second https://github.com/corona-warn-app/cwa-app-android/issues/701, users should be informed in the App Store version history about what has changed with the update.

**Comment by gkgg** [comment] 2020-07-04 11:26
For me (using iOS 13.5.1 on an iPhone SE 2), things seemed to work fine in version 1.0.2 of the app. The (original) issue discussed here (or at least something that looks like it) was actually introduced to me by/after installing the update to version 1.0.3.
After the update had been installed, the counter had been set back to 9/14, not changing even after the >24 hours timeframe (automatic background processing worked so far).
The issue persist after installing the update to version 1.0.4, again unchanged after the >24 hours timeframe.

**Comment by c-hoeger** [comment] 2020-07-07 08:04
I am stuck at 13 of 14 days on iOS. I installed the app on the same day it was released (3 weeks ago).

**Comment by Ein-Tim** [comment] 2020-07-07 08:05
> I am stuck at 13 of 14 days on iOS. I installed the app on the same day it was released (3 weeks ago).


https://github.com/corona-warn-app/cwa-app-android/issues/796

**Comment by maku1303** [comment] 2020-07-07 14:27
Same here 13 of 14 days, for 5 days now :-(

Iphone 8S iOS 13.5.1

**Comment by Git2077** [comment] 2020-07-08 08:25
Same here! 
iOS 13.5.1, App v1.0.4 (0)

**Comment by slage16** [comment] 2020-07-11 19:30
I updated the app yesterday morning before the app has synchronized and installed the app on 16.06.2020. I still have the problem with counting the days. 
Like mentioned yesterday in issue #888

![9F004160-A8AF-4D27-9B63-811F2C717A44](https://user-images.githubusercontent.com/42173759/87232154-224e1800-c3bd-11ea-81da-2b416584e567.png)
![5FCB0934-3A94-4530-B1BD-51D9BBDEBE37](https://user-images.githubusercontent.com/42173759/87232158-25e19f00-c3bd-11ea-80e9-9f5ef6f76ced.jpeg)
![889B1187-33D6-47AE-9A69-644500BB29D3](https://user-images.githubusercontent.com/42173759/87232159-267a3580-c3bd-11ea-9fa1-2685403dab02.jpeg)

**Comment by gkgg** [comment] 2020-07-12 06:54
[update] After installing the update to v1.0.5 followed by the one to v1.0.6 later the same day (07/10/20), the active days indicator only changed once (from 9/14 to 10/14, over night after installing the updates).

As I didn't change the way I am using my phone and all looked well in v1.0.2, I cannot tell what caused the appearance of that stuck(?) counter after updating to v1.0.3 (which might as well be more of a correlation than a causation). 
All I can tell is that v1.0.2 seemed to work well as far as this indicator issue is concerned, and that none of the updates, including v1.0.6, seemed to solve the underlying problem for my system/phone.

![image](https://user-images.githubusercontent.com/67552666/87240825-46414600-c41d-11ea-8306-fcf8ef1886f4.jpeg)
![image](https://user-images.githubusercontent.com/67552666/87240828-4e00ea80-c41d-11ea-8dd2-b479d3672320.jpeg)

**Comment by FarahElI** [comment] 2020-07-12 15:14
I have the same issue. It shows that I have 13 of 14 days saved for several days even after the daily exposure update. I have an iPhone 11, iOS 13.5.1 and the Corona-Warn-App is version 1.0.6.

**Comment by whynotberlin** [comment] 2020-07-13 20:57
I just had „15/14 days“ which was confusing and now it says „unknown risk“, as if I had never turned exposure logging on.

![36077BDE-F593-450B-8D73-DE298BAF54FD](https://user-images.githubusercontent.com/68251458/87352607-a0e0bc00-c55b-11ea-9c8d-02262ec3d598.jpeg)

I have often had irregular day counts but wasn’t sure if I was just confused. I will start taking screenshots to keep track. 

Just updated the Corona Warn App, nothing changed. 

iPhone SE 13.5.1

**Comment by gkgg** [comment] 2020-07-15 15:37
[update] Maybe it is too early to call my observations a pattern, but perhaps telling about it rings a bell … somewhere.

The shortened version:
- running v1.0.2, counters/indicators work as expected
- after updating to v1.0.3 counters/indicators drop to "9/14", appear to be stuck there
- updating to v1.0.4 doesn't bring any changes
- after updating to v1.0.5/v1.0.6 (morning/evening of the same day), the next day in the morning the counters/indicators show "10/14", but appear to be stuck there again
- after updating to v1.0.7 the next day in the morning the counters/indicators show "11/14", but appear to be stuck there again

I did neither change the way I use my phone, nor did I receive any system updates (still iOS 13.5.1).

**Comment by maku1303** [comment] 2020-07-15 16:48
[update] after being stuck at "13/14 days" for a while, I am now stuck at "14/14 days" for about 5 days :-(
1.0.7 (0)
And hurray, I have a news "Fehler 13" 

iOS

**Comment by slage16** [comment] 2020-07-17 04:20
I still have problems with the correct display of the active days.

Currently I have 11 of 14 days in my calendar since 2 days

App-Version 1.0.7
iPhone Xs 
iOS 13.6

Wednesday:
![3730E827-9BD8-4D40-B761-9D59A9A50943](https://user-images.githubusercontent.com/42173759/87748129-6003d400-c7f5-11ea-868d-38b0449f7993.png)
Thursday:
![8720F3AB-A97A-494E-81C8-08C083E37327](https://user-images.githubusercontent.com/42173759/87748136-62fec480-c7f5-11ea-809c-7a8bbe81d11d.png)

**Comment by tkowark** [comment] 2020-07-17 07:17
@maku1303 14/14 does not count as stuck. Your "Risiko-Ermittlung" was just active for the entire last 14 days. We are currently working on making that screen clearer, but if you see that and it does not change anymore, everything is working as expected

@slage16 the 11 / 14 days can stay for a couple of days depending on which days in the past the app was deactivated. As an example: today you have 11/14 day and exposure logging was deactivated for the last 3 days. Then it would take 11 days until you see a change as only then the deactivation from 3 days ago would no longer be in the last 14 days window. See https://www.coronawarn.app/de/faq/#days_active_Android for more details and https://github.com/corona-warn-app/cwa-app-android/issues/796#issuecomment-653061512 for a detailed breakdown.

**Comment by tkowark** [comment] 2020-07-17 10:57
Not even indirectly by using flight mode, disabling bluetooth, shutting the phone off at night?

**Comment by FarahElI** [comment] 2020-07-17 18:12
Same here. I never turned it off. I only have a 'do-not-disturb'on at night. And my count 13 of 14 days is still stuck. It just added the message three days ago that my app is not supported in the region that I live. Although I'm still at the same spot. But the pop up message disappeared again yesterday.

**Comment by slage16** [comment] 2020-07-19 18:58
> Not even indirectly by using flight mode, disabling bluetooth, shutting the phone off at night?

After three day’s in a row don’t disable bluetooth, using flight mode or switch of my iPhone off, it displays still 11 of 14 days. And this problem I’ve now since Wednesday.
 
It shouldn't be too difficult for you to implement an algorithm with modulo.

**Comment by tkowark** [comment] 2020-07-24 11:32
Since this bug has not resurfaced after the recent updates, we'll close the issue accordingly. If you experience it again with the latest app and iOS version, please open a new, dedicated issue.

Thanks for all your input!

**Comment by Ein-Tim** [comment] 2020-07-24 11:48
> Since this bug has not resurfaced after the recent updates, we'll close the issue accordingly. If you experience it again with the latest app and iOS version, please open a new, dedicated issue.
> 
> 
> 
> Thanks for all your input!

Hi @tkowark 
My days are still stuck at 12 from 14 days since more than 2 weeks.
I've installed the CWA and never deactivated "Risiko Ermittlung".
Should I create a new issue? 
Best wishes
Tim

**Comment by maku1303** [comment] 2020-07-24 12:01
hahaha .... now the just removed the "x/y days" from the screen

iOS Iphone 8s

**Comment by tkowark** [comment] 2020-07-24 12:22
@maku1303 the x/y das is still there, only if you "completed" the full 14 days there is the "dauerhaft aktiv" display. 

Since the issue still persist for @Ein-Tim , I'll reopen the issue.

**Comment by tkowark** [comment] 2020-07-24 12:23
@Ein-Tim which version of CWA are you running right now?

**Comment by Ein-Tim** [comment] 2020-07-24 12:34
> @Ein-Tim which version of CWA are you running right now?

I'm running version 1.1.1 (3) and in the App store I can't download any newer version.

**Comment by maku1303** [comment] 2020-07-24 13:06
I was at 14/14 for about 10 days. Now i see this 
![11D66609-0934-43CE-8087-6B5A05746A12](https://user-images.githubusercontent.com/67896615/88394185-43e8cf80-cdbf-11ea-868f-3b6bca16b451.jpeg)

**Comment by tkowark** [comment] 2020-07-24 13:13
Yes, exactly as I've written above. Your app is working as expected. The text change was made since many users did not understand why the app did not continue counting after arriving at 14/14 days.

**Comment by gkgg** [comment] 2020-07-24 13:20
I guess this has been changed in v1.1.1 to sort of replace that 14/14 indicator, because it confused many people. It still is present in the section "Risiko-Ermittlung […]" above.
With that change of the phrasing, there is "no need" to ask what happens in day 15, 16 and so on, as 14 days are considered "permanent" as far as tracking the potential risk is concerned.

**Comment by Ein-Tim** [comment] 2020-07-24 15:13
@tkowark What should I do?
Should I wait until a newer version of CWA is released and if the days are still stuck then, I comment here again?

**Comment by tkowark** [comment] 2020-07-24 15:26
Mhhh, since this thread is already rather crowded and the original "days jumping back" issue should be resolved, let's do it like this:
* I'll close this issue again
* You open a dedicated new issue "Days active stuck at 12/14 days for more than 2 weeks"
* If your displayed active days change either by themselves or due to a new version, would be great to get feedback in the new issue

Sounds reasonable?

**Comment by Ein-Tim** [comment] 2020-07-24 15:29
Yes, let's do it this way.
Thank you!

**Closed** 2020-07-24 15:44 UTC
Labels: UX, bug, community, in progress

**Comment by maku1303** [comment] 2020-07-24 22:53
> Yes, exactly as I've written above. Your app is working as expected. The text change was made since many users did not understand why the app did not continue counting after arriving at 14/14 days.

Okay, I understand. I just saw at my wife’s iPhone already 20/14 days.

**Comment by SebastianWolf-SAP** [comment] 2020-07-27 09:38
@maku1303 Please ensure to run the latest version of the app (currently 1.1.2) - it seems that your wife still uses a quite old one. 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
