### ISSUE TITLE
Transnational Exposure Logging: wrong text in English localization

### ISSUE THREAD

**Issue by achisto** [corona-warn-app/cwa-app-ios#1487] opened 2020-11-10 11:08 UTC
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug
When using the CWA in English localization the last sentence of the informative text regarding Transnational exposure logging does not make any sense. See attached picture for details.

When switching the language to German everything is fine so I believe there is just some translation issue here or a word missing.

## Expected behaviour
Be clear about when and where mobile data will or will not be used by the app.

## Steps to reproduce the issue
1. Click on "Exposure logging active"
2. Click on transnational exposure logging
3. Scroll down and see the sentence as shown in the attached screenshot

 ![image](https://user-images.githubusercontent.com/20704439/98665969-a9e86b00-234c-11eb-8b8e-9f3df23a4484.jpeg)

## Technical details
- app version 1.5.3 (1)

## Possible Fix
My suggestion for the sentence would be: "you will not be charged for the data used by the app in this context, nor will roaming charges for this apply in other EU countries."

**Comment by dsarkar** [comment] 2020-11-10 11:20
Dear all,

Thank you for your contributions.
This has been reported already here https://github.com/corona-warn-app/cwa-documentation/issues/457. Please continue any further discussion there!

Thanks again! Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-11-10 11:20
Duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/457

**Closed by dsarkar** 2020-11-10 11:20 UTC
