### ISSUE TITLE
Apple's AppStore shows minimum age: 17+ (should be 0 like in Google playstore)

### ISSUE THREAD

**Issue by schmitti73** [corona-warn-app/cwa-app-ios#677] opened 2020-06-17 11:19 UTC
see subject

**Comment by tkowark** [comment] 2020-06-17 11:41
duplicate of #632

**Closed by tkowark** 2020-06-17 11:41 UTC
Labels: bug

**Comment by corneliusroemer** [comment] 2020-06-17 15:46
But the duplicate got closed without proper reasons and discussion (as usual...)
