### ISSUE TITLE
Wrong date of birth in Rapid test profile

### ISSUE THREAD

**Issue by muslu92** [corona-warn-app/cwa-app-ios#2844] opened 2021-06-03 23:27 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11
- iOS version: 14.6
- App version: 2.2.1

## Describe the bug

When I create a rapid test profile, the date of birth under the QR-Code is always one day earlier than the one I typed in before.

## Steps to reproduce the issue

![C99168CD-41DD-4483-962F-071F4E4772C0](https://user-images.githubusercontent.com/85320497/120723918-0078ea80-c4d3-11eb-863d-6ce34bb596e7.png)
![2E2CC6A4-1E73-43D8-A105-1D18EF1C0C1B](https://user-images.githubusercontent.com/85320497/120723913-feaf2700-c4d2-11eb-8cb2-7584044fe3c0.png)

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-7263](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7263)

**Comment by Ein-Tim** [comment] 2021-06-04 00:35
Hey @muslu92 👋 

Thank you for reporting this issue. We are aware of this bug and it is planned to be fixed in the next upcoming release, version 2.3. 

This was reported in #2695 before and is an error with the timezones. It only happens between 00:00h and 01:59h CEST.

The corresponding PR is: #2741.

I'd like to ask you to close your issue in favour of #2695, monitor this issue and follow up there if necessary.

Have a good night and stay safe & healthy!

**Comment by dsarkar** [comment] 2021-06-04 06:52
@muslu92 Thanks for the report. As @Ein-Tim already mentioned, this issue is know and fixed in version 2.3, which will be delivered quite "soon". I am afraid that we cannot give an exact delivery date, but we will post it here on GitHub once roll out has started. 

In the meantime, as a workaround, you can create your rapid test profile at any time, but not between 00:00-0200. 

Thanks. Best regards, DS

---
Corona-Warn-App Open Source Team
Internal Tracking ID: [EXPOSUREAPP-7263](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7263)

**Comment by Ein-Tim** [comment] 2021-06-09 05:29
Version 2.3 has been released to the App Store yesterday. Can you confirm that this is fixed @muslu92?

**Comment by Ein-Tim** [comment] 2021-06-19 10:32
Can we close this as fixed in version 2.3? The fix has been confirmed in #2695.

**Comment by dsarkar** [comment] 2021-06-19 10:35
@muslu92 Thanks again for the report. We will close this issue, since the fix has been confirmed as @Ein-Tim already mentioned https://github.com/corona-warn-app/cwa-app-ios/issues/2844#issuecomment-864388066.

Best, DS
---
Corona-Warn-App Open Source Team

**Closed** 2021-06-19 10:35 UTC
Labels: Fix 2.3, bug, duplicate, mirrored-to-jira
