### ISSUE TITLE
Missing default action for "More Information" button in EN Error popup

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#1353] opened 2020-10-15 07:41 UTC
## Avoid duplicates

* [] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is not already reported in another issue

## Describe the bug

When ENF reports an error code, this is shown as dialog box to the user, with buttons "ok" and "Mehr erfahren". But in some cases, the "mehr erfahren" button is empty. Example: EN error 2 (bad params). See [here](https://github.com/corona-warn-app/cwa-app-ios/issues/1339#issuecomment-708934167)
I agree that there is not much a user can do if they encounter such an error. But at least they should report back so it can be investigated and fixed.

## Expected behaviour

Button "mehr erfahren" should always give some advice. If no specific action is recommended, the user should at least report back to the technical hotline or to the project maintainers at github.

## Steps to reproduce the issue

- Trigger an EN error like error 2
- see the dialog box
- press button "mehr erfahren"

## Technical details

cwa 1.3.2(0)
- iOS Version:
- Device:

## Additional context

----
Internal Tracking ID: EXPOSUREAPP-3286

**Comment by Ein-Tim** [comment] 2020-10-15 12:02
@ndegendogo 
I also think it would be good to have the "More Information" button working, but since the EN Error comes from the ENF, I think the Pop Up also comes from Apple and the Devs here can't do anything about it.
Just wanted to add that 🙂

**Comment by tens0rfl0w** [comment] 2020-10-15 12:41
@Ein-Tim If I remember correctly from a earlier pre-release development stage the error gets returned as a conditional return when the API entry point functions are called, so the alert popup is handled by the app. With that it's possible to handle every error appropriate.

**Comment by Ein-Tim** [comment] 2020-10-15 12:56
@tens0rfl0w 
Okay, as said this was only an assumption but thanks for your comment 👍 Lets wait for the Devs and see what say

**Comment by tens0rfl0w** [comment] 2020-10-15 13:07
Actually found the PR that I had in my mind: https://github.com/corona-warn-app/cwa-app-ios/pull/868

This was the latest addition to UI error handling. Looking at the code you can see that the error handling is handled by the app itself and that there is just no special case for Error 2 as it never happened before. Should be an easy one to fix this. :)

**Comment by heinezen** [comment] 2020-10-15 13:27
Hello everyone,

The issue is now mirrored to Jira (ticket ID: EXPOSUREAPP-3286). Let's see what the devs can do about it. Further updates on the progress will be posted in this thread.

@ndegendogo I changed your title to be more precise. Hope that is okay with you.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-12-01 08:39
Dear community, 

we also updated info for developers with respect to this issue.  Best,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-12-01 11:44
See https://github.com/corona-warn-app/cwa-app-ios/issues/1000#issuecomment-736485835

**Comment by Ein-Tim** [comment] 2020-12-23 21:52
Although this is solved, I again looked at the PR which @tens0rfl0w shared here a few months ago (#868). 
When looking at [this file](https://github.com/corona-warn-app/cwa-app-ios/blob/162423bc4fdb1c57124968e0d16bcb8ce213ab00/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings), there, in [line 23](https://github.com/corona-warn-app/cwa-app-ios/blob/162423bc4fdb1c57124968e0d16bcb8ce213ab00/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L32), the `General_moreInfo_URL` is defined so that it points to `https://www.coronawarn.app/de/faq/`.

If I understand everything correct here this means that all ENErrors (but 5, 11 and 13) should guide the user to https://www.coronawarn.app/de/faq/, or?

**Comment by dsarkar** [comment] 2020-12-28 07:28
@Ein-Tim, We will check with the developers. Thanks, DS 

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2021-01-21 12:19
@Ein-Tim

> If I understand everything correct here this means that all ENErrors (but 5, 11 and 13) should guide the user to https://www.coronawarn.app/de/faq/, or?

Feedback from developers: That is correct.

@ndegendogo Feel free to close this issue. 


Thanks to everybody.

**Comment by Ein-Tim** [comment] 2021-01-21 14:16
No please don't close this.
The PR #868 was merged on the 08.07.2020.
This Issue was opened on the 15.10.2020. 
@dsarkar could the devs please cross check if this really works?

**Comment by heinezen** [comment] 2021-01-24 14:39
@Ein-Tim The latest change was in https://github.com/corona-warn-app/cwa-app-ios/pull/1608 which suppresses the error messages and handle the error internally. This is the recommended procedure for all ENErrors as far as I know. The app will cach these error and display its own message popup with links to the FAQ.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment] 2021-01-24 14:41
Thanks @heinezen.
Can be closed from my side.

**Comment by dsarkar** [comment] 2021-01-28 11:48
@Ein-Tim regarding errors 5,11,13 and the rest of them and your question https://github.com/corona-warn-app/cwa-app-ios/issues/1353#issuecomment-764671747I got the following answer from the developers:

> Yes, it is currently implemented in this way. Errors that occur or are known are linked to a specific FAQ entry to help the user. Error codes that exist theoretically but have never occurred before are linked to the FAQ overview. If one of these errors occurs, the URL can be quickly adjusted.

**Comment by Ein-Tim** [comment] 2021-01-28 11:56
Okay thanks. Can be closed 👍

**Closed** 2021-01-28 12:26 UTC
Labels: bug, mirrored-to-jira, ready to close
