### ISSUE TITLE
App hangs/unresponseive after allowing notifications in setup [iOS14 Beta 2]

### ISSUE THREAD

**Issue by aejb** [corona-warn-app/cwa-app-ios#871] opened 2020-07-08 17:36 UTC
## Describe the bug

After after notifications in the welcome / setup screen, the app becomes unresponsive and neither “next” nor “do not allow” do anything 

## Steps to reproduce the issue

1. install app for first time
2. when prompted, allow notifications 
3. app will become unresponsive 

## Technical details

- iOS Version: iOS 14 Beta 2
- Device: iPhone 11

**Comment by n-thumann** [comment] 2020-07-08 18:00
Duplicate of #749. CWA is not working on iOS 14 Beta yet, see https://www.coronawarn.app/en/faq/#ios_14_beta ✌️

**Comment by SebastianWolf-SAP** [comment] 2020-07-08 18:11
Thanks for pointing that out, @n-thumann. 

@aejb Please also see the beta release information by Apple: https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14-beta-release-notes

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Closed by SebastianWolf-SAP** 2020-07-08 18:11 UTC
