### ISSUE TITLE
Provide exact source-code of AppStore release on "Releases" in GitHub Repo

### ISSUE THREAD

**Issue by imdatsolak** [corona-warn-app/cwa-app-ios#679] opened 2020-06-17 12:44 UTC
## Current Implementation
Currently, the downloadable Client in the AppStore is 1.0.2 (2). But there is no Release (and thus packaged source) for this in the GitHub Repo.

## Suggested Enhancement
Please provide the AppStore released client's exact source-code as a release in GitHub - with Marketing Version + Build Number so that we can reproduce it ourself.

## Expected Benefits
Increase trust in the approach that the binary in the AppStore was created from a verifiable source-code.

**Comment by winkelsdorf** [comment] 2020-06-17 14:31
Or instead introduce reproducible git tagging in the release pipeline which also sets the app information during release builds.

**Comment by inf2381** [comment] 2020-06-17 16:06
Closing this issue as a duplicate of (Allow for Reproducible Builds)[https://github.com/corona-warn-app/cwa-documentation/issues/14]. We are currently trying to find out a way that also suits our internal guidelines.

**Closed by inf2381** 2020-06-17 16:06 UTC
Labels: enhancement

**Comment by imdatsolak** [comment] 2020-06-19 07:35
Sorry, I am just asking for a tag - so that we (outsiders) know what state the source-code was from which you created the binary in the AppStore. I don't even want to have the ability to checksum the binary. This would increase trust ...
