### ISSUE TITLE
ENErrorDomain-Fehler 11; iPhone 11 with 14.0.1 

### ISSUE THREAD

**Issue by franzi1802** [corona-warn-app/cwa-app-ios#1296] opened 2020-10-06 07:43 UTC
## Avoid duplicates

* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Technical details

- iOS Version:
- Device:

**Comment by svengabr** [comment] 2020-10-06 09:43
Duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/972

**Comment by svengabr** [comment] 2020-10-06 09:44
Duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/1284

**Comment by svengabr** [comment] 2020-10-06 09:48
Hey @franzi1802,

Thanks for your input! I needed to mark your issue as duplicate and kindly ask you to contribute to the existing discussion.

https://github.com/corona-warn-app/cwa-app-ios/issues/972

Your feedback is already collected and I did inform the developers.

Best regards,
SG

Corona-Warn-App Open Source Team

**Closed by svengabr** 2020-10-06 09:48 UTC
Labels: bug

**Comment by dsarkar** [comment] 2020-11-24 11:59
@franzi1802, and community, can you confirm that this issue is resolved for you?

Best wishes,
DS

---
Corona-Warn-App Open Source Team
