### ISSUE TITLE
You plan an event screen ui bug

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-app-ios#3163] opened 2021-07-15 09:30 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [?] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone SE 1
- iOS version: 14.6
- App version: 2.5.1

## Describe the bug

![image](https://user-images.githubusercontent.com/73582096/125765062-a25dc36e-cc15-4117-bda7-6ed3fadb0717.jpeg)

## Steps to reproduce the issue

I wasn't able to reproduce it.

## Expected behaviour

Show "löschen" in the middle.

## Possible Fix

Maybe needs to be done be apple, hadn't time to look into the code.

**Comment by dsarkar** [comment] 2021-07-15 09:45
@jucktnich Actually I observed the same, but didn't find the steps how to reproduce. iPhone 6s/ iOS 14.4 / CWA 2.5.1

**Comment by Ein-Tim** [comment] 2021-07-15 09:48
I'll try to reproduce this. After some quick tests on my iPhone 6s (iOS 15 Beta 2) & iPhone XR (iOS 14.6) I can't reproduce this. I'll try with the emulator when I have time.

**Comment by Ein-Tim** [comment] 2021-09-28 06:17
I'm still not able to reproduce this. Seems to be an edge case IHMO.

**Comment by ndegendogo** [comment] 2021-09-28 07:11
From the "look" of the screenshot, it could be a race condition of two unsynchronized animations ...

**Comment by dsarkar** [comment] 2021-09-28 07:36
Hi @jucknich @Ein-Tim, same here, I can't reproduce anymore. I suggest closing this issue. Should we be able to reproduce this issue, we can re-open it and mirror internally the bug. Thanks.

---
Corona-Warn-App Open Source Team

**Comment by jucktnich** [comment] 2021-09-28 10:48
Closed as not reproducible

**Closed** 2021-09-28 10:48 UTC
Labels: bug, in review

**Comment by dsarkar** [comment] 2021-09-28 10:52
@jucktnich Thanks for contributing anyway! Best wishes, DS

---
Corona-Warn-App Open Source Team
