### ISSUE TITLE
Fehler EN Code: 16

### ISSUE THREAD

**Issue by blueicehaller** [corona-warn-app/cwa-app-ios#1657] opened 2020-12-09 16:44 UTC
## Avoid duplicates
* [ ] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Question has not already been asked in another issue

## Your Question

* Source File:
* Line(s):
* Question:

Hello,
an Friend has an iPhone SE and asked me if I know the Error `EN Code: 16` which occurs again and again but I don't have an iPhone but GitHub Account.
I asked him to provide me an [Screenshot](https://support.apple.com/en-us/HT200289).
Do you need further Information?

Hallo,
ein Freund hat ein iPhone SE und mich gefragt ob ich den Fehler `EN Code: 16` welcher immer wieder auftritt kenne. Da ich kein iPhone habe aber einen GitHub Account frage ich hiermit.
Ich habe ihn gebeten mit ein [Bildschirmfoto](https://support.apple.com/de-de/HT200289) zu senden.
Braucht ihr weitere Informationen?

**Comment by Ein-Tim** [comment] 2020-12-09 16:49
@blueicehaller Please see: https://github.com/corona-warn-app/cwa-app-ios/issues/1000

This will be fixed with version 1.8.0

**Comment by dsarkar** [comment] 2020-12-09 18:38
Duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/1000

**Comment by blueicehaller** [comment] 2020-12-09 21:15
Please add ' EN Code: 16' to the [FAQ](https://www.coronawarn.app/en/faq/)

**Comment by Ein-Tim** [comment] 2020-12-10 08:38
@blueicehaller 
As the author of this Issue you should have the option to close it 😄

**Comment by dsarkar** [comment] 2020-12-10 09:10
@Ein-Tim, @blueicehaller,  Thanks for the postings. I will close the issue. @blueicehaller monitor https://github.com/corona-warn-app/cwa-app-ios/issues/1000 for updates on this issue, please. Thanks. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Closed by dsarkar** 2020-12-10 09:10 UTC
Labels: duplicate, question
