### ISSUE TITLE
IPhone repeatedly shows "exposure notifications region changed" dialog

### ISSUE THREAD

**Issue by sventropy** [corona-warn-app/cwa-app-ios#645] opened 2020-06-16 12:27 UTC
## Your Question

* Hardware: IPhone 11 Pro Max
* iOS Version: 13.5.1

First of all kudos to the team for reaching this milestone. Great achievement and definitely a template approach to future projects (hopefully).

### Issue
I am posting this as a question since I am unsure about the source. After installation the iOS app this morning, the Phone in the mean showed this dialog twice. 

![IMG_0813](https://user-images.githubusercontent.com/1979426/84774204-c79fe700-afdd-11ea-9a79-c96e5e511f44.jpg)

The phone was not moved that much throughout the day, mostly residing on my desk.
Other seems to face the [same issue](https://twitter.com/rstockm/status/1272858776622772225?s=20) (Twitter Link). 

### Questions
* Is this something to report to Apple? 
* Is it an issue?
* Which additional information would you need from me?

Thanks for your support. 
Cheers.

**Comment by rstockm** [comment] 2020-06-16 12:39
This happened to me as well. I moved rather 1 mile today in Mid-Berlin.

**Comment by tens0rfl0w** [comment] 2020-06-16 12:42
This is definitely no notification from the app. The notification comes from the Exposure-Notification-Framework, so it's a „bug“ that should be reported to Apple. (If that happens more often)

**Comment by thomasaugsten** [comment] 2020-06-16 16:35
This alert and a not enough space error comes from the Exposure-Notification-Framework. This is a bug by Apple and already reported and will be fixed soon. You can ignore this message it will not affect the exposure notification. You can check under settings->data protection-> health-> covid19 the exposure notification is always on.

**Comment by Gill-Bates** [comment] 2020-06-16 19:23
Can confirm this behavior on iPhone 11 iOS 13.5.1 too.

**Comment by hmstahl** [comment] 2020-06-16 19:57
This happened on my wife's the iPhone Xr with iOS 13.5.1 today.

**Comment by Lana-ra** [comment] 2020-06-17 11:56
Hi, this is happening to me all the time as well. My language settings are English and Region is Germany. Some region settings were changed though after these notifications, my news app is showing UK news instead of German news now and I cannot find the way to switch it back. I did not move outside the country or anywhere near the border.

**Comment by jjochen** [comment] 2020-06-17 17:29
Same here: Region Germany, language English.

**Comment by visualication** [comment] 2020-06-17 17:51
happened to me too, stay in home office only, pinneberg.

ios 13.5.1, iphone 11 pro max

**Comment by bufemc** [comment] 2020-06-18 14:35
Can confirm the issue, I did not even leave the so called Rems-Murr-Kreis in Germany.
iPhone 8, latest iOS, region Germany. Distance travelled about 2,5 km max.
Mobile network + Bluetooth + GPS on, automatic time settings, timezone Berlin.

**Comment by JukeboxOne** [comment] 2020-06-18 18:19
region germany
language English
ios 13.5.1, iPhone 11 Pro

Happens three times a day - minimum. Travel distance 15km max

**Comment by itsfloha** [comment] 2020-06-25 13:14
Can also confirm the issue. Happens at least 3-4 times a day. 
I travel about 40km to my work place. 
iOS: 13.5.1
HW: iPhone 11 Pro Max
Settings: Region: Germany, Language: English, Mobile Network: On, Bluetooth: On, Time setting: Automatic, Time zone: Berlin

**Comment by dh4nav** [comment] 2020-06-30 14:48
I can confirm this issue still exists as of today (the message popped up just now, in fact).
My iPhone moved less than 100 m over the last 15 hours, and less than 50 km (to work and back) over the last 30 hours.

iPhone X, iOS 13.5.1, Region: Germany, Carrier: T-Mobile, Time Zone: Berlin (Automatic), Language: English, Mobile Data: On, Wifi: On, Bluetooth: On. Connected to Wifi while the message popped up, WiFi Router: FritzBox 7490.
![photo_2020-06-30_16-45-55](https://user-images.githubusercontent.com/10965538/86140752-7ae60100-baf1-11ea-9aee-242946c0bbd8.jpg)

**Comment by bkahlert** [comment] 2020-07-08 17:36
This message is annoying as f**k!
Apart from Apple's responsibility to investigate I would be very pleased if someone from Telekom and SAP could make efforts -- I'm sure you've been paid well enough in advance according to the app's ridiculously high costs.

![IMG_55B4571BFA59-1](https://user-images.githubusercontent.com/1170054/86951280-95ebed00-c151-11ea-8429-816a11a477c0.jpeg)

**Comment by SebastianWolf-SAP** [comment] 2020-07-08 17:47
@bkahlert Please check your language! It has been mentioned repeatedly in various occasions, also [in our FAQ](https://www.coronawarn.app/en/faq/#iphone_region_change)  that this is exclusively Apple's responsibility, that this message can't be caught by the app itself and that we all need to wait for Apple to release a fix with their next iOS version.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by robmorgan** [comment] 2020-07-08 21:33
@bkahlert let’s have some patience. I understand from what I’ve read it’s an upstream issue on Apple’s end and therefore the immediate problem does not lie with either Telekom or SAP. Hopefully this is resolved soon in an OS update.

**Comment by samkrieg** [comment] 2020-07-11 08:46
For € 20'000'000 I would just accept a f**k and don't whine about foul language. (Also, he surely meant "funk" or "fink")

**Comment by SebastianWolf-SAP** [comment] 2020-07-11 09:14
@samkrieg We have a [code of conduct](https://github.com/corona-warn-app/cwa-app-ios/blob/develop/CODE_OF_CONDUCT.md) and that needs to be respected by everybody on this platform. 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by bkahlert** [comment] 2020-07-11 21:08
Thank you @robmorgan for calming down the discussion instead heating it up.  
Thank you @samkrieg for reassuring that I'm not the only one seeing a problem in that deal.  
@SebastianWolf-SAP you are right, I should have watched my language and it is your right to tell me. But if you do, please don't ignore that it doesn't come out of a sudden but it's a reaction to something far less tolerable. Apart from the **way** I criticized, I'm loyal to **what** I criticized. In some countries, helping and supporting is considered a service to the people these days, whereas Telekom and SAP seem to have focussed on making a _good_ deal -- something of what I can't find any justification for.
I consider that aspect of my critique important enough so that it shouldn't be so easily ignored by simply referring to a FAQ or to the code of conduct.

**Comment by SebastianWolf-SAP** [comment] 2020-07-11 21:25
@bkahlert We are here, we are listening and yes, we also appreciate the community‘s efforts very much. One example: Just today the dev team fixed a critical issue (#880) which was reported by the community in that speed that the team could fix it really fast. Without the community we wouldn’t have seen that fix that early. Thus, I really can‘t agree with you here. 

On the other side there are simply things which we can’t influence. Apple has its own delivery schedules and they will release the fix with iOS 13.6 when it’s done. That‘s why we haven’t ignored the input by the community - we are simply informing everybody what‘s the case here.

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team

**Comment by bkahlert** [comment] 2020-07-14 23:21
By the amount Germany was charged for the app (https://www.daserste.de/information/politik-weltgeschehen/kontraste/videosextern/corona-warn-app-ziemlich-teuer-104.html; "The monthly costs presumably include manual contact tracing, but the development cost charged by Deutsche Telekom and SAP is completely inexplicable." https://9to5mac.com/2020/06/16/germanys-contact-tracing-app/) one could have hoped for more...

**Comment by sin-azucar** [comment] 2020-07-15 11:34
@bkahlert Since this is a bug in iOS, you're blaming the wrong party. How many **_billions_** have customers paid to Apple over the course of the last few years - and yet they delivered an API that seems poorly tested and instable.

**Comment by tkowark** [comment] 2020-07-24 11:13
Since this issue is now fixed with iOS 13.6., we'll close the issue accordingly. If somebody again experiences it on newer iOS version, please open a new issue for that.

**Closed by tkowark** 2020-07-24 11:13 UTC
Labels: apple, question
