### ISSUE TITLE
New releases, contact diary, beta testers amplify the test base via testflight

### ISSUE THREAD

**Issue by ouboub** [corona-warn-app/cwa-app-ios#1581] opened 2020-11-26 12:57 UTC
Hi

One hour ago, that article was published in the «Spiegel» <https://www.spiegel.de/netzwelt/apps/corona-warn-app-update-bringt-neue-funktionen-a-24874a83-9bf7-46c8-a59d-ab3905a17832>

If I understand this correctly there will be a contact diary included in a future release. Now given the problem(s) and issues concerning <https://github.com/corona-warn-app/cwa-app-ios/issues/916#issuecomment-727907904> wouldn't it be wise to enlarge the circle of beta testers (via testflight).

In my opinion, free and open software was/is successful because of the large user base of testers. The corona-warn is on github and according in a sense open software, however due to apples policy it is quite complicated to compile, install and to test, while it is relatively straightforward for GNU emacs say.

This is why I think «testflight» would be the right thing to do.

regards

Uwe Brauer

**Comment by dsarkar** [comment] 2020-11-26 13:31
Dear @ouboub,

Thank you for your request. Please continue this discussion in our other open issue #153. See also corona-warn-app/cwa-documentation#214. I will close this issue now, please contribute to the open issue in this case, so we can focus all the information on this topic in one single space.

Many thanks. Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-11-26 13:32
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/153

**Closed** 2020-11-26 13:33 UTC
Labels: duplicate, question
