### ISSUE TITLE
Since update to IOS 14.2.1 CWA fetches keys every time it is opened 

### ISSUE THREAD

**Issue by range** [corona-warn-app/cwa-app-ios#1554] opened 2020-11-21 18:46 UTC
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [?] Bug is not already reported in another issue

## Describe the bug

Since my phone updated to iOS 14.2.1, the Corona-Warn App seems to fetch new keys every time I open it up. You can see this inbzje screenshot: At the bottom it’s checking at 14:16 three days ago and two days ago. The update came in during the night from 19th to 20th of November. It then checks at 14:17 on the 20th and from them on every time I opened the application. 

I saw #1505 and #1497 but these talk about problems because of network issues. This is not the case here, the obvious change is the iOS update.

I am running 1.6.1 (0) on iPhone 12 pro with iOS 14.2.1. 

Cheers,

Ralph 
![DEBDEE65-2AE3-4638-8153-734D6B6C7315](https://user-images.githubusercontent.com/346905/99885006-4571b980-2c32-11eb-8e5b-e61bc0be10da.png)

**Comment by thomasaugsten** [comment] 2020-11-21 18:54
This is related to the v1.6.1 this will fix with the v1.7 next week.

**Comment by Ein-Tim** [comment] 2020-11-21 19:15
For more details see #1544

**Comment by range** [comment] 2020-11-21 20:55
> For more details see #1544

I didn’t relate this to the problem I am seeing because of the connection issues in that issue - something that I can rule out. But thanks for the heads up.

**Comment by Ein-Tim** [comment] 2020-11-21 23:12
@range Ok, than I understood you wrong, sorry. If your question is answered please close this Issue. Thanks!

**Comment by range** [comment] 2020-11-22 01:44
Okay, I guess i created a communication problem. In opened this bug report, because the others I found talked about connection problems when the „out of line“ updates occurred. As I can rule out connection problems, I don’t see my question as answered. 

Should 1.7 fix this bug though as was hinted above, I am fine with this issue being closed. 

Ralph

**Comment by dsarkar** [comment] 2020-11-22 09:01
Dear @range, dear community,

Thanks for contributing. I will close this as duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/1544.
Should it be necessary, of course feel free to re-open this issue again.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-11-22 09:01
Duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/1544.

**Closed by dsarkar** 2020-11-22 09:01 UTC
Labels: bug
