### ISSUE TITLE
"Fehler - Ihre Internetverbindung wurde unterbrochen" bei jedem Öffnen der App

### ISSUE THREAD

**Issue by anothernewusername** [corona-warn-app/cwa-app-ios#1312] opened 2020-10-06 17:16 UTC
Jedes Öffnen der App führt zur Popup Fehlermeldung: "Fehler Ihre Internetverbindung wurde unterbrochen. Bitte prüfen Sie die Verbindung und öffnen Sie die App dann erneut."

Keine Abhilfe durch:
- Schließen und Öffnen der App
- Neustarten von App und Gerät
- Zurücksetzen der App

Auch bei der Rückkehr von tieferen App Screens auf den Main Screen erscheint oben genannte Fehlermeldung.

Eventuell tritt das Problem seit dem Update auf iOS 14 auf.

**Comment by Ein-Tim** [comment] 2020-10-06 17:25
Dumme Frage, aber passiert das nur wenn du keine Internetverbindung hast oder auch sonst immer?
Könntest du außerdem mal versuchen ob dieses Problem weiterhin besteht wenn du Mobile Daten/ein anderes WLan verwendest?

**Comment by abro1i** [comment] 2020-10-07 08:01
Hi @anothernewusername

thanks you for sharing this issue with us. Can you please give us more information regarding this issue:

Which exact iOS 14 version are you using?
Which device are you using? 

If you could also share a screenshot, that would really help.

Thank you

Best regards,

ABB

Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment] 2020-10-12 06:57
A few days ago I had a similar issue. And, yes, indeed, my internet was down at that time. Only local WLAN was available.

I agree that it is a good idea to notify the user about missing internet connection, because it affects the core functionality of the app.
But: 
1) one such error message should be enough. I got the error message again and again, each time when I returned from a submenu to the main screen.
2) On starting the app this check for internet availability should be done in a background thread, and not block any user actions; it is sufficient to show the result of this to the user. Several functions of the app do not need internet (e.g. look at my risk status, check the app version info, ...). I am aware that I can trigger a risk check by opening the app; but in my case the risk check was still fresh (~ 1 hour ago), and I just wanted to check the result (any 'green' encounters?); instead I got the message box with a quite long timeout in front of my screen during the attempt to connect to the internet; and no button to close it.

cwa 1.3.2(0) / iOS 13.7 / iPhone 8

**Comment by dsarkar** [comment] 2020-10-27 11:49
Dear @anothernewusername and @ndegendogo,

thank you for your contributions.
Now with the actual CWA version 1.5.2, can you please confirm the following behaviour:

If the last update was at least about 10 minutes ago, you repeatedly get the error message "Your internet connection was lost. Please ....". However, you can close it and still access other functions of the CWA, although you have to close the error message box repeatedly. If the update was very recent, there is no such error message for several minutes, even without internet connection. 

In that case, in order to summarise:

@anothernewusername you suggest rather to improve the user experience than reporting a bug. In that case we would transfer this issue to the wish-list.

@ndegendogo, your issue seems to be resolved as long you have a internet connection. 

Best regards,
DS

Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment] 2020-10-27 20:10
@dsarkar at the moment I have no internet access, so I could test behaviour of cwa 1.5.1
From my side ok, thanks

**Comment by dsarkar** [comment] 2020-10-30 11:31
Dear @anothernewusername and @ndegendogo,

Thanks again for your input.  My understanding is that the problem has not occurred again. Therefore, I close the issue. Please, should the problem persist, let us know and we will re-open the issue.

Furthermore, @ndegendogo, regarding https://github.com/corona-warn-app/cwa-app-ios/issues/1312#issuecomment-706914519,  you could, if you wish, open an issue in the wishlist since it is not a bug, but rather a user experience issue.

Best regards,
DS

Corona-Warn-App Open Source Team

**Closed by dsarkar** 2020-10-30 11:31 UTC
Labels: bug, further input needed
