### ISSUE TITLE
[RAT-profile] Not able to use the Siri suggestions

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-app-ios#3262] opened 2021-07-28 09:56 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone SE 1
- iOS version: iOS 14.7
- App version: 2.6.1

## Describe the bug

On the rat profile edit screen you cannot use the Siri suggestions

## Steps to reproduce the issue

1. Go to the RAT profile edit screen
2. Tap into an empty field
3. Try to use the suggestions on top of the keyboard
## Expected behaviour

Use the suggestions

**Comment by Ein-Tim** [comment] 2021-07-28 09:57
Duplicate of #3159

**Comment by jucktnich** [comment] 2021-07-28 09:59
Oh yeah, dunno why I didn't found it 🙈

**Closed** 2021-07-28 09:59 UTC
Labels: bug
