### ISSUE TITLE
Error 13 / Fehler 13 occurs repeatedly - case 1

### ISSUE THREAD

**Issue by djohana** [corona-warn-app/cwa-app-ios#2220] opened 2021-03-16 09:33 UTC
## Technical details

- Device name: Apple 
- iOS Version: 14.4
- App Version:1.14.4

## Describe the bug
Error 13 since 13.03

## Steps to reproduce the issue

Error keeps appearing, I am
Not able to see my exposure. 

## Expected behaviour

Should be able to see my exposure and update it 
![7D6F6221-1CFB-443F-BE89-A2D1F383D7C9](https://user-images.githubusercontent.com/80750994/111286948-07662e80-8643-11eb-954b-e81bcbeee419.jpeg)

---
Internal Tracking ID: [EXPOSUREAPP-5836](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5836)

**Comment by Ein-Tim** [comment] 2021-03-16 09:40
Hey @djohana 👋

Thanks for the report.

Could you please provide your EN-Log? 


<details>
<summary>How to export Exposure Notificaiton Logs under iOS 13.7 or newer</summary>


_This log does not conatin any private information!_

**German:**

`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen` ➡️ `Überprüfungen exportieren`

**English:**

`Settings` ➡️ `Exposure Notifications` ➡️ `Exosure Logging Status` ➡️ `Exposure Checks` ➡️ `Export Exposure Checks`

**To upload the file here, rename it from .json to .txt**
</details>

Thank you.

**Comment by djohana** [comment] 2021-03-16 09:56
[Uploading ExposureChecks-2021-03-16.zip…]()

**Comment by djohana** [comment] 2021-03-16 09:57
I can’t change the type of file from my phone, but I was able to compress it. I hope this works

**Comment by Ein-Tim** [comment] 2021-03-16 09:58
Thanks @djohana 

Sadly the upload doesn't work. Could you try it one more time? 

Thank you.

**Comment by djohana** [comment] 2021-03-16 10:07
[ExposureChecks-2021-03-16.zip](https://github.com/corona-warn-app/cwa-app-ios/files/6147947/ExposureChecks-2021-03-16.zip)

**Comment by djohana** [comment] 2021-03-16 10:08
If it doesn’t work, can I look in the text for the part you are looking for?

**Comment by Ein-Tim** [comment] 2021-03-16 10:18
@djohana 

Thanks, it's working now.
I'm looking into it.

This error appears every day since 13.03.21, correct?

**Comment by djohana** [comment] 2021-03-16 10:22
Yes, since the 13.03

**Comment by Ein-Tim** [comment] 2021-03-16 10:42
| Date | Check No (day) | Normal? |
| --- | --- | --- |
| 13.03., 03:50h | 1 | Yes |
| 13.03., 07:38h | 2 | Yes |
| 13.03., 11:42h | 3 | Yes^|
| 13.03., 11:45:06h | 4 | **No** |
| 13.03., 11:45:24h | 5 | **No** |
| 13.03., 15:42h | 6 | Yes^| 
| *Limit reached for 13.03. | | |
| 13.03., 16:23h | 7 | **No** |
| 13.03., 19:43h | 8 | **No** |
| 14.03.2021 | | | |
| 14.03., 11:50h | 1 | Yes |
| 14.03., 15:53h | 2 | Yes |
| 14.03., 16:50h | 3 | **No** |
| 14.03., 16:52h | 4 | **No** |
| 14.03., 16:53h | 5 | **No** |
| 14.03., 17:33h | 6 | **No** - No new files downloaded |
| 15.03.2021 | | | | 
| 15.03., 11:52h | 1 | Yes - No new files downloaded | 
| 15.03., 11:56h | 2 | Yes |
| 15.03., 16:02h | 3 | Yes |
| 15.03., 18:13h | 4 | **No** |
| 15.03., 19:34h | 5 | **No** - No new files downloaded | 
| 15.03., 20:02h | 6 | Yes |
| 16.03.2021 | | | | 
| No checks on 16.03. | | | |


Suggestion:
Don't open the app for 24h, the app should go back to normal.

---

^ These checks happened a bit to early.

**Comment by Ein-Tim** [comment] 2021-03-16 10:44
@djohana 

I can't explain why there are these non normal checks, did you update your iOS or the Corona-Warn-App? 

@dsarkar 

Somebody should look into this IHMO.

**Comment by djohana** [comment] 2021-03-16 10:48
The app was updated on the 12. Same day I got results on a Corona test, the QR code was uploaded on the 11 (Don’t know if this has something to do). I will not open it until tomorrow around this time (I hope it works, since I will need to read new test results via the app). Today I erased the old test, and will wait until tomorrow to scan the new qr.

thanks

**Comment by dsarkar** [comment] 2021-03-16 11:02
@djohana Thanks for reporting.
@Ein-Tim Thanks for the table.

**Comment by dsarkar** [comment] 2021-03-16 11:10
Internal Tracking ID: [EXPOSUREAPP-5836](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5836)

**Comment by Ein-Tim** [comment] 2021-03-16 11:13
@djohana 

Even when the Error 13 is shown, you can see your test result.

**Comment by djohana** [comment] 2021-03-16 11:15
@Ein-Tim great, thanks

**Comment by dsarkar** [comment] 2021-03-16 11:18
@djohana 
- iPhone model? 
- If you look at the table @Ein-Tim created, would you say that more or less these are the times you opened the app?
- If so, did you just open it, or did you try to scan a QR code, or maybe something else.

Thanks for the feedback.

**Comment by djohana** [comment] 2021-03-16 11:31
@dsarkar 
iPhone XS

I don’t remember opening the app so many times the last days. But I did open it to see if it worked again. I also tried restarting my mobile phone.

Over the past days i have open the app to take a look but also had the following interactions: On the 10th I got a high risk alert (my husband tested positive). On the 11 I scanned a QR code. Got the results on the 12. And today I erased the old test.

**Comment by dsarkar** [comment] 2021-03-16 11:48
@djohana ok, thanks for the feedback. Any further information you can give might help. We will come back to you. It is a rather strange behaviour of the app, in this specific case. The issue is forwarded to the developer´s team. On a side note: Warning you has worked properly as well as test result notification, that is good.

**Comment by dsarkar** [comment] 2021-03-16 11:55
@djohana Also, just to give a heads up, for the time being, one can say the app works. It does too many risk assessments during a day, which triggers the error 13 notification. 

- I assume that all this happened while being connected to wifi, not mobile data? Correct?
- Also, in general, do you have a stable internet wifi connection?

**Comment by djohana** [comment] 2021-03-16 11:58
@dsarkar 
I’m mostly connected to the wifi (90% of the time)
The internet is stable, in general.

Could it have anything to do the fact that my husband and I are in the same apartment? He tested positive last week

**Comment by dsarkar** [comment] 2021-03-16 12:01
@djohana 

> Could it have anything to do the fact that my husband and I are in the same apartment? He tested positive last week

I am pretty sure that this is not related to the error 13 notification.
But highly probable that for that reason you got a high-risk encounter notification.

**Comment by Ein-Tim** [comment] 2021-03-17 05:39
Good morning @djohana 

Please wait till ca. 12:00h and the open the app. 
Let us know what it shows 👍

**Comment by djohana** [comment] 2021-03-17 07:41
@Ein-Tim morning, I actually opened yesterday to plead the new qr and the app loaded for like 1 minute and then started working normally again.

**Comment by Ein-Tim** [comment] 2021-03-17 07:55
@djohana 

Okay, nice to hear that it works again! 
If you consider this as solved, feel free to close this issue.

@dsarkar
The Devs would have to decide wether they would like to further investigate this. 

Have a nice day. 
Tim

**Comment by djohana** [comment] 2021-03-17 08:03
@Ein-Tim yes, thank you so much!

**Comment by dsarkar** [comment] 2021-03-17 09:29
@Ein-Tim @djohana 
Thanks for the feedback. Please re-open if the issue should re-appear. Best wishes, DS.

**Comment by dsarkar** [comment] 2021-03-31 10:48
@djohana We have another very similar case as yours, see https://github.com/corona-warn-app/cwa-app-ios/issues/2316. We would like to investigate further the root of this issue, if possible with your help. Could you let us know if the test result was positive or negative on the phone with the error 13 notification? Many thanks, your feedback is very much appreciated.

**Comment by Ein-Tim** [comment] 2021-03-31 11:02
@dsarkar 

Do you try to reproduce this internally? 

Suggestion: Developers add test result and this returns positive. Risk detection off -> CWA update -> risk detection on. 

What happens?

**Comment by djohana** [comment] 2021-03-31 12:21
@dsarkar hi! It was positive. And it happened  to me again last week. Same problem. My husband did the test (positive). I opened the app and it had the notification error 13 again. then I did a test again, the app shows me the result (positive), I was asked if I had symptoms, for how long. Then it kind of closes, I open it and the test is gone and the error keeps on showing from time to time. I just don’t open the app as often as before to try to reduce the error

**Comment by dsarkar** [comment] 2021-03-31 14:30
@djohana Thank you very much for the information. Hope you all are feeling better now. Best wishes, stay safe! DS

**Comment by dsarkar** [comment] 2021-04-05 07:05
Good morning @djohana,

Is the error 13 notification gone or do you still get the notification every day?
If that is the case, did you try this: https://github.com/corona-warn-app/cwa-app-ios/issues/2316#issuecomment-810558754? 

Thanks for the feedback, best wishes, DS 

---
Corona-Warn-App Open Source Team

**Comment by djohana** [comment] 2021-04-05 08:03
@dsarkar hi, yeah I still get it like every second day. I will try this and let you know. I also noticed than in the exposure notification  the option to automatically inform others is off and It does not let me turn it on. 

Thanks for keep on working on the case. Have a nice day

**Comment by Ein-Tim** [comment] 2021-04-05 08:11
@djohana 

> the option to automatically inform others is off and It does not let me turn it on.

This is intended, see #2176.

**Comment by dsarkar** [comment] 2021-04-05 08:33
@djohana OK, thank you for the information. Enjoy your day as well!

**Comment by Ein-Tim** [comment] 2021-05-02 08:31
Version 2.1 which fixed the unintended occurrence of Error 13 has been released!

It will reach all users in the next 48 hours.

See GitHub Release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.1.1 

The PR that fixed this was #2492.

Please update your App, confirm the fix and then close this issue.

Thank you!

**Comment by dsarkar** [comment] 2021-05-03 13:12
Hi @djohana ,

Siehe den Kommentar oben von @Ein-Tim. Wir würden uns über Feedback von Dir freuen: Kannst Du bestätigen, dass der Fehler bei Dir nicht mehr auftaucht? Vielen Dank, Beste Gruesse, DS


See comment above from @Ein-Tim. We would appreciate your feedback. Can you confirm that this is no more issue for you? Many thanks. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by djohana** [comment] 2021-05-05 09:50
@dsarkar 
I just updated the app. Opened and the error came. Should I maybe reinstall the app? 
![FBE21604-1448-444B-AD1A-8CEC6ABD3398](https://user-images.githubusercontent.com/80750994/117123956-fced2900-ad97-11eb-87e0-c41b43671a40.png)

**Comment by dsarkar** [comment] 2021-05-05 09:53
@djohana thanks for the feedback. After updating it happens to some users to get error 13, which is not a problem if to is a single event. Please, let us know if tomorrow and the day after tomorrow all is fine. Thanks again! Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by djohana** [comment] 2021-05-11 11:47
@dsarkar hi! It seems to be working correctly. I haven’t got any error. Thanks

**Comment by dsarkar** [comment] 2021-05-11 12:19
@djohana Thanks for the feedback. We will close this issue now. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Closed by dsarkar** 2021-05-11 12:19 UTC
Labels: bug, mirrored-to-jira
