### ISSUE TITLE
Can't activate exposure logging after iCloud backup restore

### ISSUE THREAD

**Issue by ferdinand** [corona-warn-app/cwa-app-ios#754] opened 2020-06-23 14:09 UTC
## Avoid duplicates

* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is not already reported in another issue

## Describe the bug

After restoring an iOS 13.6 Public Beta 2 iCloud backup to my iPhone X. I was no longer able to activate exposure logging within the app. Using the reset function of the app didn't help as well, but only reinstalling it.

## Expected behaviour

I'm aware that the random IDs are not backed up, but the app should continue to work after an iCloud backup restore without the need of reinstalling it.

## Steps to reproduce the issue

https://www.icloud.com/photos/#0rlNvI8yY61JImMFCrG8QvdDQ

## Technical details

- iOS Version: 13.6 Public Beta 2
- Device: iPhone X

---
Internal Tracking ID: EXPOSUREAPP-1948

**Comment by haosap** [comment] 2020-06-23 15:40
Hi @ferdinand 
Could you please describe it more, like the following:
1.  Upgrade the system.
2. Restore the backup.
3. re-run the app
4. Cannot activate the EN
is it correct?

**Comment by ferdinand** [comment] 2020-06-23 17:02
@haosap The reason for the restore for the restore of the backup was not an upgrade, but a downgrade from iOS 14 Developer Beta 1 to iOS 13.6 Public Beta 2. Besides that it's correct.

What I've done is:

1. Installed the app on its release day (pretty sure I was already on iOS 13.5 Public Beta 2 back then)
2. Made sure that iOS did an automatic iCloud backup yesterday
3. Upgraded OTA to iOS 14 Developer Beta 1
4. Downgraded to iOS 13.5.1 today (I didn't know there is a restorable IPSW file available for iOS 13.6 Public Beta 2. Hence the little detour.)
5. Upgraded OTA to iOS 14.6 Public Beta 2
6. Erased all contents and settings
7. Restored the backup done in step 2
8. Re-run the app
9. As far as I remember the app asked me again if I want to activate the EN and if I want to allow notifications, I agreed to both but iOS didn't bring up the system's permission dialogs
10. The app returned that the EN is not activated 
11. Tried unsuccessfully to activate it (see video)
12. Used the app's reset function
13. Same behaviour as in steps 10 and 11
14. Deleted the app
15. Reinstalled the app
16. Went through the onboarding process, gave the necessary permissions when the system asked me fo it, and everything works fine

**Comment by SebastianWolf-SAP** [comment] 2020-07-12 06:53
Recently, there are also reports that backup/restores may as well lead to an endless loop, see #896.

**Comment by BongoUser** [comment] 2020-07-30 11:06
Hey, any updates here? You have a workaround? Should we delete and reinstall the app? 
I have the same problem? 
Kind Regards

**Comment by ferdinand** [comment] 2020-07-30 11:15
@BongoUser The only workaround seems to be to reinstall the app. Since iOS doesn't backup the keys they're lost anyway. Thus, it's safe to do so.

**Comment by tkowark** [comment] 2020-07-30 11:44
Yes, unfortunately, that's currently the way to go.

**Comment by arm-in** [comment] 2020-08-05 20:07
Same issue here.
Migration from iPhone 7 to 11 on iOS 13.6 via iCloud backup => CWA won't work, endless loop on the welcome page

**Comment by Ein-Tim** [comment] 2020-08-06 11:28
I think it would be useful if we change this title to something like "App doesn't work after Backup restore" because not only people who restore from iCloud have this problem, people who restore from iTunes, etc. have this or other restore problems.

**Comment by darthvader007** [comment] 2020-08-28 09:42
Is there any update on that? I can confirm that this issue happens all the time doesn't matter if iCloud or iTunes Restore.
Tested with an iPhone 6S Backup to iPhone 7 and an iPhone7 to iPhone 11.

It is easy to fix for someone with technical understanding, because you just need to redownload the app, but for example elderly people don't know this. I had one case in my family where the app was not working for a week due to this issue.

**Comment by w-m** [comment] 2020-08-28 09:44
Confirming another case of the endless loop issue, after migrating phones through iCloud backup, no beta versions involved. Also fixed by reinstalling the app on the new phone,

**Comment by svengabr** [comment] 2020-08-28 12:31
I can also provide a video on that since we experienced the bug yesterday. iPhone 11 Pro

![RPReplay_Final1598449748](https://user-images.githubusercontent.com/4686874/91560949-fcfc7580-e93a-11ea-9897-0b1e5a99ae80.gif)

**Comment by Ein-Tim** [comment] 2020-09-11 11:49
Related PR: https://github.com/corona-warn-app/cwa-app-ios/pull/1158

**Closed** 2020-09-11 12:44 UTC
Labels: apple, bug, community, mirrored-to-jira

**Comment by Ein-Tim** [comment] 2020-09-25 10:42
@whiskey and @svengabr 
Can you confirm that this Issue will be solved with the 1.4.0 release?

**Comment by svengabr** [comment] 2020-09-25 12:46
@Ein-Tim I have updated the attached Jira Ticket EXPOSUREAPP-1948 and asked for feedback from the developers. I will keep you updated!

**Comment by thomasaugsten** [comment] 2020-09-25 12:52
This fix is in release 1.4

**Comment by Luke1410** [comment] 2020-10-18 14:24
With the release of the iPhone 12 more and more people will run into this issue, I'm afraid. As far as I understand, the behavior of the app in 1.4 was changed, so affected users no longer end up in the endless-loop but rather the app correctly handles the issue and resets the DB so the current workaround (of having to remove and reinstall the app, which practically only a subset of affected users will spend the time on to figure this out themselves) is no longer required.

With the fix being available for around 23 days meanwhile, it doesn't seem that the severity of the issue is taken into account. From the looks of it (through the eyes of a QA manager), this issue would deserve a hotfix release by itself already with a much shorter distribution delay than the 1 month which is approaching now.

Again: In light of more and more users going to run into the problem now with the new iPhone being released, I'd like to raise the point that maybe it's worth considering another 1.3.x hotfix release, if 1.4 is not already around the corner in the next week.

**Comment by Ein-Tim** [comment] 2020-10-18 14:26
@Luke1410 

1.5.0 will be released tomorrow, @thomasaugsten is this Fix included in 1.5.0?

**Comment by Luke1410** [comment] 2020-10-19 11:10
Confirmed that the 1.5.0 release fixed the endless dialog loop in my case. App works again as expected.
