### ISSUE TITLE
Number of days since last exposure is missleading as this is a relative distance without the knowledge of the concrete starting point.

### ISSUE THREAD

**Issue by rude78** [corona-warn-app/cwa-app-ios#1406] opened 2020-10-25 21:28 UTC
Yesterday (Saturday) evening at 21:44 the warn app got updated in the background and reported an increased risk incident. 
Unfortunately I did not notice the update till today Sunday morning. 
The app showed "3 days since last exposure". As I did not know the start of this relative information it was not clear to me wether 
3 days ago was Wednesday or Thursday. Depending on 3 days ago refers to today (Sunday) or refers to yesterday (Saturday) when the last updates was done.

After I got the new update today (Sunday 21:45) I found out that the 3 days ago are relative to the date of last update. This is not intuitive. 

Suggestion:
Please add the explicit / concrete date of exposure. This is clear in all bordercases.

**Comment by Ein-Tim** [comment] 2020-10-25 22:05
Please see: https://github.com/corona-warn-app/cwa-app-ios/issues/1032

**Comment by dsarkar** [comment] 2020-10-27 07:53
Dear @rude78 , 

thank you for your contribution. 

As @Ein-Tim comments, this is a duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/433.
Please continue any further discussion there. I will close this issue.

Best regards,
DS

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment] 2020-10-27 07:54
Duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/433

**Closed by dsarkar** 2020-10-27 07:54 UTC
Labels: duplicate
