### ISSUE TITLE
Closing #880 before fix is distributed is wrong IMHO

### ISSUE THREAD

**Issue by jwildeboer** [corona-warn-app/cwa-app-ios#895] opened 2020-07-11 18:31 UTC
Could you please keep #880 open until the update is distributed and confirmation that the solution works is collected?

Many here have added the version number of their app and they haven't updated to the current latest version. Some here are still on 1.0.2. Just closing the bug BEFORE the fix is distributed is IMHO bad style.

Also - could you please elaborate how the fix to #880 avoids causing checks to miss possible exposures for at least the last 24 hours, possibly up to 72 hours or more until the update is published and the checks have been performed.

**Comment by sin-azucar** [comment] 2020-07-12 15:53
Fix is still not available - at least not for me.

I agree that this was closed in an overhasty way because people will continue to receive an incomplete risk calculation for at least today and potentially tomorrow as well and they won‘t know about it unless they sift through closed issues. 😞

**Comment by jwildeboer** [comment] 2020-07-12 22:05
The update to 1.0.7 is still not available at 2020-07-13 00:03 CEST. My next check will occur in 9 hours. If the update hadn't arrived by then, it will mean 3 days of checks with only half of the keys being checked. That means I could have potential exposures that will not be found. That's IMHO a relevant risk for me.

**Comment by jwildeboer** [comment] 2020-07-13 07:59
The 1.0.7 update is still not available in the App Store. My app has just performed its check. Now 3 days in a row with only 7 sets checked. 3 days with a high risk of the app not recognising possible exposures. This is alarming. 

![image](https://user-images.githubusercontent.com/873028/87279543-88d35300-c4ef-11ea-9657-fc7017e16652.jpeg)

![image](https://user-images.githubusercontent.com/873028/87279544-8ffa6100-c4ef-11ea-8e07-150509242cd4.jpeg)

![image](https://user-images.githubusercontent.com/873028/87279545-97ba0580-c4ef-11ea-8a44-3c21ee93b745.jpeg)

**Comment by jwildeboer** [comment] 2020-07-13 08:52
The update has arrived. But my app already did the risk calculation an hour ago. So earliest tomorrow I will get a "full" check. That's 96 hours with only partial exposure risk calculation. Please make sure this never happens again.

![image](https://user-images.githubusercontent.com/873028/87284527-c38cb980-c4f6-11ea-957f-2515f60d3a47.jpeg)

**Comment by inf2381** [comment] 2020-07-13 10:00
Agree with you here. I'm sorry for that. Usually, the update is available within 2 - 5 hours after our upload and I closed the issue on Saturday evening because I thought the update will be available just a few hours later. But this time, Apple rejected the build because it wasn't working on iPad (which is not supported by their ExposureNotification framework and also not listed as supported device family in this app). So there was some escalation going on until this update finally went through 2 hours ago..

**Comment by sin-azucar** [comment] 2020-07-13 10:36
I can confirm that the update resolved the issue and 14 checks are being made again, see screenshot ("hoy" = "today" 😉)

![comprobaciones](https://user-images.githubusercontent.com/67788972/87295431-749a5080-c505-11ea-886e-c2cbb5564ef2.jpg)

**Comment by jwildeboer** [comment] 2020-07-13 11:17
Unfortunately on both my iPhones the update came *after* the daily check was performed. So earliest tomorrow I will get a full check and I will never know how many possible exposures were lost in the last 96 hours. I don't know how many keys have expired in these 96 hours and will thus not be included in the check tomorrow.

I hope this bug results in better tests to make sure this never can happen again.

:(

**Comment by mss1010** [comment] 2020-07-13 12:48
> Unfortunately on both my iPhones the update came _after_ the daily check was performed. So earliest tomorrow I will get a full check and I will never know how many possible exposures were lost in the last 96 hours. I don't know how many keys have expired in these 96 hours and will thus not be included in the check tomorrow.
> 
> I hope this bug results in better tests to make sure this never can happen again.
> 
> :(

The chances that you missed something are extremely low, due to the low infection rates and low usage of the app.
Basically you are right, but I wouldn´t worry too much.

**Comment by gkgg** [comment] 2020-07-13 16:12
With v1.0.7 available today (07/13/20) around noon (well, at least for me it took so long), I had to wait until early evening to check if there would be any change.
From what I can see I can confirm that today 14 sets of data appear as downloaded/processed in the corresponding log. Now wait >24h to see if it will still work as expected and necessary.

**Comment by Tho-Mat** [comment] 2020-07-14 05:10
@jwildeboer 
Keys expire 14 day after they have been published. So the keys publish 25.06.20-29.06.20 have been expired.
If your device was running the CWA in the times below you did not miss any key.
The keys form 25.06 were available 26.06 - 08.06 
The keys from 26.06 were available 27.06 - 09.06 
The keys from 27.06 were available 28.06 - 10.06 
The keys from 28.06 were available 29.06 - 11.06 
The keys from 29.06 were available 30.06 - 12.06 
...

**Comment by Tho-Mat** [comment] 2020-07-14 08:18
If you get only 13 files updated yesterday, look here
[https://github.com/corona-warn-app/cwa-app-ios/issues/880#issuecomment-658038202]

**Comment by jwildeboer** [comment] 2020-07-14 09:11
I had the full Checks performed today. So safe to close from my perspective.

**Comment by mss1010** [comment] 2020-07-15 10:17
@jwildeboer You can close this issue I guess.

**Closed** 2020-07-15 10:33 UTC
