### ISSUE TITLE
Only seven exposure checks today

### ISSUE THREAD

**Issue by mss1010** [corona-warn-app/cwa-app-ios#880] opened 2020-07-10 08:37 UTC
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question has not already been asked in another issue

## Your Question

Since today after I installed update 1.0.5 I only got 7 exposure checks. In the FAQ its stated, that it should check the last 14 days.

But I‘m not sure about this process. So is this an error?

![C0189748-964D-4B4E-B793-8139BBBEE904](https://user-images.githubusercontent.com/36116339/87134596-2f71e680-c299-11ea-8fe8-40e426199ced.jpeg)

**Comment by gkgg** [comment] 2020-07-10 16:33
From what I can see, I can confirm:
14 sets downloaded yesterday,
7 sets downloaded today.

![image](https://user-images.githubusercontent.com/67552666/87177346-cb244680-c2db-11ea-889d-aee343bc90b9.jpeg)

**Comment by MartinBode14** [comment] 2020-07-10 19:10
Same here
![IMG_3820](https://user-images.githubusercontent.com/68126373/87189886-c23e6f80-c2f1-11ea-96f3-81c355a3bd56.png)

**Comment by jwildeboer** [comment] 2020-07-11 07:36
Confirm. I have installed the app the day it came out. I suspect backend bug?![image](https://user-images.githubusercontent.com/873028/87219271-08c7b480-c35a-11ea-874d-32a4fb97aac8.png)

**Comment by jwildeboer** [comment] 2020-07-11 07:48
Added issue #663 to the cwa-app-server as I suspect this is a problem on the backend and not the app.

**Comment by jwildeboer** [comment] 2020-07-11 08:32
Also - I think this qualifies as bug, not as question.

**Comment by mss1010** [comment] 2020-07-11 08:47
@inf2381 @i336616 Can you please check this, and change the label to bug if applicable?

**Comment by Tho-Mat** [comment] 2020-07-11 09:23
I still have installed 1.0.2 (2) and got 14 
so I think its not the server.

![20200711_090041000_iOS](https://user-images.githubusercontent.com/67630959/87220951-ac1fc600-c368-11ea-8b73-f8a79c789a3b.png)

**Comment by jwildeboer** [comment] 2020-07-11 09:29
Yesterday it performed 14 checks, that's ok. But today only 7. your check was yesterday at 14:00, please Check again after today's check.

**Comment by jwildeboer** [comment] 2020-07-11 11:50
If this isn't fixed in the next 12-15 hours, it means millions of users will have incomplete risk checks for at least 48 hours. Please upgrade this to bug and escalate ASAP.

**Comment by sin-azucar** [comment] 2020-07-11 11:57
Could it be due to the repackaging that happens on the server side that is described here? ➡️ https://github.com/corona-warn-app/cwa-server/issues/650

In this case, nothing would be lost, the data is just packaged differently (in fewer files, i.e. there‘s not necessarily one file per day anymore).

**Comment by jwildeboer** [comment] 2020-07-11 12:02
Sure. Expunging inactive keys makes sense, but a sudden reduction of 7 days and, AFAICS by comparing hashes on my iPhone, I didn't receive the new keys for yesterday at all.

**Comment by SebastianWolf-SAP** [comment] 2020-07-11 12:18
Our dev team has seen this and is investigating the exact reason. We will update you here and of course also flag the issue accordingly. 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by jwildeboer** [comment] 2020-07-11 13:51
Hier die 7 Hashes die beim heutigen Check auf meinem iPhone verwendet wurden:

```
    {
      "Hash" : "E7CBE87CB3A7F590E4DFC08DB2E4F6842796548E06C19EBF999E27A9B5BDE8F0",
      "RandomIDCount" : 1280,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-11 09:33:43 +0200"
    },
    {
      "Hash" : "7F8A901375A46C6DA02A57040A861EFEE2BB7D581F661C52C0FDBD3EA3FE6460",
      "RandomIDCount" : 760,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-11 09:33:43 +0200"
    },
    {
      "Hash" : "15851D1345471A71AA4C32AF3613E3A75908C6777144E8FB6BC8B01A7083D020",
      "RandomIDCount" : 1270,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-11 09:33:43 +0200"
    },
    {
      "Hash" : "2064759A6C457046D28CCE87F3A325BE7DF1AEFE82AC9F34D65D2D193D86FCAA",
      "RandomIDCount" : 2680,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-11 09:33:43 +0200"
    },
    {
      "Hash" : "3718D4F1C65880F45AD7A2831864570526FAC408D98CD8C9738639155AEC9A06",
      "RandomIDCount" : 1990,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-11 09:33:43 +0200"
    },
    {
      "Hash" : "F5A823E08898DE23A6F1976285F6B4E1F9FE51C4AA4261683186EF27B16B4E97",
      "RandomIDCount" : 1960,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-11 09:33:43 +0200"
    },
    {
      "Hash" : "42E5015A7E48248B77F540C15D5C1E853341CF57B072576F4193E968C1483FBC",
      "RandomIDCount" : 945,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-11 09:33:43 +0200"
    }
  ],
  "DeviceProductType" : "iPhone12,1"
}
```

**Comment by jwildeboer** [comment] 2020-07-11 13:53
Und zum Vergleich die 14 die beim gestrigen Check verwendet wurden:

```
{
      "Hash" : "17C8D19FC3255130D60D1AA06946CF2A8114D906A2BF1FCFD4876C23792B039A",
      "RandomIDCount" : 1450,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-10 05:53:25 +0200"
    },
    {
      "Hash" : "E7CBE87CB3A7F590E4DFC08DB2E4F6842796548E06C19EBF999E27A9B5BDE8F0",
      "RandomIDCount" : 1280,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-10 05:53:25 +0200"
    },
    {
      "Hash" : "7F8A901375A46C6DA02A57040A861EFEE2BB7D581F661C52C0FDBD3EA3FE6460",
      "RandomIDCount" : 760,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-10 05:53:25 +0200"
    },
    {
      "Hash" : "15851D1345471A71AA4C32AF3613E3A75908C6777144E8FB6BC8B01A7083D020",
      "RandomIDCount" : 1270,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-10 05:53:25 +0200"
    },
    {
      "Hash" : "2064759A6C457046D28CCE87F3A325BE7DF1AEFE82AC9F34D65D2D193D86FCAA",
      "RandomIDCount" : 2680,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-10 05:53:25 +0200"
    },
    {
      "Hash" : "3718D4F1C65880F45AD7A2831864570526FAC408D98CD8C9738639155AEC9A06",
      "RandomIDCount" : 1990,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-10 05:53:25 +0200"
    },
    {
      "Hash" : "F5A823E08898DE23A6F1976285F6B4E1F9FE51C4AA4261683186EF27B16B4E97",
      "RandomIDCount" : 1960,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-10 05:53:25 +0200"
    },
    {
      "Hash" : "42E5015A7E48248B77F540C15D5C1E853341CF57B072576F4193E968C1483FBC",
      "RandomIDCount" : 945,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-10 05:53:25 +0200"
    },
    {
      "Hash" : "8D32BC260A0C5FC662F474F7750008A374628A8BC79AA6541EEF4A6B1890F579",
      "RandomIDCount" : 535,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-10 05:53:25 +0200"
    },
    {
      "Hash" : "50324DC3F671099049E694AE5E90BAA144E2ACA10CB16173AFFEF67444EFAC75",
      "RandomIDCount" : 180,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-10 05:53:25 +0200"
    },
    {
      "Hash" : "DE774A8811990298A0D2EB9E6ABBFB1BBD39723CC5DE25528AC8C9B7F9727426",
      "RandomIDCount" : 495,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-10 05:53:25 +0200"
    },
    {
      "Hash" : "4260D0054AD4ED046687792FCC7F5AF7E3C95DF858EF6348D9DA86FF905F09F2",
      "RandomIDCount" : 715,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-10 05:53:25 +0200"
    },
    {
      "Hash" : "BCF4FAF20C0121E47C8E764303B2537509FB1594F66B61C1BA8C68F9AD7156EA",
      "RandomIDCount" : 495,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-10 05:53:25 +0200"
    },
    {
      "Hash" : "94B8FE9CD7C80C854AAABC0846FEBEEE886C5336412E9B2C49D122725FB0A276",
      "RandomIDCount" : 620,
      "MatchCount" : 0,
      "DataSource" : "de.rki.coronawarnapp",
      "Timestamp" : "2020-07-10 05:53:25 +0200"
    },
```

**Comment by Tho-Mat** [comment] 2020-07-11 14:45
Just checked my version  1.0.2 (2)  for today:
download 14
![20200711_131222000_iOS](https://user-images.githubusercontent.com/67630959/87226701-d63bad00-c395-11ea-8b5f-1c684e6616d2.png)

**Comment by gkgg** [comment] 2020-07-11 15:44
[update]
After receiving only seven sets yesterday, today again only seven sets have been received.

![image](https://user-images.githubusercontent.com/67552666/87227904-1868ec80-c39e-11ea-9aca-23867f7718b7.jpeg)

**Comment by inf2381** [comment] 2020-07-11 16:53
Fixed the issue in the linked PR. Hotfix has been submitted for review and will hopefully be available over night.

**Closed by inf2381** 2020-07-11 16:54 UTC
Labels: bug, in review

**Comment by jwildeboer** [comment] 2020-07-11 18:24
Could you please keep this bug open until the update is distributed and confirmation that the solution works is collected?

**Comment by jkrwdf** [comment] 2020-07-14 08:04
I have no iOS device, but in the name of a colleague who has and who received an update to version 1.0.7 yesterday, I report that there were 13 (thirteen) verifications executed after the update (screenshot: 20:21 CEST), not 14.

![V13](https://user-images.githubusercontent.com/5329491/87400479-2777b680-c5b9-11ea-8729-cd82673ae853.jpeg)

**Comment by Tho-Mat** [comment] 2020-07-14 08:11
That ok for that time. 
At 20:05 all parts of 29.06.2020 had been removed and 13.07.2020 was not published.
So in the time from 20:05-2:05 there were only 13 days to test
