### ISSUE TITLE
Translucent tab bar in contact journal

### ISSUE THREAD

**Issue by max-ae** [corona-warn-app/cwa-app-ios#3728] opened 2021-10-20 14:53 UTC
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 12 Pro Max
- iOS version: 15.0.2
- App version: 2.12.1

## Describe the bug

Tab bar in diary view is translucent when selecting person or location

## Steps to reproduce the issue

1. go to contact journal
2. tap on a day
3. see bug

![image](https://user-images.githubusercontent.com/4730112/138117130-64e15777-2b8b-49cc-9f70-bb01fe1e641a.jpeg)

---
Internal Tracking ID: [EXPOSUREAPP-9910](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9910)

**Comment by dsarkar** [comment] 2021-11-01 11:04
Internal Tracking ID: [EXPOSUREAPP-10178](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10178) duplicate of
Internal Tracking ID: [EXPOSUREAPP-9910](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9910)

**Comment by Ein-Tim** [comment] 2021-11-03 17:40
PR: #3788 merging into `release/2.14.x`.

**Comment by Ein-Tim** [comment] 2022-02-24 18:51
@dsarkar Please, could you inform the team that PR #3788 did **not** sufficiently fix this issue? See https://github.com/corona-warn-app/cwa-app-ios/issues/3161#issuecomment-1032963516.

**Comment by max-ae** [comment] 2022-02-24 18:55
Addition from my side:

Bug also occurs if the following is done:
1. select a day in the journal
2. slightly swipe from the left hand side of the screen as if going back to the overview, but don't complete the swipe to stay on the day view
3. tab bar is transparent again

**Comment by dsarkar** [comment] 2022-02-25 13:55
@max-ae Thanks for reporting. In which iOS do you reproduce this issue?

**Comment by max-ae** [comment] 2022-02-25 14:02
> @max-ae Thanks for reporting. In which iOS do you reproduce this issue?

iOS 15.3.1 on iPhone 12 Pro Max, CWA version 2.18.1

**Comment by Ein-Tim** [comment] 2022-07-07 15:49
@dsarkar Version 2.25 seems to be mostly a bugfix release. Could you maybe ask around internally if this could be fixed with that version?

**Comment by dsarkar** [comment] 2022-07-09 09:25
@Ein-Tim ok, I will check.

**Comment by dsarkar** [comment] 2022-07-19 07:43
@Ein-Tim Fix will not be included in 2.25

**Comment by Ein-Tim** [comment] 2022-07-19 08:31
@dsarkar Ok, thanks for the info. Is there any plan to fix this issue soon? I mean it is quite an annoying issue, which is known for many months now.

**Comment by dsarkar** [comment] 2022-10-31 11:49
@max-ae @Ein-Tim FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/4869

**Comment by Ein-Tim** [comment] 2022-11-19 22:55
@dsarkar The "Fix 2.29" label should be renamed to "Fix 3.0".

**Comment by Ein-Tim** [comment] 2023-01-18 16:37
@dsarkar 

1. Please change the label to "Fix 3.0". 
2. I can confirm that this issue has been fixed in version 3.0. It can therefore be closed.

**Comment by larswmh** [comment] 2023-02-24 12:38
Thanks to all participants,

I'm closing this issue now as it has been fixed in version 3.0.

**Closed as completed by larswmh** 2023-02-24 12:38 UTC
Labels: bug, mirrored-to-jira, contact-journal, Fix 3.0
