### ISSUE TITLE
Local stored trace data should be available in backups 

### ISSUE THREAD

**Issue by Eisbaerhaar** [corona-warn-app/cwa-app-ios#1416] opened 2020-10-27 10:23 UTC
After configuring my new iPhone by transferring data from the old one, the data of the Corona-Warn App from past 14 days has not been transferred.
I will not be warned in the next 14 days if there was a risky contact until I configured the new iPhone. 
It would be better to include these data in backups and to transfer these to an iPhone being configured with that.

**Comment by Ein-Tim** [comment] 2020-10-27 12:52
Hey @Eisbaerhaar 
There is already an Issue requesting this: 
https://github.com/corona-warn-app/cwa-wishlist/issues/8
Please close this Issue so we can focus the discussion on one Issue 👍

**Comment by abro1i** [comment] 2020-10-27 12:58
Hi @Eisbaerhaar,

thanks for your feedback. 

As @Ein-Tim already mentioned, this issue is under discussion here: https://github.com/corona-warn-app/cwa-wishlist/issues/8

Best regards, 

ABB 

Corona-Warn-App Open Source Team

**Comment by abro1i** [comment] 2020-10-27 12:59
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/8

**Closed** 2020-10-27 12:59 UTC
Labels: enhancement
