### ISSUE TITLE
Suspicous frequency of entries in log

### ISSUE THREAD

**Issue by Ichabod** [corona-warn-app/cwa-app-ios#803] opened 2020-06-29 19:30 UTC
Look at this log:
![threema-20200629-210213-5db692b4fe7540d8](https://user-images.githubusercontent.com/3101260/86046991-74527d80-ba4e-11ea-8338-ef8467a673bd.jpg)

First day: one poll
Second day: two polls
Third day: three polls
And so on... 
. 
. 

As a professional programmer I consider this behavior as a symptom of a potential bug. Also shouldn't there be only one poll per day? 

By the way I also get the NEerrorDomain message which is said to be raised by too frequent framework polls. Coincidence? 

- iOS Version: 13.5.1
- Device: iPhone 11

**Comment by ferdinand** [comment] 2020-06-29 21:02
Duplicate of #778 and #782. Should be added to the FAQ.

**Comment by tkowark** [comment] 2020-06-30 08:30
And is now added to the FAQ: https://www.coronawarn.app/en/faq/#multiple_exposure_checks :)

**Closed by tkowark** 2020-06-30 08:30 UTC
Labels: bug
