### ISSUE TITLE
App doesn't start correctly on iOS14 beta after Update

### ISSUE THREAD

**Issue by sh89** [corona-warn-app/cwa-app-ios#760] opened 2020-06-24 06:11 UTC
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is not already reported in another issue

## Describe the bug

When opening the App on iOS14 it only shows a black/white screen (depending on dark/bright Theme).

## Expected behaviour

Correct start of the app

## Steps to reproduce the issue

Start the App on an updated iOS14 device

## Technical details

- iOS Version: 14.0
- Device: iPhone Xs

## Possible Fix

Maybe look at the Risk-Detection module.
After reinstalling the app risk detection can't be activated (ENErrorDomain-Fehler 3.)

## Additional context

After Migration from iOS13 to iOS14
![IMG_1582](https://user-images.githubusercontent.com/42806483/85507121-178c3880-b5f2-11ea-8414-4f02910baf59.PNG)

After Fresh install on iOS14
![image0](https://user-images.githubusercontent.com/42806483/85507102-0cd1a380-b5f2-11ea-9271-22b79550f0c6.png)
![image1](https://user-images.githubusercontent.com/42806483/85507113-13f8b180-b5f2-11ea-9bbb-44f1308c6790.png)

**Comment by n-thumann** [comment] 2020-06-24 06:12
Duplicate of https://github.com/corona-warn-app/cwa-app-ios/issues/749 ✌️

**Comment by sh89** [comment] 2020-06-24 06:16
Duplicate... Sorry!

**Closed** 2020-06-24 06:16 UTC
Labels: bug
