### ISSUE TITLE
Do vac-certs still get validated with locale time

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-app-ios#3912] opened 2021-12-01 10:45 UTC
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [?] Question is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Question has not already been asked in another issue

## Your Question

* Source File:
* Line(s):
* Question:
Does the app on this screen
![image](https://user-images.githubusercontent.com/73582096/144220149-8fe1cffe-b2bc-49ea-b360-eb58b40fdd2b.jpeg)
,if the cert gets valid in this date, show the cert as valid on 0:00, even if the cert gets valid on 1:00 or 2:00 (summertime).

**Comment by dsarkar** [comment] 2021-12-01 11:14
@jucktnich Thanks for question. We try to get an answer by tomorrow.

**Comment by dsarkar** [comment] 2021-12-02 12:12
@jucktnich It is UTC time.

**Comment by jucktnich** [comment] 2021-12-02 12:45
So you changed the behaviour of this box?

**Comment by dsarkar** [comment] 2021-12-02 14:58
@jucktnich not sure what the exact question is. I am not aware of any change regarding using UTC or LT here in this context. I remember a bug where it was one day to late or similar.

**Comment by Ein-Tim** [comment] 2021-12-02 15:04
@dsarkar Probably this: https://github.com/corona-warn-app/cwa-app-ios/issues/3385

**Comment by jucktnich** [comment] 2021-12-02 15:12
@Ein-Tim the problem is that the info box (red-outlined by me) showed, that the cert is valid.

**Comment by Ein-Tim** [comment] 2021-12-02 15:20
@jucktnich So the problem is that the box uses local time? According to @dsarkar not. This would mean that the app and the check validity feature is now consistent.

**Comment by jucktnich** [comment] 2021-12-02 15:23
Exactly, this was the case and I wanted to now, if this is fixed now.

**Comment by svengabr** [comment] 2021-12-16 09:40
@jucktnich since there were already answers from the team/developers, is there anything else that is not answered from your point of view?

If all questions are answered I would kindly ask you to close this issue.

Thanks!

**Comment by jucktnich** [comment] 2021-12-16 16:35
Sorry, GitHub weirdly doesn't show me the button for this 🤷‍♂️

**Comment by Ein-Tim** [comment] 2021-12-16 17:01
@jucktnich 

Are you using GitHub mobile? The close button was moved to the 3 dot overvflow menu (where you can also edit the title of your issue). This also confused me 😅

**Comment by jucktnich** [comment] 2021-12-16 17:02
@Ein-Tim yeah thanks 😅🤦‍♂️

**Closed** 2021-12-16 17:02 UTC
Labels: question
