### ISSUE TITLE
Glitch in scrolling the main screen

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-app-ios#991] opened 2020-08-01 22:18 UTC
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

In a specific scenario, the main screen jumps during scrolling. See details below.

## Expected behaviour

Smooth scrolling

## Steps to reproduce the issue

Reproduce as follows:
- start cwa and see the main screen
- scroll down to the very bottom.
- select "App Informationen", then back to the main screen
- now scroll slowly up again.
Expected: smooth scrolling
Observed: during scrolling, the screen suddenly jumps up a bit

## Technical details
- cwa v 1.1.2 (0)
- iOS Version: 13.6
- Device: iPhone 8

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-2007](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2007) obsolete
Internal Tracking ID: [EXPOSUREAPP-4732](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4732) in progress
PR https://github.com/corona-warn-app/cwa-app-ios/pull/1890

**Comment by Ein-Tim** [comment] 2020-08-02 18:03
I've tested this on my iPhone XR, there everything is normal. On an iPhone 6s, the glitch occurs.
Could it be that this only happens on smaller screen iPhones?

**Comment by ndegendogo** [comment] 2020-08-02 18:20
> Could it be that this only happens on smaller screen iPhones?

yes, definitely. I think the root cause could be some hard-coded numbers / dimensions in the layout that don't match the smaller screens.

**Comment by GPclips** [comment] 2020-08-04 09:10
Hello @ndegendogo and @Ein-Tim ,

thanks for reporting this issue. I will share it with our developemnt team to work on it as soon as possible.

Thank you,
LMM

Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment] 2020-08-06 06:47
I have now found a different scenario with similar effect, it seems related.

cwa v 1.1.2(0) / iOS 13.6 / iPhone 8

Scenario:

* start cwa
* scroll to the very top
* exit cwa (home button) and start cwa again
* see the very top of the screen as expected
* now scroll to the very bottom
* exit cwa (home button) and start cwa again
Expected: see the very bottom of screen
Observed: visible part of screen is offset from the bottom

And now comes the interesting part:
* scroll again to the very bottom
* exit cwa (home button) and start cwa again
* now you see indeed the very bottom of screen as expected

**Comment by JoachimFritsch** [comment] 2020-10-21 07:01
Dear all, 
are these behaviors still reproducible with V1.5.0? On my device (iPhone 7) I can reproduce any of the above mentioned behavior.

**Comment by ndegendogo** [comment] 2020-10-21 12:22
@JoachimFritsch you **can** reproduce with cwa 1.5.0 or you can **not**? 🤪

We already suspect that it may be related to devices with smaller screen height (like iPhone 8).

I still get those glitched with cwa 1.5.
I'll test and report in more detail later.

**Comment by ndegendogo** [comment] 2020-10-21 23:29
Tested again with configuration: cwa 1.5.0(8) / iOS 14.1 / iPhone 8.

I could reproduce [this scenario](https://github.com/corona-warn-app/cwa-app-ios/issues/991#issuecomment-669739145) exactly as described above.

The original described scenario, however, does no longer jump, but behaves now as follows:
* start cwa and see the main screen
* scroll down to the very bottom.
* select "App Informationen", then back to the main screen
You see a visible offset from the bottom.
* Scroll slowly up again.
Observed: smooth scrolling, as it should be.

**Comment by Ein-Tim** [comment] 2020-10-23 19:08
Can confirm @ndegendogo's founds

**Comment by Ein-Tim** [comment] 2020-11-16 15:32
Issue is still here in 1.6.0/1.6.1. Any updates @JoachimFritsch?

**Comment by dsarkar** [comment] 2020-12-09 12:42
@ndegendogo, @Ein-Tim, issue still present in CWA version 1.7.1. We will update the developers. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment] 2020-12-09 19:45
@dsarkar off-topic:
could you please have a look at [this android ticket](https://github.com/corona-warn-app/cwa-app-android/issues/1786#issuecomment-741766691)?
Seems your robot forgot to pick it up ...

**Comment by Ein-Tim** [comment] 2020-12-17 20:49
Still reproducible with 1.9.1. Only on small screen iPhones. 

BTW: You could add the UX lable here

**Comment by dsarkar** [comment] 2020-12-18 07:42
Hi @Ein-Tim, thanks. Info was forwarded to the developer's ticket. Best, DS

**Comment by Ein-Tim** [comment] 2020-12-28 20:35
This is still reproducible with 1.10.1. 

There is also a new behavior (which also affects large screen iPhones):

1. Scroll all the way down to the bottom
2. Click on the contact diary box
3. Leave the contact diary box
4. See a visible offset from the bottom

First time you do this is the most noticeable offset, second time only a small one and third time everything is normal.

[Screenrecordings.zip](https://github.com/corona-warn-app/cwa-app-ios/files/5748696/Screenrecordings.zip)

**Comment by dsarkar** [comment] 2020-12-29 07:31
Hi @Ein-Tim, thanks. Info was forwarded to the developer's ticket. 

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment] 2021-01-28 21:33
I can't reproduce this anymore under version 1.11.

**Comment by dsarkar** [comment] 2021-01-29 07:34
@Ein-Tim Yes, I can reproduce your first vid on the iPhone 6s

**Comment by dsarkar** [comment] 2021-01-29 07:53
@Ein-Tim all iOS 14.4 ?

**Comment by Ein-Tim** [comment] 2021-01-29 07:55
@dsarkar 
Yes

**Comment by dsarkar** [comment] 2021-01-29 07:57
ok, thanks, updated internal ticket.

**Comment by ndegendogo** [comment] 2021-01-29 08:31
@dsarkar the simulator that Apple provides for iPhone app development has a slow-motion mode, where you can watch more closely if an animation is smooth; and you can configure the simulator for different device types ( = screen sizes).

Of course, this does not tell you about the root cause of a broken animation; but is still very useful to verify if a fix has the desired effect.

**Comment by dsarkar** [comment] 2021-01-29 09:05
- Internal Tracking ID: [EXPOSUREAPP-2007](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2007) obsolete now
- Internal Tracking ID: [EXPOSUREAPP-4732](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4732) new ticket in progress

**Comment by ndegendogo** [comment] 2021-01-31 08:15
Another observation, possibly related: the scrollbar of the main screen jumps. Especially when scrolling upwards.

cwa 1.11.0(9) / iOS 14.2 / iPhone 8

**Comment by dsarkar** [comment] 2021-01-31 08:43
@ndegendogo Good Morning, your observation is forwarded to the devs. Thanks.

**Comment by Ein-Tim** [comment] 2021-02-01 12:47
PR fixing this: #1890

**Comment by ndegendogo** [comment] 2021-02-01 13:19
@Ein-Tim @nickguendling wow - thanks!

**Comment by ndegendogo** [comment] 2021-02-04 12:46
Just tested it with simulator for iPhone 8 on the release/1.12.x branch.
Very smooth now, exactly as it should be.
**Many thanks!**

From my side I regard this as fixed.
@Ein-Tim, I assume you would also like to test it?

**Comment by Ein-Tim** [comment] 2021-02-04 13:31
@ndegendogo 

I would suggest to leave this open until 1.12 is released (10.02.) so that I can test this too (I'm sadly not (yet) able to test it via the emulator). 

Thanks for asking @ndegendogo ❤️

**Comment by dsarkar** [comment] 2021-02-05 08:18
@ndegendogo Thanks for the feedback.

**Comment by Ein-Tim** [comment] 2021-02-10 10:06
1.12.1 has been released (https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.12.1) and I can confirm that this has been fixed. So feel free to close this @ndegendogo, and thanks for waiting!

**Comment by dsarkar** [comment] 2021-02-10 10:12
Dear @ndegendogo  and community.

Thanks again for all the contributions. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Closed** 2021-02-10 11:17 UTC
Labels: Fix 1.12, UX, bug, mirrored-to-jira
